### ISSUE TITLE
Epic: Get rid of OTS (One-Time Secret)

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#10134]
### Summary

The one-time secret (OTS) mechanism is used to deliver secrets to the workspace cluster. It's not location-aware which breaks workspace startup across regions.

### Context

The one-time secret (OTS) mechanism is used to deliver secrets to the workspace cluster. During workspace startup, `server` will create up to three OTS:
- one for the SCM token
- one for the Gitpod token
- potentially one for environment variables

A one-time secret is stored in the database and identified by a UUID. Using this UUID it can be downloaded once, after which it's removed from the database. When the OTS is created, `server` produces a URL from which the OTS can be downloaded. This URL is not location-specific, but uses the load balancer (i.e. gitpod.io/...).

Because the different regions use different databases which are synchronised using db-sync, and because the OTS URL is not region-aware, a workspace created in another region will race db-sync. This can lead to workspace startup failure.

### Value

Removing OTS will
- reduce failure modes (see https://github.com/gitpod-io/gitpod/issues/8096)
- enable cross-region prebuilds (see https://github.com/gitpod-io/gitpod/issues/6650)
- reduce complexity in webapp

### Acceptance Criteria

This work is complete when
- there's a secure way to keep secrets on the workspace side (Kubernetes secrets qualify here)
- the OTS mechanism is no longer in use for shipping secrets
- the OTS mechanism has been removed from the code-base

### Measurement

We are successful here when there's no loss of functionality, and no more need for the OTS mechansim.

# Tasks
- [x] Add "secret" support to ws-manager, where a `StartWorkspace` request can carry named secrets
- [x] Ship the SCM token as named secret and pass it to ws-daemon during `InitWorkspace`
- [x] Ship the Gitpod token as named secret and pass it as environment variable to `supervisor`
- [x] Ship the user's environment variables as named secrets and pass as environment variables to the workspace
- [x] https://github.com/gitpod-io/gitpod/issues/12554
- [x] https://github.com/gitpod-io/gitpod/issues/11318
- [x] https://github.com/gitpod-io/gitpod/issues/13490
- [x] https://github.com/gitpod-io/gitpod/pull/13484
- [x] https://github.com/gitpod-io/ops/issues/5608
- [x] #13632
- [x] #13633
- [x] #13634

**Comment by atduarte** [comment]
Added to workspace teams' project, even though it's shared work between WebApp and Workspace, to avoid this being forgotten.

**Comment by geropl** [comment]
@atduarte Added for Team WebApp as well! Please notify when you have the interface changes (w/o impl, maybe). Happy to jump on the changes on our end.

**Comment by csweichel** [comment]
Next step IMHO is to connect the `protected_secrets` workspace feature flag to CopyCat and roll this out slowly.

**Comment by atduarte** [comment]
@csweichel what about the integration test?

**Comment by kylos101** [comment]
Added: https://github.com/gitpod-io/gitpod/issues/12554 to the epic

**Comment by kylos101** [comment]
@atduarte this is done now, let @Furisto know if you need any support for validation?

**Comment by easyCZ** [comment]
There still seem to be OTS implementation on Server, and it's also being called/used - [metrics](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28gitpod_server_http_requests_total%7Broute%3D~%5C%22.%2Aots.%2A%5C%22%7D%5B1m%5D%29%29%20by%20%28route%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D)

**Comment by Furisto** [comment]
@easyCZ @kylos101 I believe @geropl wanted to remove it.

**Comment by easyCZ** [comment]
From an [internal conversation](https://gitpod.slack.com/archives/C02EN94AEPL/p1669277282001569) it looks like the other client which is generating traffic against the OTS endpoints are Desktop IDEs.

@loujaybee @akosyakov Would you be able to validate if this is indeed the case and the Desktop IDEs use the OTS? What would be the effort to remove OTS from them so that we can remove the endpoints entirely?

**Comment by akosyakov** [comment]
@kylos101 @csweichel Does it mean we can remove SUPERVISOR_ENVVAR_OTS now?

**Comment by kylos101** [comment]
@akosyakov maybe? I added a conversation [here](https://gitpod.slack.com/archives/C02EN94AEPL/p1669676512934339?thread_ts=1669277282.001569&cid=C02EN94AEPL), socializing that it would help to get more data about the client.

**Comment by kylos101** [comment]
@akosyakov @easyCZ  inboxed this epic to IDE and WebApp, as there appears to be some additional cleanup needed to fully remove OTS, and set the status for workspace back to In-Validation.

**Comment by geropl** [comment]
@akosyakov @kylos101 @atduarte FYI: I thought we can close this issue, but it turns out here is one thing left: [AdditionalContentContext](https://github.com/gitpod-io/gitpod/blob/0c0178b610b3d46a1703516cd7ac494c187f6055/components/server/src/workspace/workspace-starter.ts#L1676-L1710). :grimacing: 

@kylos101 Let's sync how we want to go about this one.

**Comment by geropl** [comment]
After discussing wiht @kylos101 : Let's close this one and continue the tiny bit left here: https://github.com/gitpod-io/gitpod/issues/16481.
