### ISSUE TITLE
Epic: Prebuilds stability

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#10361]
### Summary

The goal of this epic is to focus on two things:
 1. fix the most glaring issues we currently have with prebuilds
 2. ensure quality beyond that by adding tests and metrics as we see fit

### Context

Historically the "prebuild experience" has been really shaky (cmp. #7812, for instance), mostly because:
 - it's a rather high-level feature that involves a lot of moving parts to :gear:  into each other
 - it has close to zero test coverage
 - it's opaque to users as to a) why and b) if a prebuild is executed after they "triggered" it: some of the perceived instability is actually working as intended but a) we're doing a bad job at explaining it and b), it's not observable for users (not exactly this epic, but touches parts of [this one](https://github.com/gitpod-io/gitpod/issues/9292))
 - we do not have proper metrics + alerts setup (SLI anyone)
 
As one of our quarterly goals is to improve perceived reliability, and we're driving usage-based pricing now, it feels like the right time to step up our game in this area. :muscle: 

We already have two other related epics that have a certain overlap:
 - https://github.com/gitpod-io/gitpod/issues/9292
 - https://github.com/gitpod-io/gitpod/issues/9291
 
We might tackle those as well if there's time. But we start out with the issues listed here, and and work our way towards those. Also, I expect that the individual issues are a) outdated and b) have overlap themselves, so we'll have to draw and move the line as we go.

### Value

- we fix some immediate issues that plague our customers
- we ensure those do not happen again, or are detected earlier when they happen again next time

### Acceptance Criteria

 - all issues referenced in this epic are done :heavy_check_mark: 
 - we have metrics from which we can derive a "success rate" (bonus points for having an SLI dashboard)

### Measurement

The user perceived reliability increased.

#### Issues
 - [x] https://github.com/gitpod-io/gitpod/issues/8195 
 (@AlexTugarev https://github.com/gitpod-io/gitpod/pull/10357)
 (@AlexTugarev https://github.com/gitpod-io/gitpod/pull/10646)
 - [x] https://github.com/gitpod-io/gitpod/issues/9395 
 (@geropl )
 - [x] https://github.com/gitpod-io/gitpod/issues/10383
 (@laushinka )
 - [x] https://github.com/gitpod-io/gitpod/issues/10024
 (@laushinka and @jankeromnes – https://github.com/gitpod-io/gitpod/pull/10352)
 - [x] https://github.com/gitpod-io/gitpod/issues/4879
 - [x] https://github.com/gitpod-io/gitpod/issues/8324
 - [x] https://github.com/gitpod-io/gitpod/issues/8684
 - [x] https://github.com/gitpod-io/gitpod/issues/6391
 - [x] https://github.com/gitpod-io/gitpod/issues/5908
 - [x] https://github.com/gitpod-io/gitpod/issues/8596
 - [x] https://github.com/gitpod-io/gitpod/issues/9132

#### deferring 
 - https://github.com/gitpod-io/gitpod/issues/9170
 - https://github.com/gitpod-io/gitpod/issues/10341 (JL)
 - https://github.com/gitpod-io/gitpod/issues/8452 (JL)

#### Observability/Metrics
 - https://github.com/gitpod-io/gitpod/issues/7938
 - https://github.com/gitpod-io/gitpod/issues/9292

**Comment by lucasvaltl** [comment]
👋 Other prebuild related issues that should also be included imo: https://github.com/gitpod-io/gitpod/issues/8942 and https://github.com/gitpod-io/gitpod/issues/10024

**Comment by AlexTugarev** [comment]
Also, https://github.com/gitpod-io/gitpod/issues/10024 might not be a bug, at least not a functional one.

**Comment by jldec** [comment]
I put a comment into #10024 pointing to the relavant docs issue (assuming it's just a case of missing `init` task.)

**Comment by jldec** [comment]
@AlexTugarev, @geropl, I also added #10341 
and #8452 after discussing with @laushinka 
Both of these are important for debugging and support.

**Comment by geropl** [comment]
@jldec I left those out intentionally. But let's see if we find time to have a look. :upside_down_face: 

> @geropl, w.r.t. acceptance criteria, let's set a limit or define when to freeze this, otherwise this isn't valid.
:100: 

Please, do not add any more issues! :snowflake:

**Comment by axonasif** [comment]
Not sure if it's appropriate to put it here but hoping it is 😄
A user reported repeated `SYSTEM ERROR` for prebuilds.
IDs:
```
1. 4084cff8-5a8a-4505-a87d-88ce26d28023
2. d0960544-7e89-48de-9f3e-e5e6127767d3
```
Ref: https://discord.com/channels/816244985187008514/816246578594840586/982343828105211934

**Comment by woss** [comment]
> Not sure if it's appropriate to put it here but hoping it is 😄 A user reported repeated `SYSTEM ERROR` for prebuilds. IDs:
> 
> ```
> 1. 4084cff8-5a8a-4505-a87d-88ce26d28023
> 2. d0960544-7e89-48de-9f3e-e5e6127767d3
> ```
> 
> Ref: https://discord.com/channels/816244985187008514/816246578594840586/982343828105211934

That was me.  I checked my files and realized that the path for the image inside the gitpod.yml was not correct.  When corrected the manual rebuild started and finished successfully.

I hope this will help you in building even better product!!

**Comment by geropl** [comment]
Closing as all boxes are ticked :heavy_check_mark: :upside_down_face:
