### ISSUE TITLE
Epic: Improve Self-Hosted Day 2 Documentation

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10464]
### Summary

Regroup our docs and add content to improve on day 2 documentation

### Context

This epic aims to improve on #9073. 

In order to stay focused and on point within our self-hosted documentation, we want to regroup different pages according to the type of documentation they are. This is in line with current best practices. 

See internal [RFC](https://www.notion.so/gitpod/Proposal-Day-2-Self-Hosted-Docs-7708eea39c5e4a1fb05b04ccd99aa797) for more details

### Value

- Makes documentation clearer and more direct. We are not trying to pull a certain piece of documentation into several directions at once. 
- Facilitates docs writing because it is more clear what to write, how to write, and where to write what. Each type of documentation has only one job. 

### Acceptance Criteria
- [x] #10465 (requires https://github.com/gitpod-io/website/issues/1547)
- [x] #10515
- [x] #10516
- [ ] #11137
- [x] https://github.com/gitpod-io/gitpod/issues/11581
- [x] https://github.com/gitpod-io/gitpod/issues/10126
- [ ] Gitpod and Certificates (Concepts & Background section)
- [x] https://github.com/gitpod-io/gitpod/issues/11521
- [ ] Gitpod and Persistence: what data is stored where and how (Concepts & Background section)
- [ ] How to minimize workspace startup times (see internal [thread](https://gitpod.slack.com/archives/C01KPEPNBD0/p1656589246279589?thread_ts=1656586552.674479&cid=C01KPEPNBD0))
- [ ] How to configure Gitpod guide  (Operational Guides Section)
- [ ] How to scale Gitpod guide (Operational Guides Section)
- [ ] How to audit Gitpod  (Operational Guides Section) (requires https://github.com/gitpod-io/gitpod/issues/10560)

### Measurement

- Actively solicited feedback on docs

### Persona(s)

Self-hosted administrators - users that are responsible for setting up a self-hosted instance and operating it.

**Comment by lucasvaltl** [comment]
Moving this back into backlog as we have done considerable work here but won't be focusing on this right now.

**Comment by Siddhant-K-code** [comment]
@lucasvaltl Can we close this issue now _(as self-hosted is deprecated)_?

**Comment by lucasvaltl** [comment]
Yes - thanks for the ping!
