### ISSUE TITLE
Epic: Proof of Value Reference Architecture 

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10622]
### Summary

Create a specific reference architecture for a PoC phase of the customer life cycle. Aimed at balancing ease-of-set-up with enough scale to prove Gitpod's value in a team setting. 

### Context

We are working on a reference architecture for prod settings. This reference archtiecture is aimed at creating a scalable, reliable way to operate Gitpod in a production setting. For customers only wanting to try out Gitpod in a PoC phase (i.e. they have already tried the #9075 locally and now want to test with their team), this prod Reference Architecture is too cumbersome to set up - and there is no need to create such a reliable set up in this phase yet. 

Important: This is not a self-hosted team project, but a Gitpod project. All teams need to give their input, the self-hosted team may just be coordinating.

### Value

- Speed up the PoC phase of the sales pipeline
- Give the community a easy-to-set-up way of creating a Gitpod installation that should work for a lot of use cases, but should not be used in prod

### Acceptance Criteria

- Detailed documentation of the reference architecture, and the reasoning for the infrastructure decisions made. This also includes cost estimates.
- A terraform script that creates the reference architecture documented. This script can be used by users at their own discretion (i.e. it is not officially supported), and will be used to run internal automated tests see #7316)

### Measurement

- Qualitative feedback on reference artchitecture from users that have set it up
- Feedback from Sales Engineering who have accompanied customers in PoC phases that used it
- Community feedback

### Issues
- [x] https://github.com/gitpod-io/gitpod/issues/11225
- [x] https://github.com/gitpod-io/gitpod/issues/11226
- [x] https://github.com/gitpod-io/gitpod/issues/12001
- [ ] https://github.com/gitpod-io/gitpod/issues/12517
