### ISSUE TITLE
Epic: GPU Support - GA

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#10650]
### Summary

We want to fully support GPUs to enable different workloads, such as data science, particularly on self-hosted installations. 

Open questions:

- [ ] Would we be able to dynamically assign GPUs to workspaces?
- [ ] Would we be able to support all types of GPUs or would need to select a subset? What subset?
- [ ] Are we able to confidently release GPU support for self-hosted without launching it also on SaaS?

Related request: https://github.com/gitpod-io/customers/issues/24

### Context

.

### Value

.

### Acceptance Criteria

.

### Measurement

.

**Comment by sheffier** [comment]
Really expecting to try GPU support! please ping me as soon as it can be tested

**Comment by singhsidhukuldeep** [comment]
Can't wait to try GPUs. Please update as soon as we can try 😃

**Comment by KangOxford** [comment]
Please ADD GPU support!!! I will pay the bill.

**Comment by julien-blanchon** [comment]
Any news on this ?
