### ISSUE TITLE
Epic: Unattended Deployments

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#10722]
### Summary

Team WebApp has recently switched to [automatic deployments](https://www.notion.so/gitpod/How-we-deploy-9455c1f51ca74f29855c354c3f03c6c8#a739a536abe9441dbafcbb4e2018276f).
The [next step](https://www.notion.so/gitpod/How-we-deploy-9455c1f51ca74f29855c354c3f03c6c8#1d6966c1f1d74d11a73d050142815b8d) is to ensure we can do those deployments :100: unattended.

### Context

One of Prod.Eng. G&Rs is to improve Development Velocity. [The vision](https://www.notion.so/gitpod/How-we-deploy-9455c1f51ca74f29855c354c3f03c6c8#431779b679a8416eba8068e2ad532f20) for WebApp deployments is to make them completely automatic, unattended and instant.

Compare [the roadmap](https://www.notion.so/gitpod/How-we-deploy-9455c1f51ca74f29855c354c3f03c6c8#fa7f69b2378546118da9f9797650b44f) for more context.

### Value

 - waste less dev cycles on attended deployments
 - increase dev velocity
 - decrease reaction time
 - increase developer happiness because time between effort and feedback is much shorter
 - ... 

### Acceptance Criteria

 - [x] (at least) all current [manual checks](https://www.notion.so/gitpod/WebApp-Deployment-Log-f50641b2af7846fa8cece3be3de72ec7) are converted into alerts (tracked in https://github.com/gitpod-io/ops/issues/2873)
   - [x] https://github.com/gitpod-io/gitpod/pull/12514 (and https://github.com/gitpod-io/gitpod/pull/12588 with fixes)
     - [x] API error rate
     - [x] websocket connection rate
     - [x] services health (running without restarts?)
     - [x] services RAM/CPU usage trends
   - [x] log error rate https://github.com/gitpod-io/ops/pull/4269
   - [x] DB usages stays within limits https://github.com/gitpod-io/ops/pull/4258
 - [x] the process and it's mechanisms is/are documented (incl. how-tos for rollback, etc.)
 - [x] communicated the current state and future plans with other teams

### Measurement

 - (at least) all current [manual checks](https://www.notion.so/gitpod/WebApp-Deployment-Log-f50641b2af7846fa8cece3be3de72ec7) are converted into alerts

### Out of scope

 - increasing the deployment cadence

### Complexities

 - ensuring that metrics&alerts are a) helpful right after deployment, but b) do not ring false-alarms during the deployment itself

**Comment by geropl** [comment]
PRs to implement alerts are done/in review.

Next steps:
 - test alerts in prod
 - write a piece in notion with links to all alerts

**Comment by geropl** [comment]
- [x] Alerts have been tested (and fixed)
 - [x] there is a [notion doc about our alerting setup](https://www.notion.so/gitpod/Alerts-b7296dcdcadc4fa8a7df2f234ae66303)
:heavy_check_mark:
