### ISSUE TITLE
Epic: Private beta of initial public APIs

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10798]
This epic is for the exposure of the initial API's in our public documentation, following the completion of: 

- https://github.com/gitpod-io/gitpod/issues/7900 

**Remaining items**
- [ ] https://github.com/gitpod-io/website/issues/3112
- [x] https://github.com/gitpod-io/website/issues/3174
- [x] https://github.com/gitpod-io/website/issues/3172
- [ ] https://github.com/gitpod-io/website/issues/3173
- [ ] Introduce mechanism to opt-in to private beta

**Completed actions:** 
- [x] https://github.com/gitpod-io/website/issues/2911
- [x] Documenting Go SDK
- [x] Adding an API doc page to [references](https://www.gitpod.io/docs/references)
- [x] Documenting authentication approach (https://www.gitpod.io/docs/configure/user-settings/access-tokens)
- [x] Some context for users on what the API is, why we have it, what you can do with it, etc. 

**Out of scope:** 
- Documentation tools, format (e.g. swagger, open api, etc)

Depends on:
- https://github.com/gitpod-io/gitpod/issues/9757

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/11335

**Comment by loujaybee** [comment]
We are currently running the private beta.

**Comment by Siddhant-K-code** [comment]
> We are currently running the private beta.

How can a user can apply for the access? Contact Support form?

**Comment by loujaybee** [comment]
I'm going to close this issue now, @Siddhant-K-code we'll publish a public form in future for opt-in. For now, we'll reach out to individual users or customers to join the private beta.
