### ISSUE TITLE
Update all guides/preflight checks to check minimum Kubernetes version of 1.22

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#10959]
### Bug description

Officially, we support the last three versions of Kubernetes - as of today, the latest Kubernetes release is 1.24, which means that we should update our documentation/guides to use `>=1.22`

Places to check include:

- [ ] [public docs](https://www.gitpod.io/docs/self-hosted/latest/cluster-set-up)
- [ ] Guides - AWS, Azure, GCP
- [ ] KOTS preflight checks
- [ ] Installer cluster validation

### Steps to reproduce

n/a

### Anything else?

We should also establish a way of automating this where possible - even if it's the automation of a new ticket when a new version of [Kubernetes is released](https://kubernetes.io/releases/)

See also #6176
