### ISSUE TITLE
UI/UX improvements to usage telemetry page

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#10951]
We've received feedback about the overall structure, voice, and layout of the self-hosted telemetry page (thanks @gtsiolis!) that'll communicate information more effectively and improve the overall user experience. We'd like to improve the following areas:

- [ ] Correlate `Send Service Ping` checkbox with `Send Customer ID` checkbox; unchecking the service ping setting should disable/grey out the send customer ID option.
- [ ] Changing telemetry settings updates the telemetry preview (at present a page refresh is required)
- [ ] Change telemetry preview in response to disabling telemetry (preview should be greyed out, indicating that it won't be sent)
- [ ] Page layout improvements: group link to privacy policy with section description, change heading for telemetry preview (to indicate that it's part of the `Usage Statistics` section
- [ ] Clarify wording telemetry usage, improve tone of messaging to communicate intent more effectively

**Comment by gtsiolis** [comment]
Thanks for opening this, @adrienthebo! Cross-linking also [relevant discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1656331557761999) (internal).
