### ISSUE TITLE
Move blocked repository configuration into the database and build admin UI to work with it

### ISSUE THREAD

**Issue by andrew-farries** [gitpod-io/gitpod#11030]
Gitpod allows for repositories to be blocked, so that workspaces can't be started with those contexts. Support for blocking repositories was added to `components/server` in #9762 where the implementation used server config to provide the list of blocked repos.

We'd like to move blocked repository configuration out of server config and into the application database for a few reasons:
* We can more easily build blocked repo configuration into the Gitpod admin UI (and/or `gpctl`?)
* Having this configurable in the admin UI makes on-call easier than having to change `server` config at runtime with `kubectl`.
* The ability to block repositories may be useful for self hosted users.

## Description

We don't need to use a feature flag for this; we can support blocked repository config in the database and in server config at the same time. We can then move the repositories that reside in server config into the database and delete the former.

## Tasks

* [ ] Add new table to the database to hold blocked repository data.
* [ ] Read new table at workspace startup and prevent workspace start/block user as necessary.
* [ ] Add CRUD API surface to work with blocked repositories.
* [ ] Build CRUD admin UI to work with blocked repositories.
* [ ] Move existing blocked repositories from server config into database.
* [ ] Remove server configuration of blocked repositories and code that reads it.

**Comment by geropl** [comment]
@andrew-farries Do you mind if I take over here during my on-call week? :question:

**Comment by andrew-farries** [comment]
Please do 😄
