### ISSUE TITLE
Other self-hosted docs improvements

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#11137]
This is a placeholder ticket - these are follow up action items resulting from https://github.com/gitpod-io/website/pull/2337
- [ ]  Restructure repo: We should restructure the self-hosted docs in the repo to have one folder per subsection. This will break a lot of links though - I don't know how to best do this from an execution perspective.
- [ ]  UX improvements: This change makes the docs look empty. We should have the sub-menus default to open for the self-hosted section to facilitate jumping between them and facilitate discovery (at least until we have too many menu items that it becomes untenable). Should probably better indicate in the UI which menu items are a subsection to facilitate discovery of docs pages.
- [ ]  Rename Self-Hosted Section into Administer Gitpod
- [x]  Rename current getting started guide into installation guide. Subsequently rename local preview into getting started. Move getting started (formerly local preview) to the top Self-Hosted hierarchy level
- [ ]  Should move TLS guide one level up the hierarchy (under installation Guides)
- [x]  Split releases into release policy and upgrade guides (maybe move the latter to the operational guides section?
- [ ]  Need to improve the trouble shooting section with info on how to reach out to support / community.
- [x]  Add background section for (future) topics like Architecture Basics, Disaster Recovery, Update strategies, and TLS certificates basics - once we have the first one of these.
- [ ]  Split How to update Gitpod docs into two - update guide and update strategies. Move update strategies into the background subsection.
- [x]  Move reference architectures up one level once we have them in a V1 state and can remove the cluster set up guides
