### ISSUE TITLE
GitPod: Wipe the history of commands

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1121]
if i press `arrow-up` on gitpod it suggests bunch of seemingly backend commands alike:

```console
gitpod /workspace/emkdir-rustlang $ exec /theia/node/bin/gitpod-node ./src-gen/backend/main.js
```

Recommends wiping the history prior to letting end-user to the environment

**Comment by JesterOrNot** [comment]
Yea that is part of the gitpod layer logic @svenefftinge can you take a look at this?

**Comment by jankeromnes** [comment]
Thanks for the feedback!

In general I think there are several things we should improve with Gitpod's Terminal history. Ideally, it should:
- [x] display prebuild commands and logs when your workspace starts from a [prebuild](https://www.gitpod.io/docs/46_prebuilds/) (already the case, but we shouldn't break it)
- [ ] allow users to use `up-arrow` and `ctrl-shift-R` to find commands from previous sessions, e.g. by saving the Terminal's history inside the `/workspace` directory (this used to work in c9.io and was really handy e.g. to resume servers with long cryptic commands)
- [ ] not include "internal" Gitpod commands in that history (e.g. commands from your `.gitpod.yml` are ok, but not Theia commands as described above)
- [ ] not show the `history -r $HISTFILE` command in all Terminals (it's an "internal" Gitpod command, and it got several users confused and/or wondering whether something was broken)
