### ISSUE TITLE
Epic: PVC (Persistent Volume Claims) on Self-Hosted

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#11476]
### Summary

To ensure workspace data durability we are moving from backups to object storage to using persistent volume claims (PVCs) and snapshots. We have started with SaaS (https://github.com/gitpod-io/gitpod/issues/7901) and will then focus on self-hosted with this epic.

### Value

Bringing the reduced chance of data loss, and associated system trust, to self-hosted customers.

### Acceptance Criteria

* Self-hosted customers can benefit from the same durability guarantees offered on SaaS.
* There's a safe upgradability path.
* Installer/KOTS
  - [ ] https://github.com/gitpod-io/gitpod/issues/10613
  - [ ] https://github.com/gitpod-io/gitpod/issues/10614
* Tests
  - [ ] https://github.com/gitpod-io/gitpod/issues/10211
  - [ ] https://github.com/gitpod-io/gitpod/issues/10212

### Persona(s)

Self-hosted admins and users.

### Complexities

- Support of major clouds and on-prem setups will require extensive research and testing

**Comment by mrzarquon** [comment]
Cross Zone support will need to be tested. GKE has support for [region wide persistence](https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#regional_persistent_disks), but EKS's GP2/ebs type doesn't.

In EKS, once a workspace is launched, it is tied to the availability zone it's PVC was created in. Which can be a problem if in the future that zone has 0 workspace nodes in it, and a user wants to launch it. Either the launch will fail or be held until EKS can scale a node to that zone for them.

Whatever outcome of testing is, it will likely impact our reference architectures, as it could be we go from one multi-zone workspace nodegroup to a workspace nodegroup per zone. And if one AVZ goes offline or can't provision into that zone for some reason (other capacity issues, etc) workspaces with pvc in that zone in that zone can't relaunch until it comes back.

**Comment by jenting** [comment]
I think we don need to work on this issue anymore. @atduarte

**Comment by kylos101** [comment]
Closing as it's for self-hosted.
