### ISSUE TITLE
Epic: IDE integration testing against Self-Hosted

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#11862]
### Summary

As a result of https://github.com/gitpod-io/gitpod/issues/8017 IDE is capable to run nightly integration tests to smoke test VS Code Browser and JB integrations for SaaS. We need to complete it with support of VS Code Desktop and SSH Gateway, as well as to test against Self-Hosted.

### Value

- QA of IDE clients against latest released Self-Hosted.
- QA of new Self-Hosted release against IDE changes.

### Acceptance Criteria

- [x] Integration tests runs nightly against main branch and latest released Self-Hosted installations.
- [ ] Integration tests failures and going from failed to successful reported to [ide-jobs slack channel](https://gitpod.slack.com/archives/C02F9LQU4DR).
- [x] At least one test is running for VS Code Desktop
- [x] At least one test is running for SSH Gateway, i.e. direct ssh

**Related issues:** 
- https://github.com/gitpod-io/gitpod/issues/14101
- https://github.com/gitpod-io/gitpod/issues/13661

**Comment by mustard-mh** [comment]
@nandajavarma what is the status of the integration test in SH, as they are working in IDE job channel stably these days.

Is this Epic still make sense? Any further plans?
