### ISSUE TITLE
Epic: Establish Workspace Success Rate (IDE)

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#11910]
### Context

IDE team should establish a workspace success rate according to  [internal RFC](https://www.notion.so/gitpod/Workspace-Success-Rate-ef464969f5f54b83b7df43828d1ec5a4#29aa3385045446a1b8b16101f229a68c)

### Value

Improve visibility in reliability issues for users trying access the workspace using different IDE interfaces.

### Acceptance Criteria

- [ ] All SLIs are defined and documented
- [ ] All SLOs are defined and overview available in one place
- [ ] All alerts on SLOs are created
- [ ] Grafana dashboards are available for IDE clients and proxies

#### Engineering
- [x] https://github.com/gitpod-io/gitpod/issues/11134
  - [ ] rate limiting
  - [ ] RED observability for grpc endpoint
  - [ ] reporting from non-js clients, i.e. golang and java

#### SLIs/SLOs

> Connections errors mean any error to IDE services from any protocol (http, web-socket, Gitpod API, IDE backends, etc) as a ratio per a client session or a throughput in proxies.

- [ ] Connection errors in a browser (supervisor-frontend/VS Code Browser)
  - [ ] [SLI definition](link)
  - [ ] [SLO overview](link)
  - [ ] [alert](link)
  - [ ] [dashboard](link)
- [ ] Connection errors in VS Code Desktop extension
  - [ ] [SLI definition](link)
  - [ ] [SLO overview](link)
  - [ ] [alert](link)
  - [ ] [dashboard](link)
- [ ] Connection errors in JB Gateway Gitpod Plugin
  - [ ] [SLI definition](link)
  - [ ] [SLO overview](link)
  - [ ] [alert](link)
  - [ ] [dashboard](link)
- [ ] Connection errors in ws-proxy
  - [ ] [SLI definition](link)
  - [ ] [SLO overview](link)
  - [ ] [alert](link)
  - [ ] [dashboard](link)
- [ ] Connection errors in IDE proxy
  - [ ] [SLI definition](link)
  - [ ] [SLO overview](link)
  - [ ] [alert](link)
  - [ ] [dashboard](link)
- [ ] Connection errors in OpenVSX proxy
  - [ ] [SLI definition](link)
  - [ ] [SLO overview](link)
  - [x] [alert](https://github.com/gitpod-io/gitpod/blob/bcade930fd0e20a90edefee4119d9b1cf579e1fc/operations/observability/mixins/IDE/rules/components/openvsx-proxy/alerts.libsonnet#L10)
  - [x] [dashboard](https://grafana.gitpod.io/d/HNOvmGpxgd/openvsx-proxy?orgId=1&refresh=5s)
- [ ] Connection errors in SSH Gateway
  - [ ] [SLI definition](link)
  - [ ] [SLO overview](link)
  - [ ] [alert](link)
  - [x] [dashboard](https://grafana.gitpod.io/d/3oan1Zr7k/ssh-gateway-overview?orgId=1&refresh=30s)

**Comment by andreafalzetti** [comment]
Closing as we now prefer improving observability  ad-hoc where we need it's important
