### ISSUE TITLE
Epic: Azure reference architectures

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#12000]
### Summary

Create azure versions of the reference architectures

### Context

In order to cater to azure users, we want to create azure versions of the reference architectures:
- PoV Reference Architecture
- Single Cluster reference archtiecture

All of the above should also have terraform modules that can create the infrastructure described via terraform

See also:
- [Epic: Self hosted reference architecture GA release](https://github.com/gitpod-io/gitpod/issues/12714)
- [Epic: Self hosted reference architecture beta release](https://github.com/gitpod-io/gitpod/issues/12709)
### Value

- Expands addressable market from reference architectures towards azure users

### Acceptance Criteria

- Azure based PoV Reference Architecture Guide + Terraform
- Azure based Single Cluster Reference Architecture  Guide + Terraform

### Measurement

- Guides and terraform can be successfully used by customers

### Issues

- [ ] https://github.com/gitpod-io/gitpod/issues/12001
- [ ] https://github.com/gitpod-io/gitpod/issues/12002
- [ ] https://github.com/gitpod-io/gitpod/issues/11534

**Comment by lucasvaltl** [comment]
Closing this as all issues here are now part of https://github.com/gitpod-io/gitpod/issues/12709
