### ISSUE TITLE
Automatically generate a community licence per user

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#12068]
As of today, we have a method of recording the information of users prior to giving them a licence. However, this licence is the same for all users.

We should add the ability to generate a new license for each user who requests a license via this page. This can be achieved either with two API calls ([create customer](https://replicated-vendor-api.readme.io/v3/reference/createcustomer-1), [download license](https://replicated-vendor-api.readme.io/v3/reference/downloadlicenses)) or with two calls to the Replicated CLI

It may be desirable to allow customers to select their channel (`stable`, `beta`, `unstable`). As a 🛹, we could hardcode to `stable`

There should be a naming convention that allows for the avoidance of collisions and to make it easy to see the customer in question when listing - a few random characters in the name should do the trick.

We should also deprecate the existing customer licences and put a timescale on when we delete them from Replicated. Suggest a minimum of 3 months for this, although the exact timescale is TBD.

- [ ] Decide on naming convention
- [ ] Configure a Zapier integration
- [ ] Set up email delivery (may not be required with Zapier)
- [ ] Deprecate existing licences and decide upon how long we maintain these
- [ ] Document how to upgrade from the old common licences to the new individual licences
- [ ] Delete old common licences from Replicated Vendor portal and our repo

### Benefits:
- Allows us to upgrade a user to paid plan
- Allows users to directly send their support bundles
- We get some high level info on their installation (e.g. cloud platform used)

**Comment by corneliusludmann** [comment]
> We should also deprecate the existing customer licences

It seems that I don't get this. What licenses do we want to deprecate and why? Do you mean the common (non-personalized) licenses?

---

> **Benefits**
> - Allows us to upgrade a user to paid plan

… without that the user has to change their license, right? With the license change feature, that works today already.

> - We get some high level info on their installation (e.g. cloud platform used)

We get this from the telemetry data already, don't we?

---

For the record, possible **drawbacks**:
- Over time, the vendor portal gets pretty messy with hundreds of licenses aka “customers”. Most of them will probably not be in use. Tidying up them seems to be pretty hard. The real customers are buried under tons of community licenses.
- This gets even worse when our form is flooded with spam.

**Comment by MrSimonEmms** [comment]
> It seems that I don't get this. What licenses do we want to deprecate and why? Do you mean the common (non-personalized) licenses?

Yes. I don't see much benefit to having a common licence. I don't necessarily object to this not being done.

>     * Over time, the vendor portal gets pretty messy with hundreds of licenses aka “customers”. Most of them will probably not be in use. Tidying up them seems to be pretty hard. The real customers are buried under tons of community licenses.
> 
>     * This gets even worse when our form is flooded with spam.

Yes, 💯 - this is the cost of having the additional visibility.
