### ISSUE TITLE
[reference architecture] Investigate using tigera-operator instead of static calico manifests

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#12492]
## Is your feature request related to a problem? Please describe

In February the Calico EKS documentation changed the [recommended installation path](https://github.com/projectcalico/calico/commit/e7e920c2de09eeb48671f24a3cb8c47547e68d24) to use the tigera-operator. Users running through the EKS reference architecture note that this pattern no longer follows the Tigera or AWS recommendations and may follow setup instructions that leave Calico in a state that doesn't satisfy Gitpod's requirements.

## Describe the behaviour you'd like

We need to answer the following questions and provide documentation backing up our decision to use either tigera-operator or calico-vxlan.yaml.

- [ ] What does the new tigera-operator do?
- [ ] How does it differ from running `kubectl apply -f https://projectcalico.docs.tigera.io/manifests/calico-vxlan.yaml`?
- [ ] Is tigera-operator supported?

**Comment by adrienthebo** [comment]
Tacking a comment onto this issue, we should also document [_why_ we're using Calico](https://github.com/gitpod-io/website/pull/2571/files#r954127345).

**Comment by Pothulapati** [comment]
From the docs, I can see the following:

>  What does the new tigera-operator do?

Calico is installed by an operator which manages the installation, upgrade, and general lifecycle of a Calico cluster. The operator is installed directly on the cluster as a Deployment, and is configured through one or more custom Kubernetes API resources.

Considering that both manifests & operator are supported (but operator is recommended), I would err on the side of starting wit the manifests and then figuring out a path to the operator if needed. This also matches with the current goal of getting upto speed with that existing guides. WDYT? Happy to use the operator if there are stronger reasons though.
