### ISSUE TITLE
Fixes to support PVC on loadgen and integration test

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#12560]
Today, we got workspaces running with loadgen via this branch, https://github.com/gitpod-io/gitpod/commits/fo/pvc-chown. However, that left us with some questions and changes to make:

- [x] ~Why was SupervisorRef added?
https://github.com/gitpod-io/gitpod/compare/fo/pvc-chown#diff-67b4c7f3957772e87beb608fc54eb2bdc7959210d20c2ceb8dcd08f06df0801aR71~
- [x] ~Remove sleep
https://github.com/gitpod-io/gitpod/compare/fo/pvc-chown#diff-c9626ddd8d63f48f858c8e81807c14008f5c4199bd41ba80a2981401111356f0R119~
- [x] ~WorkspaceLocation is required for PVC, and shouldn't be hard coded (it varies with repo)
https://github.com/gitpod-io/gitpod/compare/fo/pvc-chown#diff-67b4c7f3957772e87beb608fc54eb2bdc7959210d20c2ceb8dcd08f06df0801aR81~
- [x] ~Authentication was needed, with PVC, not sure why, it shouldn't be needed
https://github.com/gitpod-io/gitpod/compare/fo/pvc-chown#diff-33e706bada7e46c8ade905ca32216a5073740c91cff12b28f2dc618ed81a8c89R200-R202~
- [ ] CheckoutLocation is required for PVC, and shouldn't be empty (it varies with repo)
https://github.com/gitpod-io/gitpod/compare/fo/pvc-chown#diff-33e706bada7e46c8ade905ca32216a5073740c91cff12b28f2dc618ed81a8c89R195
- [ ] The PVC should support content-service `EmptyInitializer`, because some integration tests use the EmptyInitializer to open the workspace without git pulling the repo. This makes the testing faster.

**Comment by kylos101** [comment]
@jenting are you sure 1 (SupervisorRef) is still needed? I am skeptical of it. Also, I believe 3 (WorkspaceLocation) and 4 (CheckoutLocation) were resolved in #12567.

**Comment by kylos101** [comment]
Also, how does this related to `integration test`? I believe it would be better if loadgen and integration test changes were tracked in separate issues.

**Comment by jenting** [comment]
Remove the `SupervisorRef`.

I think the loadgen test and integration test do not require the parameters `WorkspaceLocation` and `CheckoutLocation` in the start workspace request. These two parameters should be _optional_.

**Comment by kylos101** [comment]
> These two parameters should be optional.
Why?

In other words, what is the side effect if we do not do this issue?

**Comment by jenting** [comment]
The startWorkspace request, field `workspaceLocation` is a required field.
ref to https://github.com/gitpod-io/gitpod/blob/27dfab97902614858cf95bdd6ef082d0321e0b19/components/ws-manager/pkg/manager/manager.go#L587

**Comment by jenting** [comment]
Without `checkoutLocation` with PVC, the error message shown
```console
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"cannot initialize workspace:\n    github.com/gitpod-io/gitpod/content-service/pkg/initializer.InitializeWorkspace\n        github.com/gitpod-io/gitpod/content-service@v0.0.0-00010101000000-000000000000/pkg/initializer/initializer.go:439\n  - git chown -R -L gitpod /workspace failed (exit status 1): chown: changing ownership of '/workspace': Operation not permitted\n","file":"supervisor.go:1340","func":"func1","level":"fatal","message":"content initialization failed","serviceContext":{"service":"supervisor","version":"commit-6e8efd1aee02a9c13db6c03f886f39ceee178ac1"},"severity":"CRITICAL","time":"2022-09-29T08:20:14Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"rpc error: code = Canceled desc = context canceled","file":"rings.go:1083","func":"WorkspaceInfo","level":"error","message":"could not get workspace info","serviceContext":{"service":"workspacekit","version":"commit-6e8efd1aee02a9c13db6c03f886f39ceee178ac1"},"severity":"ERROR","time":"2022-09-29T08:20:14Z"}
```
