### ISSUE TITLE
[UBP for individuals] Configure usage-based billing in personal settings

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12685]
This lives in the Billing page at https://gitpod.io/billing in your personal settings, where we already show your team billing account if active.

![Image](https://user-images.githubusercontent.com/849592/188619141-9a3b0040-6d10-4696-8ce0-bd97c06e2a8c.png)

---

A new section on the same page should show personal UBP billing as inactive when no payment method has been configured.

![Image](https://user-images.githubusercontent.com/849592/188620711-89df76ff-0a0a-4032-ab34-d69cdb076d10.png)

---

After configuring a payment mething the section  shows the following, similar to team billing.

![Image](https://user-images.githubusercontent.com/849592/188620733-11eee880-3427-4297-9191-e3a8f4f3ccdb.png)

### Server
- [x] Add new methods to `server` to support individual user signup: 
  - [x] Add `createOrUpdateStripeCustomerForUser` method (#12753)
  - [x] Add `findStripeSubscriptionId` (https://github.com/gitpod-io/gitpod/pull/12876)
  - [x] Add `getStripePortalUrl` (https://github.com/gitpod-io/gitpod/pull/12864)
  - [x] Add `(get|set)UsageLimit(attributionId)` (https://github.com/gitpod-io/gitpod/pull/12767)
  - [x] Add `subscribeUserToStripe` (https://github.com/gitpod-io/gitpod/pull/12887)
### UI
- [x] Extract components common to both team and individual user UBP configuration (#12732)
- [x] Add placeholder billing configuration UI to individual billing page (#12733)
- [x] Hook up placeholder billing UI on the user settings page with the new server methods. (https://github.com/gitpod-io/gitpod/pull/12942)
- [x] Remove team-specific Stripe APIs from `server`:
  - [x] `findStripeSubscriptionIdForTeam` (https://github.com/gitpod-io/gitpod/pull/12957)
    - [x] Need to remove one usage from `BillingAccountSelector` first (https://github.com/gitpod-io/gitpod/pull/12954)
  - [x] `subscribeTeamToStripe` (https://github.com/gitpod-io/gitpod/pull/12957)
  - [x] `getStripePortalUrlForTeam` (https://github.com/gitpod-io/gitpod/pull/12957)
  - [x] `getUsageLimitForTeam` (https://github.com/gitpod-io/gitpod/pull/12957)
  - [x] `setUsageLimitForTeam` (https://github.com/gitpod-io/gitpod/pull/12957)
### Other
- [ ] Make `getCostCenter` throw an error if no cost center exists. See [this comment](https://github.com/gitpod-io/gitpod/pull/12767#discussion_r968029349).
