### ISSUE TITLE
Epic: Reference architecture Beta release

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#12709]
### Summary

This epic tracks outstanding work for the beta release of the GKE and EKS reference architectures.

Follow-up GA epic: https://github.com/gitpod-io/gitpod/issues/12714

### Context

Feedback from end users deploying the reference architecture has identified potential pitfalls and areas of improvement. These issues are to be tracked in a single location so we have an agreed upon definition for a beta release of the EKS and GKE reference architectures.

### Value

See above. 

### Acceptance Criteria

The reference architectures should provide complete documentation for installing Gitpod onto GKE and EKS. The guides should follow current Gitpod SaaS best practices, distinguish between required procedures and settings vs general howtos, and should call out common pitfalls.

### Tasks

**General**

- [x] https://github.com/gitpod-io/website/pull/2652 (separate headless and regular workspace pools)
- [x] https://github.com/gitpod-io/website/issues/2888
- [ ] recommend a means to configure autoscaler node_labels by nodepool for EKS and Azure
- [x] #9661  
- [ ] #13830
- [x] https://github.com/gitpod-io/gitpod/issues/12782
- [ ] #13829
- [ ] Measure autoscaling behaviour - how long does it take to scale up and down across cloud providers? ([context](https://www.notion.so/gitpod/68624956f436474aaec0c112c37edc81#831507bfd67c4777b072b0890a7fa99e))
- [ ] Terraform configurations for the PoV reference Architecture

**EKS**

- [x] https://github.com/gitpod-io/gitpod/issues/12399
- [x] https://github.com/gitpod-io/gitpod/issues/12413
- [x] https://github.com/gitpod-io/website/pull/2571
- [x] https://github.com/gitpod-io/website/pull/2680
- [x] https://github.com/gitpod-io/gitpod/issues/12740
- [ ] https://github.com/gitpod-io/gitpod/issues/12973
- [x] https://github.com/gitpod-io/website/pull/2734
- [ ] https://github.com/gitpod-io/gitpod/issues/12953
- [ ] https://github.com/gitpod-io/gitpod/issues/13482

**GKE**

- [x] https://github.com/gitpod-io/gitpod/issues/12403

**Azure:**
- [ ] https://github.com/gitpod-io/gitpod/issues/11534
- [x] https://github.com/gitpod-io/gitpod/issues/12002
- [ ] https://github.com/gitpod-io/gitpod/issues/12001 (should)

**Comment by kylos101** [comment]
👋 @lucasvaltl, when you and @atduarte are back, it would be good to brainstorm a section for `The guides should follow current Gitpod SaaS best practices`. I'm certain @aledbf can help add related detail, but, it would be good to understand your intent, so we have boundaries.

Also, I added https://github.com/gitpod-io/website/issues/2716 to the EKS section, based on my recent experience following the ref arch for EKS, and wanted to give you a heads up.
