### ISSUE TITLE
Epic: [Self-Hosted] reference architecture GA release

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#12714]
## Summary

This epic tracks outstanding work for the general availability release of the GKE and EKS reference architectures.

Preceding epic: https://github.com/gitpod-io/gitpod/issues/12709

## Acceptance criteria

This is a placeholder issue, acceptance criteria TBD

## Tasks

**General**

- [ ] #13287
- [x] #13833
- [x] #13834
- [x] #13832
- [ ]  https://github.com/gitpod-io/gitpod/issues/12400
- [x] https://github.com/gitpod-io/website/issues/2694
- [x] https://github.com/gitpod-io/gitpod/issues/11539
- [x] https://github.com/gitpod-io/gitpod/issues/12407
- [ ] https://github.com/gitpod-io/gitpod/issues/12492
- [x] https://github.com/gitpod-io/gitpod/issues/11449
- [ ] https://github.com/gitpod-io/gitpod/issues/12566
- [x] https://github.com/gitpod-io/gitpod/issues/12715
- [x] https://github.com/gitpod-io/gitpod/issues/13327
- [ ] https://github.com/gitpod-io/gitpod/issues/12782 (Should) 
- [ ] https://github.com/gitpod-io/gitpod/issues/10805 (should)

**GKE**

- [x] https://github.com/gitpod-io/gitpod/issues/12406

**EKS**

- [x] https://github.com/gitpod-io/gitpod/issues/12397
- [x] https://github.com/gitpod-io/gitpod/issues/12631
- [x] https://github.com/gitpod-io/gitpod/issues/12979

**AKS**:

- [x] https://github.com/gitpod-io/gitpod/issues/13139
