### ISSUE TITLE
Update the SaaS deployment process to use the refactored `config` commands

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#12847]
As part of the parent task, the Installer's configuration commands have updated. These will need to be incorporated into the SaaS process for building the YAML files for deployment to our clusters.

- [ ] The `init` command is now deprecated in favour of `config init` #12678 
- [ ] There are detection commands for the ShiftFS status and containerd location (this may not be needed) #12198 
- [ ] There is a new `config build-from-envvars` command to build the config parameters (this may not be needed) #12199

**Comment by mads-hartmann** [comment]
The `init` command isn't used as pat of SaaS deployments. We only use the `render` command - see [here](https://github.com/gitpod-io/ops/blob/main/charts/argocd/patches/configmap.yaml#L31) and [here](https://github.com/gitpod-io/ops/blob/main/scripts/installer/render-with-wrapper.sh#L53) ☺️ The config files are checked into git, e.g. [here](https://github.com/gitpod-io/ops/blob/main/deploy/production/meta-eu02/app/installer-config.yaml)
