### ISSUE TITLE
Create HTTP Proxy preview in Werft

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#13028]
Build an automation in Werft that allows for creation of an airgapped Gitpod infrastructure with an HTTP Proxy that allows traffic to connect to the public internet. It must use the airgapped configuration as a base to prove that the connections are going via the proxy server and not leaking directly to the public internet. Unlike with airgapped, this cluster should still be able to connect to the public internet - it will get all container images from there and will be able to connect to a public GitHub/GitLab instance.

There should be both a Werft command (eg, `/werft run proxy-preview`) and a checkbox added to all PRs. This will also add an additional preview box under the PR.

## Requirements

- [ ] All requirements as per the [airgapped automation](https://github.com/gitpod-io/gitpod/issues/13027)
- [ ] Configuration of the Kubernetes cluster to a [proxy server](https://cloud.google.com/architecture/creating-kubernetes-engine-private-clusters-with-net-proxies)
  - [ ] GKE is not actually the requirement here. If easier to achieve via [k3s](https://rancher.com/docs/rancher/v2.0-v2.4/en/installation/other-installation-methods/single-node-docker/proxy/), that would be acceptable
- [ ] A proxy server
  - [ ] [Squid](https://www.digitalocean.com/community/tutorials/how-to-set-up-squid-proxy-on-ubuntu-20-04) seems to be a fairly simple server to configure
  - [ ] Access should be password protected, so the URL will be `http://user:password@ip:3128`
  - [ ] There is no requirement for `HTTPS_PROXY` - if no `HTTPS_PROXY` configured, use of the `HTTP_PROXY` is acceptable
- [ ] The [HTTP Proxy](https://github.com/gitpod-io/gitpod/issues/10769) is currently provided to KOTS via `--http-proxy`, `--https-proxy` and `--no-proxy` flags. This data will need to be transferred securely (remember there will be a username/password in these values).
