### ISSUE TITLE
Epic: Implement free tier for individuals in usage-based billing

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#13301]
### Summary

Implement a free tier for individuals in usage-based billing.

### Context

https://www.notion.so/gitpod/UBP-Individual-Tier-343575c38d0e432588a38732cd7362b4 (internal)

### Value

- Translate the existing Chargebee-based free tier into our new usage-based billing with Stripe

- Continue providing an amazingly useful service for free to individuals, open source developers, early adopters and other tinkerers and Gitpod enthusiasts ❤️

### Acceptance Criteria

- The new Stripe/usage-based free tier should be functionally equivalent to the old Chargebee-based free tier

### Measurement

- 100% of new Gitpod users land in the new Stripe/usage-based free tier on sign-up, and none in the current Chargebee-based free tier

TODOs:

- [x] Create a new Stripe Price for individuals with a built-in free tier (using Stripe's Graduated Pricing)
- [x] #13307
- [x] #13302
- [x] #13389
- [x] Prevent individuals from changing their monthly usage limit until they upgrade with a credit card
- [x] For upgraded individuals, allow modifying the monthly usage limit (but with a minimum value corresponding to the base paid package)
- [x] #13405  
  Clearly show the free tier, usage, usage limit, and upgrade path in individual usage-based billing settings

**Comment by jankeromnes** [comment]
Closing this epic as done. 🎉 ✅
