### ISSUE TITLE
Epic: Dashboard communicates with Public API

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#13574]
### Summary

This epic focuses on removing technical blockers which prevent the dashboard (web application) to use the Public API to retrieve data.

This epic does not focus on implementing and migrating API calls that dashboard makes over to public api.

### Context

We want to give ourselves a stronger API interface which can be consumed by dashboard, but also external clients. The first step is to dog-food the API using our existing clients - dashboard.

To address the technical limitations, we need to tackle the following:
* Exposing endpoints on the Public API over HTTP1.1 - web clients cannot use HTTP2
* Generating & using clients in the dashboard to communicate with public api
* Laying the groundwork for experimental and stable APIs

### Value

Unblocking increase in traffic on Public API

### Acceptance Criteria

Dashboard webapp can communicate with Public API

## Tasks
- [x] Route HTTP 1.1 traffic from api.gitpod.io to public-api-server 
	- https://github.com/gitpod-io/gitpod/pull/13582
- [x] Refactor existing public-api protos into stable and experimental packages
	- https://github.com/gitpod-io/gitpod/pull/13579
- [x] Generate clients & interfaces for Connect.build for public API
	- https://github.com/gitpod-io/gitpod/pull/13550
- [x] Bind generated (unimplemented) Connect.build handler to Public API HTTP mux
   - https://github.com/gitpod-io/gitpod/pull/13595
- [x] Configure CORS for api.gitpod.io
	- https://github.com/gitpod-io/gitpod/pull/13743
- [x] Refactor WorkspaceService to implement connect.build handler
    - https://github.com/gitpod-io/gitpod/pull/13736
- [x] Ensure public-api has sufficient observability to show incoming requests
    - https://github.com/gitpod-io/gitpod/issues/13903
 - [x] Cache proxy connections to server
    - https://github.com/gitpod-io/gitpod/pull/13750
 - [x] #14114

**Comment by easyCZ** [comment]
This is now complete.
