### ISSUE TITLE
Epic: Improve UX of searches and lists in the admin dashboard

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13779]
- [ ] Perform a sensible search when opening for the first time
- [ ] Paginate search results
- [ ] Use reasonable defaults for ordering
- [ ] Provide an indication in the UI which attributes are being searched e.g. "Search for users by email, git ID, and name."
- [ ] Don't include deleted data in the results (or make that optional)
- [ ] Use URL parameters so that searches can be shared and bookmarked
- [ ] Remember the last search after navigating
- [ ] Searches should never table-scan the DB. e.g. the user view requires 7+ seconds for any search (and longer on first load). Instead of wildcard, use prefix matching with indexed columns.
