### ISSUE TITLE
Epic: Discontinue student plans for Gitpod and the GitHub marketplace integration

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14025]
The GitHub student plans and the Marketplace integrations are complex to maintain and support.
Gitpod caters to students with generous Free and Personal plans.

#### Phase 1 - disable new user signups and upgrades  
- [x] Share thinking with community
- [x] Remove student plan pricing from the website.
- [x] Disable new signups and upgrades of student plans via GitHub 
- [x] gitpod-io/website#3099
- [x] Disable new student plan signups through the dashboard
- [x] #15570

#### Phase 2 - migrate users with existing plans tied to GitHub student pack or marketplace
- [x] handled as part of https://github.com/gitpod-io/ops/issues/8319

Related to gitpod-io/gitpod#6673

For more details and references see [RFC](https://www.notion.so/RFC-End-GitHub-Student-Pack-and-GitHub-Marketplace-integrations-693cba37767e4c3c895d1420eaedb91c) (internal).

**Comment by jldec** [comment]
Example of incorrect Gitpod plan names in GitHub marketplace from [support](https://app.frontapp.com/open/cnv_k215tje) (internal) - user clicked on upgrade in Gitpod. The "Professional" plan in Github is out of date. This plan is now called "Unleashed" and has different features.

![github-marketplace](https://user-images.githubusercontent.com/849592/197044536-12e60281-6718-450f-b9e6-ca48e8e8a9a0.png)
 ![github-marketplace-2](https://user-images.githubusercontent.com/849592/197044527-1f83ff71-4e2f-4d96-a031-260542b81e1d.png)

**Comment by geropl** [comment]
Done, last bits superseeded by https://github.com/gitpod-io/ops/issues/8319
