### ISSUE TITLE
[JetBrains] Verify why logic to bypass consent modal fails sometimes

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#14099]
### Description

Installing third-party plugins in JetBrains IDEs via `.gitpod.yml` fail sometimes due to the consent modal.

Things to verify:
- [ ] We correctly handle removal of `alien_plugins.txt` (no false positive caused by `os.Remove` throwing `syscall.EOENT` when file does not exist)
- [ ] Check if consent is skipped for plugins installed via a custom registry [[1]](https://github.com/andreafalzetti/gitpod-jb-custom-registry)
- [ ] Verify logic at restart

- Related code: [[1]](https://github.com/gitpod-io/gitpod/blob/8e2d030f9c4a5f89435e8091964e094dd6694d36/components/ide/jetbrains/image/status/main.go#L542-L553)
- Relevant chats (internal): [[1]](https://gitpod.slack.com/archives/C02CBKZEVS8/p1666344252574189), [[2]](https://gitpod.slack.com/archives/C02BRJLGPGF/p1666345786980609)

**Comment by andreafalzetti** [comment]
This could be related or a duplicated of this ticket: https://github.com/gitpod-io/gitpod/issues/13770

**Comment by akosyakov** [comment]
@andreafalzetti I think it is not applicable after https://github.com/gitpod-io/gitpod/pull/14566 We don't match config folder anymore, but precompute it. Closing?

**Comment by andreafalzetti** [comment]
I am probably missing some context because I am not following what you said.. As far as I understand at the moment, the consent modal could still be an issue sometimes?

The issue were noticed in both prebuild situations or when using a custom registry.

Happy to close if these scenarios are not happening now
