### ISSUE TITLE
Epic: Personal Access Tokens

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#14280]
### Summary
To enable automated interaction with Gitpod, users need the ability to manage their Personal Access Tokens.

### Context
Personal Access Tokens are API tokens which act on behalf of the user. They can be used to automate workflows against Gitpod.

### Value
* Integration on API level
* Enables extensibility of Gitpod
* Complements our efforts to introduce the Public API

### Acceptance Criteria
The user is able to:
* Create Access Token
* Rotate an Access Token
* List Tokens
* Delete a Token

### Measurement
* We will measure proportion of traffic against Gitpod with API keys vs regular dashboard sessions

### RFC
* [internal RFC](https://www.notion.so/gitpod/Gitpod-Tokens-RFC-69b617426bd040e295a95c623b725218)

### User stories
1. As a user, I want to add a token with a name, an expiry date, and scopes, so that I can use it to authenticate
    Note: Properties [here](https://www.notion.so/Gitpod-Tokens-RFC-69b617426bd040e295a95c623b725218)
2. As a user, I want to see the token that I have just created.
3. As a user, I want to see the tokens that I have created, when it expires, and when it was used. 
     Note: without seeing the secret value
5. As a user, I want to delete a token so that I can revoke permissions
6. As a user, I want to regenerate a token (for any reason) and see the new token.
7. As a user, I want to update the scopes of an existing token.
8. As a user, I want to authenticate to Gitpod API using my existing token.

### Milestone plan
- 1 week of API implementation
- 1 week of UI implementation
- 1 week of validation
Note: UI and API implementation can be started independently

### Diagram
<img width="553" alt="Screenshot 2022-11-11 at 12 57 28" src="https://user-images.githubusercontent.com/8015191/201336625-2c140635-515f-45aa-bf0b-e541d9d2c4fc.png">

### Storage
Will be stored in a new table `d_b_personal_access_token`. 
Reasons why we are not using the existing `d_b_gitpod_token`:
- Does not fit the new usecase
- Allows simpler migration path in the future

(additional contexts[[1](https://gitpod.slack.com/archives/C02EN94AEPL/p1668069587803029)][[2](https://github.com/gitpod-io/gitpod/pull/1868)])

#### Schema
-- | field | type
-- | -- | --
primary key, idx | id | varchar
idx | user_id | varchar
idx | hash | varchar
  | name | varchar
  | description | text
  | scopes | text
  | expiration_time | timestamp
  | created_at | timestamp
idx | last_modified | timestamp
  | deleted | boolean

### Issues
- [x] #14465 
- [x] https://github.com/gitpod-io/gitpod/pull/14523
- [x] https://github.com/gitpod-io/gitpod/pull/14627
- [x] #14619
- [x] #14609
- [x] #14610
- [x] #14611
- [x] #14602
- [x] #14612
- [x] #14613
- [x] #14614
- [x] #14615
- [x] #14616
- [x] #14617
- [x] #14618
- [x] #14860
- [x] #14900
- [x] #14911
- [x] #14912
- [x] #14944
- [x] #14945
- [x] #14946
- [x] #14947
- [x] #14972
- [x] #15002
- [x] #15098
- [x] #15103
- [x] #15104
- [x] #15105

### Rollout
- [x] Behind a feature flag for specific users or percentage of users.
- [x] #14910
- [x] Include a link to the documentation

### Documentation
https://www.gitpod.io/docs/configure/user-settings/access-tokens

### Follow-up
Follow-up epic which tracks feedback, improvements and general direction towards a stable release is in
* https://github.com/gitpod-io/gitpod/issues/15100

**Comment by gtsiolis** [comment]
Adding this to the [product design board](https://github.com/orgs/gitpod-io/projects/29). 🎹 

Cross-linking [relevant discussion](https://gitpod.slack.com/archives/C0463A2KQUU/p1666880391797149) (internal):

> Regarding the [Gitpod Tokens: RFC](https://www.notion.so/Gitpod-Tokens-RFC-69b617426bd040e295a95c623b725218) (internal), we used to have a similar functionality in the dashboard before the redesign last year (see API Tokens section in [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1661947127582489)), which was not widely used and we decided to drop during the dashboard redesign.

> There’s already an issue with design specs for this section, named loosely Access Tokens, (see [#3399](https://github.com/gitpod-io/gitpod/issues/3399)) thought which we could use as a base for this iteration taking into account the decisions or needs described in the RFC once approved and updating the designs, copy, and structure.

**Comment by laushinka** [comment]
> > we used to have a similar functionality in the dashboard before the redesign last year
> 
> > There’s already an issue with design specs for this section, named loosely Access Tokens, (see [#3399](https://github.com/gitpod-io/gitpod/issues/3399)) thought which we could use as a base for this iteration

Thanks for the context, @gtsiolis! 
Looking at the past designs briefly we could use the same base. Some WIP to keep in mind:
- Creation will require more input than just name, but also description, scopes, expiration time. Depending on the length of scopes list, it might affect whether we use a modal on creation.
- List of tokens shows more details e.g. when it expires, maybe when it was last used.
- Each token can be deleted, regenerated, or (scopes) updated.

Will post updates in this epic.

**Comment by laushinka** [comment]
> the RFC once approved

@gtsiolis [RFC](https://www.notion.so/gitpod/Gitpod-Tokens-RFC-69b617426bd040e295a95c623b725218) is accepted 👍🏼

**Comment by gtsiolis** [comment]
Thanks for the heads-up, @laushinka!

Regarding the context in https://github.com/gitpod-io/gitpod/issues/14280#issuecomment-1308654514, I haven't read the RFC in-depth yet but the list of options listed there looks long. Should we consider breaking the list of features into smaller pieces as MVC [skateboards](https://www.notion.so/Ship-skateboards-f7f54cb1c69643e9ac42c9f2ddd9e46f) to avoid [scope creep](https://en.wikipedia.org/wiki/Scope_creep)?

Cc @easyCZ

**Comment by gtsiolis** [comment]
@easyCZ Perfect, sounds good! I'll dive into more designs for this features in the next few days.

**Comment by akosyakov** [comment]
@gtsiolis Is there a design available?

**Comment by gtsiolis** [comment]
@akosyakov I'm currently working on this. I'm planning to upload some early designs today. Any feedback or something that designs should take into account?

**Comment by akosyakov** [comment]
@gtsiolis nope it just we wanted to start to work on it. If we do some cross cutting slices it would be good to have some ideas about UI.

**Comment by gtsiolis** [comment]
Posting some early designs for the personal access tokens (PATs) flow, including 1️⃣ the empty state and 2️⃣ the new token modal. I’ll add later today, 3️⃣ the new token confirmation and 4️⃣ the listing of existing tokens. Cc @laushinka @easyCZ 

| 1️⃣ No tokens | 2️⃣ New token |
|-|-|
| <img width="1440" alt="Empty" src="https://user-images.githubusercontent.com/120486/203340048-e7d33a49-48b8-4f59-b073-5dd772ae5bfa.png"> | <img width="1440" alt="New" src="https://user-images.githubusercontent.com/120486/203340056-96d56379-15fc-49a3-9726-47e8cd0eeb35.png"> |

See [design specs](https://www.figma.com/file/1mvDLa69rEHo82Lf8YnZl4/Epic%3A-Personal-Access-Tokens-%2314280?node-id=19%3A195&t=K1DD2ho6Lu6Y9RrR-1).

**Comment by tdensmore** [comment]
Quick question about the "Permissions" checkbox: does this need to be checked for the PAT to work as expected? If not, what are the default permissions? I have seen these split into USER and ADMIN options for other products, but maybe that does not apply yet since we are still building out our public API set?

**Comment by gtsiolis** [comment]
Hey @tdensmore! Cross-posting from the [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1669129929009669?thread_ts=1669129212.853829&cid=C01KPEPQYE6) (internal) for visibility:

> @easyCZ: For the Token Create - the scopes:
> - Initially we should include a checkbox which says "Grant all my permissions to this PAT". This acts as a "grant all" special token and explicitly acknowledges that is what the token will be able to do
> - This allows us to then later introduce more fine-grained scopes in subsequent iterations

**Comment by gtsiolis** [comment]
Adding below more design specs for the token creation.

| Creating the first token | Refreshing the list |  Creating the second token |
|-|-|-|
| <img width="1440" alt="List" src="https://user-images.githubusercontent.com/120486/203419449-92828517-a033-48c4-91d9-bd28a2af9384.png"> | <img width="1440" alt="List-2" src="https://user-images.githubusercontent.com/120486/203419542-67bbdb73-c6ab-4910-8828-ccce95c7373c.png"> | <img width="1440" alt="List-1" src="https://user-images.githubusercontent.com/120486/203419490-4b4e1dd3-44ea-417d-b52c-8755be25363b.png"> |

| More actions on a token | Editing a token |
|-|-|
| <img width="1440" alt="List-3" src="https://user-images.githubusercontent.com/120486/203419652-aed913e1-f553-41ef-aadf-c347b45be785.png"> | <img width="1440" alt="List-4" src="https://user-images.githubusercontent.com/120486/203419731-fe01c133-869e-46cd-862c-3ff637883a6d.png"> |


For the token creation, an alternative approach could be to use a modal for nudging users to copy the token:

| Creating the token (Alternative) |
|-|
| <img width="1440" alt="New" src="https://user-images.githubusercontent.com/120486/203420089-9412e751-08ba-478e-8736-0fe8568f666c.png"> |

**Comment by jimmybrancaccio** [comment]
I wonder if it's worth using a yellow alert component for the "nudge" text. I like the alternative with the modal too - but perhaps remove the footer of the model since there's already a copy button/function in the text field.

Look great though, really nice job!

**Comment by gtsiolis** [comment]
Thanks for the feedback @jimmybrancaccio!

I'd avoid relying on the alert component for everything we add as this could be overwhelming for users. We're already using lost of alerts for other cases like local preview, usage limit, etc.

For the latest designs, we're leaning towards a non-modal approach as it would scale better with more permissions that we'd like to add over time, see [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1669212516443589) (internal).

**Comment by gtsiolis** [comment]
@easyCZ Shall we close this in favor of #15100? Cc @jldec

**Comment by easyCZ** [comment]
@gtsiolis Currently this epic is in a validation phase. I'd like to keep it open until we've concluded that phase, and have run it for some time.

**Comment by gtsiolis** [comment]
OK, @easyCZ! 🤝

**Comment by atduarte** [comment]
@easyCZ can we close this?
