### ISSUE TITLE
Epic: JetBrains happy-path is covered by integration tests

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#14297]
### Summary

We want to provide a stable and reliable experience, therefore lots of manual testing goes into each release or IDE image update. The goal is to cover at least the happy path of a user using any JetBrains IDE with Gitpod, to reduce manual testing and speed-up the release process.

**Related issues:**
- [ ] SPIKE [JetBrains/intellij-ui-test-robot](https://github.com/JetBrains/intellij-ui-test-robot) to understand if it can be used to test the end-to-end experience (JB Gateway -> IDE -> UI customizations)
- [x] https://github.com/gitpod-io/gitpod/issues/13661
- [x] https://github.com/gitpod-io/gitpod/issues/14101

**Comment by andreafalzetti** [comment]
@loujaybee this Epic is specific for JetBrains. We have sub-tasks to achieve the "happy path" being covered by automated tests.

#11862 is more generic. At the moment there is no overlap
