### ISSUE TITLE
Epic: Deprecate GitHub Apps

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#14661]
### Summary

We still support "Gitpod" GitHub Apps that users can install on their GH orgs/repos, and are used to setup webhooks and update prebuild status on PRs. Since Q1/22 we have a different mechanism to register webhooks, which became the default, because it's much more convenient.

Because of the following reasons we are looking onto deprecating it:
 - you have to use 1 App per Gitpod installation: this was already arkward when using one repo from Self-Hosted and gitpod.io, and will get more arkward when we find ways to setup even more Gitpod installations
 - it was hard to explain customers that GitHub has 2 kinds of "Apps": "OAuth App" (required) and "GitHub App" (to be installed on specific repos by members, but configured at config time :roll_eyes: )
 - the only feature we're currently missing is "send prebuild status/comments to Pull Request". Which would be nice, because we eventually also want this to be supported for other SCMs like GitLab and BitBucket (https://github.com/gitpod-io/gitpod/issues/8796)
 
To completely replace the OAuth app, though, it would be nice to allow users to configure credentials/a token on the Project-level. But that's an useful feature anyway, and independent of this effort.

### Context

See Summary.

### Value

- get rid of two different ways of registering webhooks
- get rid of Probot app and dependencies
- finally support "Prebuuild Status Updates" for other SCMs

### Acceptance Criteria

 - [ ] Built https://github.com/gitpod-io/gitpod/issues/8796
 - [ ] Removed all code related to Probot
 - [ ] Updated documentation regarding webhooks and GitHub Apps

### Measurement

 - [ ] We could remove all code without feature degredation

**Comment by svenefftinge** [comment]
The GitHub App allows for doing certain actions as "Gitpod", that is indeed only comments and checks on PRs and issues atm. I agree we should decouple prebuilds and projects from github app installations.
