### ISSUE TITLE
Epic: Usage-based Pricing general availability

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14969]
This epic tracks remaining issues for [usage-based pricing](https://github.com/gitpod-io/gitpod/issues/9036) GA. 
Original motivation described in https://github.com/gitpod-io/gitpod/issues/9036
Additional (internal) discussions and docs [here](https://www.notion.so/Usage-based-Pricing-Start-Here-861ecc7140b74a3383d39878e36939f9)

#### Bugs
- [x] #15203
- [x] gitpod-io/gitpod#15134
  - [ ] #15202
- [x] gitpod-io/gitpod#14973
- [x] gitpod-io/gitpod#14976
- [x] gitpod-io/gitpod#14992

#### User-facing features
- [x] gitpod-io/gitpod#14475
- [x] gitpod-io/gitpod#14940
- [x] gitpod-io/gitpod#15137
- [x] gitpod-io/gitpod#15160
- [x] #15188

#### Operations
- [x] gitpod-io/gitpod#14652

#### User experience
- [x] gitpod-io/gitpod#14814
  - [x] gitpod-io/gitpod#9898
  - [x] gitpod-io/gitpod#4353
  - [x] gitpod-io/gitpod#15144
- [x] Manually adjust credits for free-tier heavy prebuilds users so that they are not blocked
- [x] gitpod-io/gitpod#15055

#### Workspace classes
- [x] gitpod-io/gitpod#15080 (alternative to gitpod-io/gitpod#14810)
- [x] gitpod-io/website#2973

#### Notifications
- [x] gitpod-io/gitpod#14831

#### Gitpod for Open Source
- [x] gitpod-io/gitpod#14819
- [x] gitpod-io/gitpod#15095 
- [x] Manually adjust usage limits for new or exceptional Open Source participants

#### GItpod for Students
- [x] gitpod-io/gitpod#14025

#### Website, documentation, and other communications
- [x] gitpod-io/website#3102
- [x] gitpod-io/website#3110 
- [x] gitpod-io/website#3109
- [x] Pay-as-you-go announcement ([draft](https://docs.google.com/document/d/1OtBYHRPrSQrvSoG6DjEgDEtZc-v7Wnpb3bsClXzbaPg) - internal)  
- [x] Pay-as-you-go pricing page

**Comment by jldec** [comment]
🚢 ed
