### ISSUE TITLE
[installer] mandate and move `personalAccessTokenSigningKeySecretName` from experimental

### ISSUE THREAD

**Issue by Pothulapati** [gitpod-io/gitpod#15028]
## Is your feature request related to a problem? Please describe

With `public-api` becoming a mandatory component and the signing key being used in `server`,
It makes sense to mandate it as a pre-requisite to be created externally and the secret name
to be passed to the installer.

## Describe the behaviour you'd like

After this change, The installer should follow the convention of mandating
a secret name to be passed for the `render` to work. This secret should then
be loaded and used into components like `public-api` and `server`. The render
should fail otherwise.

This change involves multiple things:
- [ ] mandate and move `personalAccessTokenSigningKeySecretName` from experimental
- [ ] Update `local-preview` to auto-generate a signing key and to use it.
- [ ] (Needed only if there is a `kots` release) Update `kots-install.sh` to auto-generate the signing key

## Describe alternatives you've considered

- Auto-generating the signing key does not make sense as it needs to be same across roll-outs.
- Default static key also does not make sense due to the security concerns.

## Additional context

- https://gitpod.slack.com/archives/C01KLC56NP7/p1669038281983829
