### ISSUE TITLE
Epic: Enable in-place workspace application upgrades

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#15065]
Currently all workspace application changes require the deployment of a new workspace cluster generation which hinders deployment frequency, infrastructure costs, and engineering speed. 

We want to make it possible to do in-place upgrades for all workspace application-level roll-outs to mitigate those issues.

## Value

1. Enabling Gitpod Dedicated growth
2. Increased deployment frequency
3. Reduced engineering effort wasted on manual procedures
4. Reduced infrastructure costs

## Success Criteria

1. Workspace application level roll-outs of multiple Gitpod installations are achievable with a click of button 
2. Roll-out success is automatically monitored, and in case of issues roll-back is automatically initiated
3. Manual rollback should be similarly possible
4. Roll-outs and roll-backs result in no service disruption

## Dependencies 

- [x] https://github.com/gitpod-io/gitpod/issues/15409
- [ ] https://github.com/gitpod-io/gitpod/issues/11416
- [ ] [Dedicated support for in-place upgrades](https://github.com/gitpod-io/gitpod-dedicated/milestone/6)
- [ ] make registry-facade support in-place upgrades
- [ ] make ws-proxy support in-place upgrades
- [ ] remove gRPC calls from image-builder-mk3

## Plan 

TBD

## Resources

[Upgrading Gitpod in a Dedicated world - Gap analysis (internal)](https://www.notion.so/gitpod/Upgrading-Gitpod-in-a-Dedicated-world-Gap-analysis-dbb143176e3c4484b5c617e73be4206c)

## FAQ

1. Can we unlock any value before completing #11416?

**Comment by kylos101** [comment]
:wave: we are attempting :skateboard: in https://github.com/gitpod-io/gitpod/issues/15409

**Comment by kylos101** [comment]
@corneliusludmann does the Scout Team plan to implement in-place upgrades for Workspace components in Gitpod Dedicated using our new https://github.com/gitpod-io/gitpod/pull/15444? I assume yes, that is in support of [milestone 4](https://www.notion.so/gitpod/Milestone-04-Limited-Beta-486d97d185b84d548441e3f071e1ad8d) or [milestone 5](https://www.notion.so/gitpod/Milestone-05-GA-ab75ea6232314570a676cdcc88dad950), but am unsure which milestone it is really being targeted for. For the meantime, Workspace team is beginning work on `Workspace mk2`, such that we may use it to achieve in-place upgrades for gitpod.io, too.

cc: @atduarte
