### ISSUE TITLE
Epic: Usage-based pricing post-release followup issues

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15148]
Post-release issues for [flexible pricing](https://www.gitpod.io/blog/introducing-workspace-classes-and-flexible-pricing#flexible-pricing) in (rough) order of priority.

#### bugs
- [ ] #15202

#### usage and billing
- [x] #15236
- [x] (re-opened) #15055

#### prebuild docs
- [x] gitpod-io/website#1439

#### workspace classes
- [x] #15275
- [x] Needs design: #15287

#### team usage estimator
- [x] #15283

#### finance support
- [x] #15280

#### annual pre-commit
- [x] #14561 (manual, not through Stripe)

#### prebuild behavior
- (handle separately) #15281  
- [x] #15282

#### polish and cleanup
- [x] #15285
- [x] #15247
- [x] #15255
- [x] gitpod-io/website#3137

#### nice to have
- [ ] #15286
- [ ] gitpod-io/website#3135
- [ ] #12341
- [ ] #15246
- [ ] #14844
- [ ] #14595

**Comment by jldec** [comment]
Adjusted priorities - closing this epic.
