### ISSUE TITLE
Discontinue automatic enrollment in the Open Source program on login 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15286]
Followup to #14819

The Open Source program auto-enrollment logic is no longer functional since UBP shipped.
 
- [ ] Disable or remove auto-enrollment on first login
- [ ] Drop the d_b_oss_allow_list table from the DB
- [ ] Add a note to the [original blogpost](https://www.gitpod.io/blog/gitpod-for-opensource) that all new enrollment is by application. The list of names of popular open source packages should also be removed from the blogpost.  (This is for users who find the blogpost from Googling) 
  > NOTE  
  > - Changes to [Gitpod for Open Source](https://www.gitpod.io/for/opensource) were [announced](https://www.gitpod.io/blog/introducing-workspace-classes-and-flexible-pricing#gitpod-for-startups-students-and-open-source) on Dec 8, 2022.
  > - [Gitpod for Open Source](https://www.gitpod.io/for/opensource) users will now receive 2,500 credits per month on their free plan.
  > - Enrollment in the program requires an application. [Apply Now](https://docs.google.com/forms/d/1TE0YGgnUpHxQIH-2Sibn4LldB2ZLlhc_nQo90bJya3w/viewform?edit_requested=true)
