### ISSUE TITLE
Epic: Enable Git Auth for Organizations for Dedicated

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#15955]
## Summary
This epic aims for enabling Git Auth for Organizations for Dedicated installations.

## Context
It is also depending on the outcome of https://github.com/gitpod-io/gitpod/issues/15649.
Follow up for gitpod.io: https://github.com/gitpod-io/gitpod/issues/16932

## Scope
The scope of this epic is limited to enablement of using Git Auth and thereby also starting any workspaces. Obviously this needs to include setting up of Git Auth on the ~team~ org level, symmetrical to the SSO client config.

## Breakdown

```[tasklist]
### Git Auth
* [ ] #15964
* [ ] #15965
* [ ] #15966
* [ ] https://github.com/gitpod-io/gitpod/issues/16873
* [ ] https://github.com/gitpod-io/gitpod/issues/16934
* [ ] https://github.com/gitpod-io/gitpod/issues/17018
```
