### ISSUE TITLE
Epic: Always Create Workspace with Options

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#15979]
Gitpod used to do the-right-thing™️ based on context URLs. I.e. if you throw a PR link at it it will checkout the corresponding branch, if it's an issue it will create a new branch, etc. This was cool and a bit magical (in both good and bad ways), but has become less good, with the variability we have introduced (workspace classes, editor, env variables, etc.).

Therefore we have introduced a start-with-options dialog that allows users to review and change the input parameters to a create-workspace call. So far you have to explicitly pass an argument to get that dialog, but we believe the dialog is helpful to communicate and have users approve how a workspace is created.

Always showing the create workspace dialog also allows for communicating under which organization the workspace is going to be started.

# Proposal
Show the create workspace dialog by default to all workspace creation requests unless there is an explicit argument to skip it (i.e. turn the logic around). Do the context URL parsing to fill the dialog with information about what is going to happen, specifically what repo and branch the workspace is going to be started with. Allow users to change that and confirm.

## Breakdown

```[tasklist]
## Bugs
- [ ] https://github.com/gitpod-io/gitpod/issues/16998
- [ ] https://github.com/gitpod-io/gitpod/issues/16977
- [ ] https://github.com/gitpod-io/gitpod/issues/17016
- [ ] https://github.com/gitpod-io/gitpod/issues/17076
```

**Comment by mbrevoort** [comment]
This [comment](https://github.com/gitpod-io/gitpod/issues/15756#issuecomment-1400877040) is very much related to this proposal
