### ISSUE TITLE
[orgs] Add organizationId to workspace

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#16177]
We want workspaces to be owned by organizations, so we are introducing a reference on the workspace entity.

I'm running this in the following steps:

 - [x] alter the schema (#16192)
 - [x] enhance the code so that new workspaces get an organizationId set (#16261)
 - [x] run a migration that updates workspaces in the past (#16269)
