### ISSUE TITLE
Epic: Single Application Cluster

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#16265]
### Summary

We want to remove the multi-region application deployment we have in gitpod.io which includes removing the `db-sync` component and maintaining multiple databases, because it adds too much complexity and overhead for the value.

The target architecture is one application installation (in US) managing multiple workspace clusters in multiple regions.

[Internal RFC](https://www.notion.so/gitpod/Regional-Workspace-Cluster-Selection-in-Application-d2a3f85652f24492a5511f750de6f83f)

```[tasklist] 
### Preparation
 - [x] https://github.com/gitpod-io/gitpod/pull/16136
 - [x] gitpod-io/gitpod#16271
 - [x] gitpod-io/gitpod#16268
```

```[tasklist] 
### Performing the switch
 - [x] gitpod-io/gitpod#16272
```

```[tasklist] 
### Cleanup
 - [ ] gitpod-io/gitpod#16458
 - [ ] gitpod-io/gitpod#16447
 - [ ] gitpod-io/gitpod#16451
 - [ ] gitpod-io/gitpod#16459
 - [ ] https://github.com/gitpod-io/ops/issues/8562
 - [ ] gitpod-io/gitpod#16457
- [ ] https://github.com/gitpod-io/gitpod/issues/16581
- [ ] https://github.com/gitpod-io/gitpod/issues/16582
- [ ] https://github.com/gitpod-io/gitpod/issues/16603
- [ ] https://github.com/gitpod-io/gitpod/issues/16604
- [ ] https://github.com/gitpod-io/gitpod/issues/16606
- [ ] https://github.com/gitpod-io/gitpod/issues/16605
```

## Previous work and documents
- https://github.com/gitpod-io/gitpod/issues/9198
- https://www.notion.so/gitpod/Get-rid-of-db-sync-Milestone-plan-dfd92243ab8940a280adf71f75039da2
- https://www.notion.so/gitpod/WebApp-Epic-Get-rid-of-db-sync-a790d1d453fa482aa5041a8e0be39c28
-

**Comment by kylos101** [comment]
:wave: hey @svenefftinge, 

Do you need help on the Workspace side?

When were y'all hoping to make these changes? @atduarte mentioned WebApp team was hoping to do the consolidation/move work this week. 

There are a few things I can think of on Workspace side, can you think of anything else?

For example, I was thinking the following would need to change:
* For existing registered clusters, can you set region in the database? Are there any downtime expectations?
* For new clusters, [there's the cluster create job](https://github.com/gitpod-io/ops/blob/main/.werft/workspace-cluster-new.yaml), it looks like we can reuse the existing region parameter values, and will need to (1) [update the gpctl CLI version](https://github.com/gitpod-io/ops/blob/be549ea1927407fa10cc5814cf202bd0ac9eb53d/dev/image/Dockerfile#L109-L110) after [this](https://github.com/gitpod-io/gitpod/pull/16136) merges, (2) [pass the new region arg on cluster register](https://github.com/gitpod-io/ops/blob/be549ea1927407fa10cc5814cf202bd0ac9eb53d/deploy/workspace/gitpod-up.sh#L325-L331) and (3) [avoid registering with a non-governing meta cluster](https://github.com/gitpod-io/ops/blob/be549ea1927407fa10cc5814cf202bd0ac9eb53d/deploy/workspace/gitpod-up.sh#L344-L365)
* For the [cluster delete job](https://github.com/gitpod-io/ops/blob/main/.werft/workspace-cluster-delete.yaml), we'll need to [avoid non-governing meta clusters](https://github.com/gitpod-io/ops/blob/be549ea1927407fa10cc5814cf202bd0ac9eb53d/deploy/workspace/gitpod-down.sh#L67-L76), too.
* [The traffic shifting job](https://github.com/gitpod-io/ops/blob/main/.werft/workspace-shift-traffic.yaml) isn't used, so we're all good there.

cc: @geropl @aledbf

**Comment by svenefftinge** [comment]
Handing over DRI role to @easyCZ so I can focus on #15980

**Comment by kylos101** [comment]
Thanks for the heads up, @svenefftinge ! @easyCZ lemme know if you'd like to plan later this week? As a heads up, I'm deploying for Workspace Team next week, too, and can help with related changes.

**Comment by kylos101** [comment]
We should plan on the following too:
1. For the initial leg of the consolidation, continue registering workspace clusters in the EU region, cordoning US, just incase we have to fallback
2. Once the EU infrastructure is removed, then we can remove the dual cluster registration

**Comment by kylos101** [comment]
Timing wise we'd want to:
1. Make the database change to update existing clusters with the proper region
2. Flip the new feature flag, knowing the only requests making it to the US application cluster are for the US, and route to US workspace clusters
3. Uncordon and update score for EU workspace clusters in the US application cluster, still no traffic will be sent to them until
4. We finally update the GCP load balancer to remove the EU application cluster backend

**Comment by kylos101** [comment]
Before we do [this](https://github.com/gitpod-io/gitpod/issues/16265#issuecomment-1424468077), an internal test might look like:

1. Make the database change to update existing clusters with the proper region
2. Flip the new feature flag, knowing the only requests making it to the US application cluster are for the US, and route to US workspace clusters...**but it would be exclusive to few Gitpodders (us) working this change**
3. Uncordon and update score and **set admission constraint new-workspace-cluster** for EU workspace clusters in the US application cluster, still no traffic will be sent to them until
4. <strike>We finally update the GCP load balancer to remove the EU application cluster backend</strike>, instead of this, we'd  use a VPN to get ourselves to the US application cluster, if needed

**Comment by easyCZ** [comment]
Some additional details for the execution of the switch - [Notion doc (internal)](https://www.notion.so/gitpod/Single-Application-Cluster-Execution-Plan-1b01f57f57324a0dab16704783c7d5ea?pvs=4)

**Comment by easyCZ** [comment]
This is now complete, including removal of unused code.

What remains, and is a potential candidate for removal, is the regional vs global message bus distinction. This will be further cleaned up with the PAYG transition so leaving that for now.
