### ISSUE TITLE
New signup flow improvements

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#16553]
I'd like to use this issue for tracking some improvements to add to the new signup flow

This is following https://github.com/gitpod-io/gitpod/pull/16501 and https://github.com/gitpod-io/gitpod/pull/16543. It is a part of https://github.com/gitpod-io/gitpod/issues/15857. 

- [ ] 1. A first/last name can be just whitespaces. We can use `.trim()` to check they are not in fact empty
    - @gtsiolis: +1, we do also validate such case sin other fields like environment variables, etc.
- [ ] 2. Last names should be optional https://github.com/gitpod-io/gitpod/pull/16501#discussion_r1115549836
    - @gtsiolis: This could be no longer relevant if we merged these two fields into one, see [design export](https://user-images.githubusercontent.com/120486/220930147-0b3878e2-8184-49ec-bd43-b118a553f1ef.png) from https://github.com/gitpod-io/gitpod/pull/16501#pullrequestreview-1311386471.
- [ ] 3. Steps should be skippable https://github.com/gitpod-io/gitpod/pull/16501#discussion_r1115564403
    - @gtsiolis: Debatable as we some steps are required all steps but the last one should be easy to dismiss by just clicking continue.
- [ ] 4. We should add a stepper component so that the user knows ~ how long this process will take https://github.com/gitpod-io/gitpod/pull/16501#discussion_r1116191291 	
- [x] ~~5. The flow does not actually update commiter info https://github.com/gitpod-io/gitpod/pull/16501#pullrequestreview-1312074545~~
    - @gtsiolis: No longer relevant as the page copy has been updated.
- [x] 6. Completion of the flow is missing confetti https://github.com/gitpod-io/gitpod/pull/16543
    - @gtsiolis: Change has been merged, but haven't seen it in action—~~may have to revert~~, see [relevant discussion](https://gitpod.slack.com/archives/C04PH56LZK5/p1677240990505319) (internal).
- [ ] 7. One cannot go back a step to correct info (a <kbd>Back</kbd> button)
    - @gtsiolis: Debatable as all options can be changed later, expect the last step.
- [ ] 8. The phrasing on the `I'm signing up for Gitpod to...` question is a bit odd (reads weird with the options below it)
    - @gtsiolis: +1, an alternative phrase could be something like the [design export](https://user-images.githubusercontent.com/120486/220930176-04750b60-e7d5-42fc-b165-4c2f0869cb3c.png) from https://github.com/gitpod-io/gitpod/pull/16501#pullrequestreview-1311386471.
- [x] 9. URL is spelled as `url` in the error message 
- [ ] 10. (low-prio): URLs such as `192.168.0.1/`, `iphone.local` get past verification
- [x] 11. @phimae:  Email should be Work Email
    - @gtsiolis: Opened https://github.com/gitpod-io/gitpod/pull/16558 to resolve this.

**Comment by filiptronicek** [comment]
cc @selfcontained, maybe there is a better place for these, but wanted to make sure they are documented somewhere. Feel free to update! 

If I find the time, I'll try to fix some of the more minor ones myself

**Comment by gtsiolis** [comment]
Updated the tasks to an ordered list, so we can reference them easier. Cc @filiptronicek

**Comment by phimae** [comment]
Thanks for opening up this follow up @filiptronicek!

Couple of comments from my side:

> 2. Last names should be optional https://github.com/gitpod-io/gitpod/pull/16501#discussion_r1115549836

Let's keep it as is please - people without a last name are very, very few and even they can get around this by putting something in. Not having a last name prevents us from enrichment

>  8. The phrasing on the I'm signing up for Gitpod to... question is a bit odd (reads weird with the options below it)

Suggestion to rename:
" I want to experience.."

My own follow-ups:

- [ ] Email should be Work Email
- [ ] Company website: Can we make it so the user does not need to add https:// and www.? - otherwise I think completion will be much lower
Proposal: What currently shows https:// in grey could be switched to example.com in the helper text

**Comment by gtsiolis** [comment]
Re: Company website: Although having the http(s):// prefix is a common practice in validating a URL, relaxing this and dropping the `http(s)://` prefix requirement sounds more frictionless. For example, you can't even add `www.gitpod.io` but I'd assume it should be fine to just add `gitpod.io`. 🤷

**Comment by filiptronicek** [comment]
Many thanks for the thoughtful comments, @gtsiolis & @phimae! It's awesome that we can start discussion from this.

**Comment by filiptronicek** [comment]
Just my thoughts around some of your comments (thanks so much again for bringing them up, it's awesome that we can start a discussion about these):

> One cannot go back a step to correct info (a Back button)
    @gtsiolis: Debatable as all options can be changed later, expect the last step.

Maybe be worth it to mention that in the onboarding pages, because users may fear not being able to update it later.

> Steps should be skippable https://github.com/gitpod-io/gitpod/pull/16501#discussion_r1115564403
    @gtsiolis: Debatable as we some steps are required all steps but the last one should be easy to dismiss by just clicking continue.

Thanks for bringing this up! I agree with you here, but from my perspective I would like to be able to skip these steps (we already have very sensible defaults for all of them) to:
1. Be more user friendly - if users just want to get to coding ASAP when signing up, this will be more friction
2. Let users onboard themselves later, using the Preferences, the actual interface they will be using for the remainder of their stay on Gitpod. 
3. Make it easier to skip when in e.g. preview environments

**Comment by gtsiolis** [comment]
Also checked points [5], [9], and [11].

URL validation has been updated in https://github.com/gitpod-io/gitpod/pull/16543 to use `validator/lib/isURL`, see [relevant diff](https://github.com/gitpod-io/gitpod/blob/e6fb5c9389bd47b1252bbc54ddf41bb1958d5248/components/dashboard/src/onboarding/StepOrgInfo.tsx#L18). Cc @selfcontained 

Adding below some thoughts regarding the remaining to-dos:

- [1]: Valid point—we can open a follow-up issue to discuss more and possibly use `.trim()` as @filiptronicek mentioned above. ✔️ 
- [2]: Valid point—we can open a follow-up issue to discuss making this a single input, see see [design export](https://user-images.githubusercontent.com/120486/220930147-0b3878e2-8184-49ec-bd43-b118a553f1ef.png) from https://github.com/gitpod-io/gitpod/pull/16501#pullrequestreview-1311386471. ✔️ 
- [3]: It could be ok to have a skip button on the third step where we collect org information when someone is using Gitpod for nonwork. 💭 
- [4]: A stepper component could help, but I'd rather skip the last step when someone is using Gitpod for nonwork, which would make a stepper dynamic and possibly better to avoid. :x:
- [7]: +1 but I'd only add this on the third step. 💭 
- [8]: See [design export](https://user-images.githubusercontent.com/120486/220930176-04750b60-e7d5-42fc-b165-4c2f0869cb3c.png) from https://github.com/gitpod-io/gitpod/pull/16501#pullrequestreview-1311386471. 💭 
- [10]: Probably not worth the effort—if a user takes the effort to bypass this optional field with such values, that's ok. :x:

Cc @phimae
