### ISSUE TITLE
Epic: Local SSH Gateway

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16836]
## Press Release

Gitpod users don't need to upload SSH keys anymore.

**Questions:** 

1. Will this affect VS Code restart? 
    Depends how we define restart. If it restarts with our workspace, it makes it smoother.

## Value
With Local SSH Gateway, when a user tries to connect to a workspace, it connects to local ssh gateway. There is no password or ssh key needed, because the local ssh gateway gets the owner token from the Gitpod VSCode Desktop extension. 

## Context
<img width="612" alt="Untitled" src="https://user-images.githubusercontent.com/8015191/227579795-d8a80c36-5e84-4cd0-9f33-c99bca33b73e.png">

## Acceptance Criteria
- [x] User can open a workspace on VSCode Desktop without the above friction
- [x] When a user restarts a workspace, they don't have to go through the hassle of copying password
- [x] Enabled under a feature flag
- [x] Have analytics

## TODOs

- [x] Take care of local ssh server’s port
- [x] Add DNS record to point to local 
      https://github.com/gitpod-io/ops/pull/8989 
      https://github.com/gitpod-io/gitpod/pull/17117
- [x] Add proper telemetry and error/crash reporting
- [x] Test remote.ssh.xx features (`enablexxx` are most important) with directssh, localapp and localssh. Detail see [Linear](https://linear.app/gitpod/issue/IDE-29/localssh-%E2%9A%94%EF%B8%8F-directssh-localapp)
- [ ] Dogfood in Gitpodders and make sure users can't use it now

## Out of scope
- Restarting from VSCode Desktop extension

**Relates to:** 
- https://github.com/gitpod-io/gitpod/issues/15919
- https://github.com/gitpod-io/gitpod/issues/15920

**Comment by loujaybee** [comment]
@laushinka to investigate and update description more after speaking to the team 🙏

**Comment by akosyakov** [comment]
> Will this affect VS Code restart?

No, I don't think so. It is about smooth connection/reconnection, not restarting a workspace.
