### ISSUE TITLE
Epic: Admin Onboarding v1

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#16864]
## Summary

This epic enables admins to log-in to a Dedicated installation the first time, and finish the required setup of the Organization.

Once this epic is done:
- dedicated "admin" users can follow a link to log in to a first web session
- they are not allowed to access instance-level functionality (installation-level users, /admin area)

## Context
 - https://www.notion.so/Align-on-path-to-first-onboarding-flow-in-preview-envs-12d798d744ab40ba996e613d128063ca

```[tasklist]
# Login flow v1
- [ ]  https://github.com/gitpod-io/gitpod/issues/16223
- [ ]  ...
```

```[tasklist]
# Constraints:
- [ ]  constraint: admin-user cannot create more than one org (? workaround until we can limit this with permissions)
- [ ] https://github.com/gitpod-io/gitpod/issues/16935
- [ ] https://github.com/gitpod-io/gitpod/issues/16936
```

**Comment by geropl** [comment]
Moved to: https://linear.app/gitpod/issue/WEB-27/admin-onboarding-v1
