### ISSUE TITLE
Epic: Login with SSO

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#16862]
## Summary

This epic enables users to configure and login with SSO from the UI.

Once this epic is done:
- users can login to an organization via the UI 
- admin users can configure everything to make this work in the UI, incl. a slug to uniquely identify the Organization

## Context
parent epic: https://github.com/gitpod-io/gitpod/issues/7761
previously https://github.com/gitpod-io/gitpod/issues/15955 would hold some of these task

```[tasklist]
# Configure SSO
- [ ]  https://github.com/gitpod-io/gitpod/issues/16856
- [ ]  https://github.com/gitpod-io/gitpod/issues/15960
- [ ]  https://github.com/gitpod-io/gitpod/issues/15961
- [ ]  https://github.com/gitpod-io/gitpod/issues/15995
```

```[tasklist]
# Login UI/UX:
- [ ]  https://github.com/gitpod-io/gitpod/issues/15967
- [ ]  https://github.com/gitpod-io/gitpod/issues/15968
- [ ]  dedicated: Skip “Org selector” for “single org” case
```

**Comment by charleswhchan** [comment]
Hello,

I would like to add OidcAuthProviders config to the installer (similar to [config.go::AuthProviders](https://github.com/gitpod-io/gitpod/blob/e01ca57b69b8b7d20a9660eb5fc6c03b004e15f1/install/installer/pkg/config/v1/config.go#L146)) to automate the config, what's the correct behavior?
a. retrieve the config on deploy
b. write config to database on component/server start up

Note: I am happy to create a PR with guidance.

**Comment by AlexTugarev** [comment]
@charleswhchan, thanks for raising this question! I'll forwarded that internally, as the answer isn't just about a technical problem to be solved.
