### ISSUE TITLE
Epic: Sessions with JWTs

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#16891]
### Summary

In this workstream, we're migrating the existing sessions to use JWTs, such that we can establish the caller identity on different components, rather only on `server`.

### Context
This is a necessary step to align WebApp with our desired architecture where we move towards gRPC for services/endpoints and can implement these across both TypeScript and Go.

### End-result
![Untitled-2022-11-09-0837 (4)](https://user-images.githubusercontent.com/1419286/225871927-679efcba-2854-473e-b10d-b9c00092c7d1.png)

### Further details
* [(internal) Slack thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1678974029956599)

```[tasklist]
### JWTs in parallel with existing sessions
- [ ] https://github.com/gitpod-io/gitpod/issues/16892
- [ ] https://github.com/gitpod-io/gitpod/issues/16895
- [ ] https://github.com/gitpod-io/gitpod/issues/16893
- [ ] https://github.com/gitpod-io/gitpod/issues/16894
```

```[tasklist]
### Default to JWTs
- [ ] Stop issuing old session tokens when signing-in
- [ ] Wait for all sessions to be JWT based
```

```[tasklist]
### Cleanup
- [ ] Remove old sessions middleware from Server
- [ ] Remove DB models for `gitpod-sessions` db
- [ ] Remove `gitpod-sessions` db
```
