### ISSUE TITLE
Epic: Rollout Git Auth for Organizations on gitpod.io

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#16932]
## Summary
This epic aims for enabling Git Auth for Organizations on gitpod.io to all users.

## Context
Based on prior work in https://github.com/gitpod-io/gitpod/issues/15955

## Scope
The scope of this epic is to drive "Git Auth for Organizations" to GA on gitpod.io. It's mostly concerned with testing, especially around UX flows and proper selection of Git Auth providers with multiple Organizations.

## Breakdown

```[tasklist]
### Git Auth
* [ ] Test: Create GitHub OAuth app for github.com and use it
* [ ] Lift all lookups based on (hostname) to also include the org (org, hostname) (Example: git auth from within a workspace)
* [ ] UX: Make sure flows stay smooth, especially in face of multiple orgs with different/same SCM hosts
* [ ] https://github.com/gitpod-io/gitpod/issues/17014
* [ ] https://github.com/gitpod-io/gitpod/issues/17014
```

**Comment by geropl** [comment]
Moved to: https://linear.app/gitpod/issue/WEB-52/git-integrations-for-organizations-on-gitpodio
