### ISSUE TITLE
Allow alternative IDEs

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#1780]
We want to allow users to use whatever IDE works best for their use case. To that end we should allow users to configure Gitpod so that it provides web-based editing interfaces :
 - [x] Theia
 - [ ] Custom Theia (Custom IDEs built on Theia extensions)
 - [x] VS Code ~~(e.g. code-server)~~
 - [ ] Jupyter Notebook
 - [ ] Just Xterm.js

To allow this we need to extract the gitpod-protocol related services from Theia and make them available through an API (grpc). Architecturally we want to have super visor run a server that allows access to that API. That server should also serve a light interface taking care of the loading sequence and eventually run whatever interface was chosen in an iframe. 

The in-workspace API serves functionality around
 - stopping workspace
 - managing ports
 - managing env variables
 - sharing workspace
 - taking snapshots
 - access to GL/GH/BB tokens

As a first step the server side will forward these requests to the slim frontend which then can use the existing gitpod-protocol within the context of a secure http session. I.e. this API only works if the owner is connected through a valid session.

**Comment by sr229** [comment]
If you need assistance with integrating code-server, I'm all ears. However, during my experience with code-server porting with Eclipse Che, VS Code won't be aware of the additional container runtimes which Che is using for pluggable runtime tooling, I'm interested how would you tackle this.

Browsing VS Code's source there is a simple server we can use as well however I do think code-server would be suited.

**Comment by svenefftinge** [comment]
code-server is not maintained and actually also no longer necessary as the vscode team has changed its project to allow running vscode in browsers through the last months. Going with that makes more sense as it is closer to the real thing.
WRT additional container runtimes in Che: Gitpod doesn't impose those requirements.

**Comment by sr229** [comment]
@svenefftinge To be honest we would like to be in parity with Codespaces if we're integrating VS Code entirely, that's something we would like to do.

And I would opt in to more informative loading screens like what Codespaces does 

![image](https://user-images.githubusercontent.com/14976516/93468136-1fbdf080-f921-11ea-9ca8-6b19e4470cba.png)

**Comment by tekumara** [comment]
Is code-server the same as [cdr/code-server](https://github.com/cdr/code-server) (which has a recent release) or that something different?

**Comment by sr229** [comment]
> Is code-server the same as [cdr/code-server](https://github.com/cdr/code-server) (which has a recent release) or that something different?

@tekumara I think he meant Coder's code-server, though we're looking at our own approach in development here.
