### ISSUE TITLE
✌️

### ISSUE THREAD

**Issue by JennPlothow** [gitpod-io/gitpod#18442]
## Additional context

```[tasklist]
### Tasks
- [ ] https://github.com/gitpod-io/gitpod/issues/11339
- [ ] https://github.com/gitpod-io/gitpod/pull/18441
- [ ] https://github.com/gitpod-io/gitpod/issues/9452
- [ ] https://github.com/gitpod-io/gitpod/pull/18434
- [ ] https://github.com/gitpod-io/gitpod/pull/18403
- [ ] https://github.com/gitpod-io/gitpod/pull/18429
- [ ] https://github.com/gitpod-io/gitpod/pull/18412
- [ ] https://github.com/gitpod-io/gitpod/pull/18415
```

**Comment by JennPlothow** [comment]
Please provide more context or a sentence that needs to be rewritten in better English.
[CONTRIBUTING (2).md](https://github.com/gitpod-io/gitpod/files/12267535/CONTRIBUTING.2.md)

**Comment by JennPlothow** [comment]
For your next input, I will rewrite it in better English.
![QubyDanceGIF](https://github.com/gitpod-io/gitpod/assets/81450408/fe305975-756d-401c-a744-aea36adc7114)
