### ISSUE TITLE
The Workspaces List doesn't work well on mobile

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#1858]
### Describe the bug

The list of Gitpod Workspaces doesn't work well on mobile:

<img width="375" alt="Screenshot 2020-09-15 at 11 47 17" src="https://user-images.githubusercontent.com/599268/93195242-4d504180-f749-11ea-9f3b-aa7806ba4d9f.png">

### Steps to reproduce

1. Open https://gitpod.io/workspaces/ on mobile

### Expected behavior

We should find a better layout for mobile.

But maybe we can approach this with small, incremental improvements:

- [ ] The first improvement would be to shorten the very long Git hashes that overflow on the right (e.g. only display the first 8 characters, while keeping the link href unchanged)

    - I think the Git refs should be shortened on all screen sizes (i.e. mobile and also desktop) because showing full Git refs is almost never useful (you either want the full URL, or a few letters)

    - On the other hand, I think the long Workspace ID should stay at full length, because that's something that users often need to copy/paste, and it currently works well even on mobile screens

- [ ] Next, maybe on narrow screens the buttons could break to a new line (i.e. below "last run N hours ago") and flow horizontally (e.g. `Download` left and `Start` right)

- [ ] Next, the "Created N hours ago" text should also probably break to a new line (below the name of the workspace) on narrow screens

I think these 3 improvements will already make the Workspaces List much better on mobile.
