### ISSUE TITLE
[code] integration test cut-through

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3065]
It would be good to automate testing of Code integration.

## Tasks

- [x] provide nightly version: https://github.com/gitpod-io/gitpod/pull/6094
- [x] enable nightly werft job: https://github.com/gitpod-io/gitpod/issues/6200
- [x] deploy nightly version
- [x] allow to run VS Code test extension against Gitpod Code server running in the workspace
- [ ] configure running nightly integration tests against stable
- [ ] setup slack notifications for nightly version build as well as nightly integration tests

**Comment by csweichel** [comment]
Ideally integrated into our integration tests, so that the Code integration tests would be part of Gitpod's integration tests.

**Comment by akosyakov** [comment]
We do really a lot of repetitive testing each month. It is better to look into how it can be automated.

**Comment by akosyakov** [comment]
There are some smoke tests in VS Code repo: https://github.com/Microsoft/vscode/blob/main/test/smoke/README.md Maybe we can do something based on them.

**Comment by csweichel** [comment]
I fully agree this would be awesome to have, and it clearly supports our goals. It's not directly impacting the dev loop though, no?

**Comment by akosyakov** [comment]
When someone works on upgrade to VS Code or new integration it does, but agree that it does not impact full team.

**Comment by akosyakov** [comment]
We merged our first test, not we need to setup nightly job for staging which run it.

@csweichel Should https://github.com/gitpod-io/gitpod/blob/main/.werft/run-integration-tests.yaml be used as a template?

**Comment by jeanp413** [comment]
yes, all those three.

**Comment by jeanp413** [comment]
- [ ] Fix python tests
- [ ] Enable select stable or insiders
- [ ] Slack notification

**Comment by akosyakov** [comment]
@jeanp413 is it done?
