### ISSUE TITLE
[dashboard] Misc outstanding issues

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3507]
Here're some more outstanding issues, feel free to resolve here or a new PR. (from @gtsiolis in #3496 )

 - [x] Avatar Menu actions don't work (settings / logout)
 - [ ] When searching and focus is on the search text field, on ESC clear the search input.
 - [x] Pressing ESC opens up the "new workspace" (at least after it was opened once)
 - [x] Clicking Open in the more actions dropdown for stopped workspaces does not work.
 - [x] introduced aliases used in the wild (e.g. /settings, /upgrade-subscriptions)
 - [x] Persist top menu state on Workspaces and Settings
 - [x] Could we apply a subtle hover transition effect on everything? See also [relevant discussion](https://gitpod.slack.com/archives/C01KGM9BUNS/p1615919354035200).
 - [x] When clicking on Workspaces the top menu always move to Active workspaces.
 - [ ] Let's also change the font weight for more actions dropdown items to `font-medium`
menu. Also, let's change the dropdown spacing from `space-y-2` to `space-y-1` and `py-2` to `py-1`.
 - [ ] What do you think of removing the responsive layout of the table? Is this easily turned off? If not, feel free to ignore for now.
 - [x] Can we also remove the responsive layout of the top menu and profile menu?
 - [ ] Workspace more actions button should be visible only on hover. See similar approach in https://github.com/gitpod-io/gitpod/pull/3464#discussion_r595402190.

**Comment by gtsiolis** [comment]
Adding the follow up issues from https://github.com/gitpod-io/gitpod/pull/3510#pullrequestreview-616836938. /cc @jankeromnes @svenefftinge 

- [ ] Let's truncate this as it can break the layout for this component! See https://github.com/gitpod-io/gitpod/pull/3510#discussion_r598011266
- [ ] Can we center align all the elements within this div and also keep a fix width for the workspace reference? See https://github.com/gitpod-io/gitpod/pull/3510#discussion_r598012760.
- [ ] Both of these buttons lack hover state. Maybe we could add this on the button component in [`index.css`](https://github.com/gitpod-io/gitpod/blob/dashboard-v2/components/dashboard/src/index.css#L31-L33). See https://github.com/gitpod-io/gitpod/pull/3510#discussion_r598013244.
