### ISSUE TITLE
"What's New" screen could be improved

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3649]
<img width="450" alt="Screenshot 2021-03-29 at 21 09 37" src="https://user-images.githubusercontent.com/599268/112888177-53e64b00-90d4-11eb-9b35-3127a47c2f9d.png">

- [ ] It doesn't say "Gitpod" anywhere. (Maybe in the first sentence, "the product" should be called "Gitpod" instead? And/or replace "on the dashboard" with "to Gitpod's dashboard")
- [ ] Cognitive dissonance: "We're preserving all user settings and extensions." is immediately contradicted by "Extensions you have manually uploaded are not transfered." (also typo: "transferred")
- [ ] Typo: "convenienvt"
- [ ] "You can still switch the editor to Theia" can be much simplified as "You can still switch back to Theia" (also, I'm not sure why we use "editor" and "IDE" interchangeably -- to me it should be "IDE" everywhere, as "editor" is just the part where I edit code)
- [ ] What is the difference between X, Dismiss and Continue?
