### ISSUE TITLE
[dashboard] Remaining issues in new start screen

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3689]
- [x] Re-implement "repository may be private" errors (currently just "not found")
- [x] Re-implement "out of hours" and "too many running workspaces" errors
- [x] Wrong error message being displayed when running prebuild twice on same commit https://github.com/gitpod-io/gitpod/issues/3687
- [x] Center error message and button on stopping workspace page https://github.com/gitpod-io/gitpod/issues/3654
- [x] Fix double "Back to Dashboard" button in some cases(?)
- [x] Implement stopped workspace pending changes summary (dropdown / alert)
- [x] Actually handle/show `ideFrontEndFailureCause` error (can happen in rare cases, sent by supervisor via iframe event, but not sure how to trigger it)
- [x] Improve error message when someone tries to open a merged PR with deleted branch https://github.com/gitpod-io/gitpod/issues/3659
- [x] Missing error log "Error: build failed: cannot build base image: Error response from daemon: Dockerfile parse error line 4: unknown instruction: ERROR" when trying to build https://github.com/gitpod-io/ruby-on-rails/tree/test-branch
