### ISSUE TITLE
Support Chromium development

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#377]
I think it would be awesome to support building & running the Chromium browser in Gitpod. It would make a great proof-of-concept to show just how powerful Gitpod is, and it would be helpful to people like @beaufortfrancois who regularly work on Chromium using a Chromebook.

My feeling is that it's already almost possible to build & run Chromium in Gitpod, with just a few tweaks. (I.e. no need to change the infrastructure, nor to develop complicated things). And this would likely also clear the path for many other cool projects like Firefox, Servo, Thunderbird, Git, LLVM/Clang, GCC, Linux, etc.

Let's try to achieve this, and fix any roadblocks we hit along the way:
- [x] Pre-configure https://github.com/chromium/chromium (done in Gitpod's [external configs](https://github.com/gitpod-io/definitely-gp/tree/master/chromium))
- [x] Allow cloning the Chromium repo (increase the start-up grace period: cloning takes ~30min)
- [x] Allow stopping & restarting a Chromium workspace (increase the backup max size: a Chromium checkout is ~25GB)
- [ ] Allow sharing snapshots of a (partially) built Chromium workspace (increase the backup max size again)
- [x] Allow building Chromium faster with more threads (increase the workspace RAM hard limit)

The end goal here is to produce a Gitpod snapshot link with a fully compiled Chromium checkout, allowing you to hack, rebuild, and run Chromium graphically.

**Comment by pangqingyuan1991** [comment]
Compiling is OK. But running? How? It is a X11 GUI program, how can you run a X11 GUI program within gitpod container?

**Comment by jankeromnes** [comment]
> Compiling is OK. But running? How? It is a X11 GUI program, how can you run a X11 GUI program within gitpod container?

It's pretty easy actually, you can use the `gitpod/workspace-full-vnc` Docker image to get a web-based Virtual Desktop in Gitpod.

Either specify `image: gitpod/workspace-full-vnc` in your `.gitpod.yml`, or write a custom Dockerfile with `FROM gitpod/workspace-full-vnc` [like Chromium](https://github.com/gitpod-io/definitely-gp/blob/master/chromium/Dockerfile#L1).

See this [blog post](https://medium.com/gitpod/developing-native-ui-applications-in-gitpod-15af2967c24e) for more details.

**Comment by jankeromnes** [comment]
The RAM hard limit has been increased to 8.30GiB, which should be sufficient to build Chromium (at least without `jumbo_build` for now). 🎉

The last remaining blocker is to increase the snapshot backup size, but we've agreed that it would be a better idea to first implement disk usage monitoring, in order to get a better handle on our servers' disks getting 100% full (this currently happens a few times each month, and causes various issues, but it should be pretty easy to avoid).

**Comment by jankeromnes** [comment]
Also creating a new Chromium workspace currently fails:

<img width="1552" alt="Screenshot 2019-06-28 at 15 52 31" src="https://user-images.githubusercontent.com/599268/60347050-cafd2580-99bc-11e9-99cf-05bbc986ed12.png">

**Comment by JesterOrNot** [comment]
Any updates here? Is this feature finished or is it still under dev?

**Comment by jankeromnes** [comment]
@JesterOrNot It should basically/almost work by now, but you may encounter a few rough edges.

For example, the `git clone` step may take a long time, and workspace backup & restore may not work. Needs more testing.

**Comment by JesterOrNot** [comment]
can you add git clone to prebuild?
