### ISSUE TITLE
[first week] April 2021

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3775]
# ToDo

- [ ] @wulfthimm reinstate https://github.com/gitpod-com/gitpod/commit/a3c4783e15be2c2287f20ef7a71c44ee3b88bd6b
- [x] @ArthurSens make https://github.com/gitpod-io/gitpod/pull/3607 work
- [x] @ArthurSens add metrics to db-sync https://github.com/gitpod-com/gitpod/pull/5224 (merged, but needs to be tested on staging)
- [x] @aledbf reduce headless log noise (either https://github.com/gitpod-io/gitpod/pull/3774 or https://github.com/gitpod-io/gitpod/pull/3776)
- [x] @aledbf Add leeway script to update protobuf generated code (removes protobuf warnings) #3669
- [x] @geropl Fix workspace GC https://github.com/gitpod-io/gitpod/issues/3772
- [ ] @AlexTugarev Implement "Select Account" page https://github.com/gitpod-io/gitpod/issues/3754
- [x] @geropl ws-cluster API bugs https://github.com/gitpod-io/gitpod/issues/3792
- [x] @aledbf [chart] Tune rabbitmq defaults #3807
- [x] @jankeromnes Redirect to /blocked when trying to create/start a workspace https://github.com/gitpod-io/gitpod/issues/3783
- [ ] @jankeromnes Fix 'Continue with Default Image' button when Docker build is still running https://github.com/gitpod-io/gitpod/issues/3777
- [x] @jankeromnes Re-implement 'Cancel Downgrade' https://github.com/gitpod-io/gitpod/issues/3795
- [x] @akosyakov cannot change permissions for read:user https://github.com/gitpod-io/gitpod/issues/3796
- [x] @akosyakov fix reconnection to the extension host process for VS Code @akosyakov https://github.com/gitpod-io/gitpod/issues/3797
- [x] @AlexTugarev  Does decline work with GitHub? #3801
- [ ] @AlexTugarev  Clean up token on deauthorize #3800
- [x] @aledbf [chart] Migrate mysql from stable repository #3786 
- [x] @aledbf [content-service] Return ErrNotFound if bucket object does not exists #3773
- [x] @aledbf  [ws-daemon] Close grpc server and daemon socket #3824
- [x] @aledbf [dev] Update go to 1.16.3  https://github.com/gitpod-io/gitpod/pull/3820
- [x] @aledbf [dashboard] Replace nginx with caddy #3851
- [x] @aledbf [dashboard] Optimize build #3830
- [x] @aledbf Install node.js dependencies before generating grpc code #3868
- [x] @aledbf [content-service] Update cloud.google.com/go/storage dependency #3809

**Comment by geropl** [comment]
- [ ] Fix workspaces GC: https://github.com/gitpod-io/gitpod/issues/3772

**Comment by jankeromnes** [comment]
- [ ] Fix 'Continue with Default Image' button when build is still running https://github.com/gitpod-io/gitpod/issues/3777

**Comment by jankeromnes** [comment]
- [ ] [Blocked] Redirect to /blocked when trying to create/start a workspace @jankeromnes https://github.com/gitpod-io/gitpod/issues/3783

**Comment by jankeromnes** [comment]
- [ ] @jankeromnes Re-implement 'Cancel Downgrade' https://github.com/gitpod-io/gitpod/issues/3795

**Comment by akosyakov** [comment]
- [ ] https://github.com/gitpod-io/gitpod/issues/3796

**Comment by akosyakov** [comment]
- [ ] fix reconnection to the extension host process for VS Code @akosyakov https://github.com/gitpod-io/gitpod/issues/3797

**Comment by AlexTugarev** [comment]
- [ ] Does decline work with GitHub? #3801
- [ ] Clean up token on deauthorize #3800

**Comment by akosyakov** [comment]
- [ ] https://github.com/gitpod-io/gitpod/issues/3808 theia extension host process seems to be broken

**Comment by jankeromnes** [comment]
- [ ] @jankeromnes Fix "Timed Out" screen when the workspace timed out while the laptop was asleep https://github.com/gitpod-io/gitpod/issues/3811
