### ISSUE TITLE
[epic] Improve dev experience

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3802]
- [ ] preview envs deployments break:
   - [x] workspaces don't delete (because finalizer or because \<random reason\>): https://github.com/gitpod-io/gitpod/issues/3803
   - [x] namespaces are not wiped: #3952
   - [x] deleting workspaces breaks: https://github.com/gitpod-io/gitpod/issues/3803
   - [ ] certificates don't work
   - [x] branch name too long for DNS name (no certificate): https://github.com/gitpod-io/gitpod/issues/3505
   - [x] port clashes: https://github.com/gitpod-io/gitpod/issues/3913
   - [ ] core-dev cluster VMs /run runs full (no secrets/configmap work in deployments): #3949
   - [ ] ws-daemon takes ages (up to 10 minutes) to come up on core-dev
   - [ ] ws-daemon does fail while trying to modify /etc/hosts
- [ ] telepresence does not work (for most components)
   - related: #3834
- [ ] gitpod.io itself:
   - [ ] Go LS not working (reliably/fast enough)
   - [ ] VSCode: frequent connection loses
   - [ ] VSCode: impact of connection too high (editors started with code --wait block after window reload)
   - [ ] VSCode: "Enter" sometimes stuck in wrong menu (all other keys work) (Firefox)
   - [ ] `export EDITOR="code --wait"` needed to make `kubectl edit`/`git rebase` work. In case the connection breaks during a session, the terminal is broken forever

**Comment by geropl** [comment]
Everything listed here is either fixed or is tracked elsewhere now.
