### ISSUE TITLE
Improve responsive layout for the dashboard

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4050]
### Problem to solve

Although the new dashboard layout was not optimized for being responsive on smaller viewports, layout is relatively acessible for medium and large viewports.

Still, there are some minor issues that are visible also on medium viewports, see https://github.com/gitpod-io/gitpod/issues/3859 and https://github.com/gitpod-io/gitpod/issues/3829.

FWIW, we're currently introducing a scrollable modal in https://github.com/gitpod-io/gitpod/pull/3995 which could be useful to componetization of the modal component.

### Proposal

MVC steps here could be the following:
- [ ] Resolve the scrollbar issues on Plans and Integrations pages, https://github.com/gitpod-io/gitpod/issues/3859.
- [ ] Resolve the accessibility issues with the scrolling container in the modals, https://github.com/gitpod-io/gitpod/issues/3829.
- [ ] Design and implement a responsive layout for component like settings sidebar, workspaces list, top navigation, etc.

**Comment by jankeromnes** [comment]
I would absolutely _love_ to add minimum viable responsiveness to our dashboard. This unfinished business has been gnawing at me for months now.

I can time-box this e.g. to one or two days if that's helpful.

**Comment by pri1311** [comment]
The responsiveness issue also arises for the edit permissions modal. I didn't see this specifically mentioned anywhere, hence adding it here. Have to resize the window to 90% to see the update permissions button.
![image](https://user-images.githubusercontent.com/64613009/144757194-98af1185-947b-4b29-b174-e60af11e117b.png)

**Comment by gtsiolis** [comment]
Thanks @pri1311! I've reopened https://github.com/gitpod-io/gitpod/issues/3829 for this.

**Comment by jankeromnes** [comment]
Not stale 😇
