### ISSUE TITLE
[self-hosted] Support newer releases of Ubuntu and Kubernetes

### ISSUE THREAD

**Issue by cyrilcros** [gitpod-io/gitpod#4053]
## Current state
Basically, self-hosted currently requires Ubuntu 18.04 and Kubernetes ~1.17 - 1.18 (EDIT: well, I am unfair here for Kubernetes). It would be very desirable to move the current support matrix closer to the Ubuntu and Kubernetes respective release cycles. 
For instance, as pointed in #3969, Ubuntu 18.04 is now 3 years old, and 20.04 has been around for a year. This issue is by the way the same request, but for workspace image support whereas I am talking self-hosted...
It means:
-  people are stuck on relatively old setups, are less likely to try this and adopt it or contribute code, or may lose time (ex: there is no obvious link to the support matrix in the self-hosted docs or the repo main page)
- some newer kernel features are missing (ex Wireguard in the linux kernel, since SSH support was added to Gitpod that could be a similar step, and many CNI like Calico or Cilium are adding it as an option).
- for software development, it is generally problematic...

## Improvement suggestions for self-hosted
I fully understand this is a massive amount of work and not realistic to always stay on top of this. However, could you please:

- [ ] make the support matrix for self-hosted clearly visible on the repo Github page / your docs. That would reduce the number of issues you folks get....
- [ ] add detailed setups (platform / versions / but also the CNI for example, and the `values.yaml` you used - without secrets) 
- [ ] give a tentative timeline for supporting newer versions (or just a 'not in our current plans' answer). 
- [ ] add to the issue tracker a category like `broken in Ubuntu 20.04`, to keep track of what is missing, and possibly allow people to help. That could be a pinned issue.
- [ ] add / link to a new technical document page describing the overall architecture of gitpod. For example, what are `ws-daemon` , `blobserve`, why is there a `registry-facade`, why is there a `ws-manager` plus a `ws-manager-bridge`, which of them have access to the `kubeapi-server`  or are open to the Internet. That would help with error reporting.

This being said, many thanks for offering this software as a self-hosted option, I definitely prefer it to Eclipse Che and others..... It has a lot of potential, it could do for programming what the [Jupyterhub](https://zero-to-jupyterhub.readthedocs.io/en/stable/) project does for Jupyter notebooks.

**Comment by flickerfly** [comment]
I'm studying up for the potential of a self-hosted install. Is Ubuntu required somehow? That is unexpected for a kubernetes native application. 

I'd be glad to contribute back things I'd have to do to make it work on newer versions of Kubernetes. I'd assume that's adjustments to the helm charts, not in the pods themselves right? I spent some time creating a sketch of the components and related manifests as created by the helm chart and attached here. Super notebook mess type stuff, but maybe a start for the last point. 
![gitpod-components](https://user-images.githubusercontent.com/119957/117504710-e63e0200-af50-11eb-950c-16f80faee725.png)

**Comment by cyrilcros** [comment]
I feel the problem is that there is a lot of low level access you get (root / Docker usage) which entails a lot of fiddling with the nodes. That trigger issues when you stray from the gitpod devs' set up (Ubuntu 18.04, Kubernetes support is fine).
Check the thread I am linking for example, this comment also has the link to the platform support matrix I mention: https://github.com/gitpod-io/gitpod/issues/2994#issuecomment-818515595
The devs haven't answered here yet, BUT the fact the very last commit attempts to fix the issue I linked is a really good sign that they are aware of those issues: https://github.com/gitpod-io/gitpod/commit/44a47ef48e5edd0d4b239138fb6ff9fb949c67bd

**Comment by ghuntley** [comment]
👋 @cyrilcros and @flickerfly.

There's some mighty fine suggestions right there and some of them have been incorporated into the recent v0.10.0 release. Let's keep this issue open until more of your suggestions are implemented. If you would like to help out with contribution then 🧡 let me know how I can help.

ICYMI some of the improvements shipped over the last two weeks:
- [generating technical support bundles](https://community.gitpod.io/t/gitpod-self-hosted-support-bundle/4353)
- [docs navigation improvements and new helm/eks guides](https://www.gitpod.io/docs/self-hosted/latest/installation).

**Comment by ghuntley** [comment]
Requirements were documented last night at https://www.gitpod.io/docs/self-hosted/latest/requirements

**Comment by ghuntley** [comment]
ps: @cyrilcros and @flickerfly - come join www.gitpod.io/chat in the #gitpod-self-hosted room.

**Comment by jgallucci32** [comment]
I have 0.10.0 running on Ubuntu 20.04 with RKE 1.20.11 using containerd 1.4.9. Took some work figuring out the Helm answers but it appears to be fairly stable.

What info do you need to verify RKE 1.20.11 as a supported platform?

**Comment by jgallucci32** [comment]
@ghuntley Would you mind updating the https://www.gitpod.io/docs/self-hosted/latest/requirements page to at least mention Gitpod now works on RKE with the recommended workaround posted in the referenced Github issue comments?

We've had Gitpod 0.10.0 running now for 3+ months in production on RKE 1.21.x without issue.
