### ISSUE TITLE
[Dashboard] Add Projects Overview

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#4420]
The team landing pages should have a tab listing all the projects. 
The page should allow users to
 - create a new project
 - open one of the projects

**Comment by jankeromnes** [comment]
Hello @gtsiolis 👋 😁 I wonder -- isn't this already implemented?

**Comment by gtsiolis** [comment]
Hey @jankeromnes! The barebones are in place but we're still missing some design details like proper colors and spacing, hover states, prebuilds or branches information on the cards. Some of these also probably depend on the work in https://github.com/gitpod-io/gitpod/pull/4876. See also [relevant section](https://www.notion.so/gitpod/Teams-and-Projects-v0-2-30f5705202ac40cb884f7b428e08e381#7e7bd9de4d3a4b8691ab28fc1897a8ab) on the crew doc (internal).

> ... still missing some bit that we need to surface in the project cards related to prebuilds.

However, we could close this and open a follow up issue for updating these smaller bits. WDYT?

**Comment by jankeromnes** [comment]
Aha, thanks! I was just wondering if this was still current.

> However, we could close this and open a follow up issue for updating these smaller bits. WDYT?

No strong opinion, but I think it'd be good to have a precise checklist of what's still left to do.

If useful, I can start one based on your reply -- TODO:

- [x] barebones are in place
- [ ] align colors and spacing with spec
- [ ] implement hover states
- [ ] finalize prebuilds/branches information on the cards
