### ISSUE TITLE
Automatically detect & honor environment-as-code files

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#443]
Gitpod makes it easy to automate the setup of development environments, which is awesome.

There are other initiatives with the same goal, and it would be nice to support them, so that we can all forget about manually setting up dev environments regardless of which editor we prefer.

**Workspace & IDE**

- [x] [`.gitpod.yml`](https://www.gitpod.io/docs/41_Config_Gitpod_File/) should prebuild workspace
- [x] [`.theia/`](https://www.theia-ide.org/doc/Preferences.html) should pre-configure the IDE
- [x] [`.vscode/`](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations) should pre-configure the IDE
- [ ] [`.envrc`](https://direnv.net/) should pre-configure the environment in each directory (using [`direnv`](https://direnv.net/))

**Editor & linters**

- [x] [`.editorconfig`](https://editorconfig.org/) should pre-configure the editor
- [ ] [`.eslintrc`](https://eslint.org/docs/user-guide/configuring)
- [ ] [`.prettierrc`](https://prettier.io/docs/en/configuration.html)
- [x] [`.clang-tidy`](https://clang.llvm.org/extra/clang-tidy/)

**Languages**

- [ ] `rvm`'s [`.ruby-version`](https://rvm.io/workflow/projects#project-file-ruby-version) should pre-install the requested Ruby version
- [ ] `nvm`'s [`.nvmrc`](https://github.com/creationix/nvm#nvmrc) should pre-install the requested Node.js version
- [ ] `pyenv`'s [`.python-version`](https://github.com/pyenv/pyenv#choosing-the-python-version) should pre-install the requested Python version
- [ ] `mvn`'s `pom.xml` should pre-install the requested Java version
- [ ] `asdf`'s generic [`.tools-version`](https://asdf-vm.com/#/core-configuration?id=tool-versions) should pre-install all the requested tools

**Modules**

- [ ] `npm`'s [`package.json`](https://docs.npmjs.com/files/package.json) should pre-install node modules (also used by `yarn`)
- [ ] `pip`'s [`requirements.txt`](https://pip.pypa.io/en/stable/user_guide/#requirements-files) should pre-install pip packages
