### ISSUE TITLE
[Teams] Adjust styling of Teams menu & pages

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4471]
Follow-up to https://github.com/gitpod-io/gitpod/pull/4401

- [ ] 1. Team selector font size could be `text-sm` / `14px`: https://github.com/gitpod-io/gitpod/pull/4401#discussion_r648725143
- [ ] 2. Team selector dropdown entry title font size could be `text-sm` / `14px`: https://github.com/gitpod-io/gitpod/pull/4401#discussion_r648726069
- [x] 3. Team selector entry could be `bg-gray-100` on hover and/or when it's the currently selected team: https://github.com/gitpod-io/gitpod/pull/4401#discussion_r648727949
- [x] 4. When creating a New Team, most of the top menu should be hidden as per [the specs](https://www.figma.com/file/24YZdNs7MmS5drlZ5ZlM7r/Allow-adding-and-switching-teams-%234355): https://github.com/gitpod-io/gitpod/pull/4401#discussion_r648732024
- [x] 5. The URL to create a New Team, currently `/new-team`, could be improved: https://github.com/gitpod-io/gitpod/pull/4401#discussion_r648723829

**Comment by gtsiolis** [comment]
Updated the description and resolved items [4] and [5] which have been resolved in https://github.com/gitpod-io/gitpod/pull/4571. Thanks @jankeromnes! 🏀

**Comment by gtsiolis** [comment]
Opened follow up https://github.com/gitpod-io/gitpod/issues/5072 for point [3].

**Comment by gtsiolis** [comment]
Added https://github.com/gitpod-io/gitpod/pull/5074 to resolve points [1] and [2].
