### ISSUE TITLE
[self-hosted] Release 0.10.0

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#4710]
After we released [0.9.0](https://github.com/gitpod-io/gitpod/releases/tag/v0.9.0) with quite a delay, we plan to have a regular cadence to not let down our Self-Hosted users.

In that vein - and after the release to gitpod.io last week - we plan to quickly release 0.10.0, which should be a straight-forward "test-and-release" because there have been no bigger changes that should impact Self-Hosted.

### Test
- [x] test on k3s
- [ ] test on GCP

### Tasks
- [x] fix access to self-hosted registry: either #4711 or #4592
- [x] fix UI to show the setup page for Self-Hosted: #4764
- [x] updates docs: https://github.com/gitpod-io/website/issues/745
- [x] fix DB migration are not executed
- [x] docker credentials
  - [x] docs: add to new `values.custom.yaml` (next to minio etc.)
  - [x] docs: migration guide

/cc @corneliusludmann @solomonope

**Comment by geropl** [comment]
Dumping my personal notes here, in hope this might help whoever works on this:
 - [ ] docs:
   - [ ] "Configure Ingress": cerbot: copy'n'paste is broken
   - [ ] replace "find -exec copy broken: "find $WORKDIR/config/live -name "*.pem" -exec cp {} secrets/https-certificates \;" with
     - cp $WORKDIR/config/live/fullchain.pem secrets/https-certificates/tls.crt
     - cp $WORKDIR/config/live/privkey.pem secrets/https-certificates/tls.key
   - [ ] troubleshooting:
     - [ ] container runtime config for k3s:
        ```
        containerRuntime:
        containerd:
            socket: /var/run/k3s/containerd/containerd.sock
        nodeRoots:
            - /var/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
        ```
     - [ ] make visible in the navigation
   - [ ] migration guide:
     - [ ] make visible in navigation
     - [ ] 0.9.0 -> 0.10.0
       - mv secrets/https-certificates/fullchain.pem secrets/https-certificates/tls.crt
       - mv secrets/https-certificates/privkey.pem secrets/https-certificates/tls.key

**Comment by geropl** [comment]
Also, "Teams" introduced a minor regression with the "Setup" page [here](https://github.com/gitpod-io/gitpod/blob/e2bf23a914c8115ec6665a1602a3835c0f66b80d/components/dashboard/src/App.tsx#L62-L81): if "getTeams" is faster than "getLoggedInUser" (as it is for me) the error "not logged in" shadows the "needs setup" error code.

Both calls have to be made sequentially.

**Comment by geropl** [comment]
I'm un-assigning mysql here as we're blocked here until we decided on one of the approaches for registry (see above) and I won't be available on Monday.

**Comment by asthomasdk** [comment]
Is there an updated release date for 0.10.0?

**Comment by geropl** [comment]
@asthomasdk We plan to tackle the last issues (see top) starting tomorrow.

/cc @corneliusludmann

**Comment by asthomasdk** [comment]
Cool! 
We are keenly awaiting a working release.

**Comment by geropl** [comment]
@corneliusludmann Tested latest `main.1107` on my (existing) installation and still get this which looks like a migration error:
![image](https://user-images.githubusercontent.com/32448529/125770119-9a41e25b-9248-48fa-9951-9561a6092f53.png)

**Comment by geropl** [comment]
Found (my) db migration bug: I used a bnroken main version for testing, which had the migration order wrong, and between `helm del`etes the DB state was stored on a PV :facepalm: Now, after a `helm del` AND `kubectl delete ns gitpod`, I was able to install and setup successfully :tada: 

As present I'm now presented with this:
![image](https://user-images.githubusercontent.com/32448529/125801381-b3032332-3bf5-4815-9bfa-8bd1c1d733e4.png)

**Comment by geropl** [comment]
Ok, fixed that (see tasks above for totods).
Now: 
![image](https://user-images.githubusercontent.com/32448529/125810263-7738a260-64a1-4166-8181-49a3f50d5abf.png)

**Comment by geropl** [comment]
Ok, `helm del gitpod && helm upgrade --install...` did the trick: :heavy_check_mark:
