### ISSUE TITLE
Secret scanning

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#4737]
# overview

See [Internal discussion](https://gitpod.slack.com/archives/C01MLB7J24T/p1616593372022700?thread_ts=1616593015.021400&cid=C01MLB7J24T).

- [ ] design API token design that can be identified via regex that also has a signature checksum.
- [ ] migration between API token formats

## gitlab

- [ ] TBA

## github

- [ ] create a secret alert service which accepts webhooks from GitHub that contain the secret scanning message payload.
- [ ] TBA

# reading material

## gitlab

- https://gitlab.com/gitlab-org/security-products/analyzers/secrets/-/tree/master
- https://docs.gitlab.com/ee/user/application_security/secret_detection/

## github

1. https://docs.github.com/en/developers/overview/secret-scanning#joining-the-secret-scanning-program-on-github
2. https://github.blog/changelog/2021-03-22-the-python-package-index-is-now-a-github-secret-scanning-integrator/

# related files
