### ISSUE TITLE
Improve C++ support

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#488]
- [ ] Allow compiling / running / debugging from the IDE
  - Theia doesn't support launch configurations for C++ yet (Go, Java, and Node.js have launch configurations, but C++ only has [build configurations](https://github.com/theia-ide/theia/tree/master/packages/cpp#getting-accurate-diagnostics) for now, but no way to start a build)
- [x] Fix language server on first load
  - currently when you start a workspace, you often have to reload the IDE once to get the language server to work properly
  - EDIT: maybe this only happens with this [`clangd-8` upgrade](https://github.com/gitpod-io/workspace-images/pull/71)
- [ ] Enable the `clangd` option `--background-index` by default
  - currently, the language server will wrongly show many errors in `.h` files, because it analyzes each file separately out of context
  - Theia's C++ extension [suggests doing it](https://github.com/theia-ide/theia/tree/master/packages/cpp#getting-cross-file-references-to-work)
  - requested in [Theia's spectrum](https://spectrum.chat/theia/general/c-header-scan-and-code-completion~4a1ff142-6aec-4d9f-8d29-68b23256dca3)
  - VSCode already seems to do it by default
- [ ] Automatically generate & detect `compile_commands.json`
  - `clangd` [needs it](https://github.com/theia-ide/theia/tree/master/packages/cpp#getting-accurate-diagnostics) for accurate diagnostics
  - VSCode's C++ extension already seems to [auto-detect it](https://devblogs.microsoft.com/cppblog/visual-studio-code-cc-extension-june-2018-update/)
  - Auto-generating it implies calling `cmake` with `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`
- [x] Automatically enable `clang-tidy` linting
  - https://github.com/theia-ide/theia/commit/29299e45c78d0ba0f74195506f76ce9af7bf33e1 auto-detects `.clang-tidy` configuration files to enable `clang-tidy` diagnostics in `clangd 9+`.

Maybe these items can be solved by switching from Theia's C++ extension to VSCode's.

**Comment by Kreyren** [comment]
Is there anything required for linux backend in this?

Could be resolved in https://github.com/gitpod-io/workspace-images/pull/204
