### ISSUE TITLE
Produce linux-arm64 binaries for local-companion-app

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#5320]
Hi, currently I'm using ~~Ubuntu Focal Fossa~~ ArchLinuxARM in an arm64 device. And I can run vscode natively since they support the arm64 architecture officially as well. It would be great if gitpod would produce the `local-companion` binaries for arm64 architecture too.
Thanks. 

## Tasks
- [x] merge https://github.com/gitpod-io/gitpod/pull/6065 and deploy server
- [x] update Gitpod extension: https://github.com/gitpod-io/openvscode-server/pull/135
- [x] update docs: https://github.com/gitpod-io/website/pull/1048

**Comment by axonasif** [comment]
As mentioned in https://github.com/gitpod-io/gitpod/issues/5712#issuecomment-925507834, I could compile `local-app` component for arm64 architecture with the following command:
```bash
GOOS=linux GOARCH=arm64 go build -ldflags "-s -w"
```
This would mean to support the RaspberryPi and other ARM based devices if Gitpod would provide binaries for the arm64 architecture officially :smiley: 

I can download VSCODE for arm64 from this official link: https://code.visualstudio.com/sha/download?build=stable&os=linux-arm64

**Comment by akosyakov** [comment]
@axonasif PRs are welcomed as well!

**Comment by axonasif** [comment]
> @axonasif PRs are welcomed as well!

Sure thing! Although I'm not sure what's responsible for producing the binaries and pushing them to `gitpod.io/static/bin` as in the blog post: https://www.gitpod.io/blog/local-app#installation

https://github.com/gitpod-io/website/tree/main/static seems to be it but not exactly 😅

**Comment by akosyakov** [comment]
Apps are compiled with: https://github.com/gitpod-io/gitpod/blob/main/components/local-app/BUILD.yaml
Published with: https://github.com/gitpod-io/gitpod/blob/d54282c8ed59dd5b48373253bd6f26685cff9ec1/components/dashboard/leeway.Dockerfile#L19-L21

**Comment by akosyakov** [comment]
We don't have capacity to handle it right now. Let's try in a week or 2.

**Comment by jldec** [comment]
+1 to add the MacOS arm64 build as well.  
"Open in VS Code" with an M1 Mac currently fails because the default darwin binary is compiled for x86.

```
[9/29/2021, 11:13:53 PM] open workspace window: vscode://gitpod.gitpod-desktop/workspace/shortscale-rs?...
[9/29/2021, 11:13:53 PM] acquiring lock: gitpod.io
[9/29/2021, 11:13:53 PM] acquired lock: gitpod.io
[9/29/2021, 11:13:53 PM] fetching the local app from https://gitpod.io/static/bin/gitpod-local-companion-darwin
[9/29/2021, 11:13:53 PM] installing the local app to /var/folders/...
[9/29/2021, 11:13:54 PM] installing the local app: {
  "path": "/var/folders/...",
  "etag": "\"r07p8pa0kuo\""
}
[9/29/2021, 11:13:54 PM] starting the local app with the config: {
  "gitpodHost": "https://gitpod.io",
  "configFile": "file:///var/folders/...",
  "apiPort": 63953
}
[9/29/2021, 11:13:54 PM] failed to start the local app: Error: spawn Unknown system error -86
[9/29/2021, 11:13:54 PM] released lock: gitpod.io
[9/29/2021, 11:13:54 PM] failed to open uri: Error: spawn Unknown system error -86
```

**Comment by axonasif** [comment]
@akosyakov I was wondering about where is the source code of [gitpod.gitpod-desktop](https://marketplace.visualstudio.com/items?itemName=gitpod.gitpod-desktop) hosted at. Any hints or is it not public yet?
Thanks.

**Comment by akosyakov** [comment]
@axonasif please update Gitpod extension in local VS Code and try again, it should wokr now

Thanks to @iQQBot
