### ISSUE TITLE
Add loading indicator when fetching branches and prebuilds

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5351]
### Problem to solve

Loading Branches and Prebuilds for a project can still take a while for active projects, see https://github.com/gitpod-io/gitpod/issues/5038.

### Proposal

Until there's a better way to resolve these perfomance issues, we could introduce a loading indicator when fetching branches and prebuilds to improve the user experience.

This could use the loading indicator being introduced in https://github.com/gitpod-io/gitpod/pull/5236, see [relevant diff](https://github.com/gitpod-io/gitpod/pull/5236/files#diff-f4b8adb02a103d42c0de94bec0d32a6179440371ee01c21336a2181fcfa3a66dR15-R16). ⚫ 

| Branches | Prebuilds | 
|-|-|
| <img width="1440" alt="Bracnhes" src="https://user-images.githubusercontent.com/120486/130610683-558f95b8-37b3-4c95-8e3b-7b3ad5a6d581.png"> | <img width="1440" alt="Prebuilds" src="https://user-images.githubusercontent.com/120486/130610687-20802c95-0427-4d4d-af89-fb18f3c46b51.png"> |

**Comment by atduarte** [comment]
It would be also good to do something similar in the prebuild page, as it starts with an "unknown prebuild" title

![image](https://user-images.githubusercontent.com/666176/130779275-b0696b98-b869-4b77-8288-e67166765162.png)

**Comment by gtsiolis** [comment]
@jankeromnes since you added the loading indicator on the _Branches_ page in https://github.com/gitpod-io/gitpod/pull/5809, do you think it makes sense to do the same for the _Prebuilds_ page as it could be slightly slow to fetch prebuilds for active proejcts. For example, see https://gitpod.io/t/gitpod/gitpod/prebuilds. ❓

**Comment by gtsiolis** [comment]
Looping in @jldec for visibility.

**Comment by jankeromnes** [comment]
Yes 👍 happy to add these.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5351#issuecomment-982607142):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jankeromnes** [comment]
> /schedule

Woohoo! Rock'n'roll 😎

**Comment by jankeromnes** [comment]
TODO:

- [x] Loading indicator for _Branches_
- [ ] Loading indicator for _Prebuilds_
- [ ] Loading indicator for _Prebuild_

Could also be worth it:

- Loading indicator for _Projects_ (to avoid the single-reshuffle of all projects when the latest prebuilds are fetched)

**Comment by gtsiolis** [comment]
> Loading indicator for Projects

Yes, this was also briefly mentioned in a past meta team meeting.

A loading indicator could be a good MVC but a skeleton loader could be even better for the Projects and Prebuild pages due to page structure.
