### ISSUE TITLE
[code] independent deployment of VS Code

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5565]
It at least should be possible if we don't have any server API changes in components used by supervisor, cli or VS Code like Gitpod Server.

I think we will need help of @gitpod-io/engineering-meta since it is mostly config map changes of the server, blobserve.

**Comment by csweichel** [comment]
This points towards having "composite" component configurations where the config reloads automatically, e.g.
- [ ] server, where the IDE config comes from a separate configMap that hot-reloads
- [ ] blobserve needs to hot-reload its entire configuration
- [ ] registry-facade already does that

In addition we need to find a means to deploy local app independently of the dashboard. Possible paths forward are:
- serve local-app from a GCP bucket,
- serve local-app from a separate service within a meta cluster (e.g. Caddy)

**Comment by JanKoehnlein** [comment]
To unbock team IDE with JetBrains integration, the first step is changing the config in server.

/schedule

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5565#issuecomment-915029296):

>To unbock team IDE with JetBrains integration, the first step is changing the config in server.
>
>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
FYI: we have a similar mechanism in place for "chargebee config": https://github.com/gitpod-io/gitpod/blob/267448b4b07b731ab96f949f62597fd426fce305/components/server/src/config.ts#L171-L205

**Comment by akosyakov** [comment]
> To unbock team IDE with JetBrains integration, the first step is changing the config in server.

It is not JetBrains integration, but able to release latest VS Code independent from server. 😉

**Comment by akosyakov** [comment]
> server, where the IDE config comes from a separate configMap that hot-reloads

@meysholdt Does hot reload without server restart work for you?

**Comment by meysholdt** [comment]
> config reloads automatically

❤️ 

> means to deploy local app independently of the dashboard

I strongly recommend the "serve local-app from a separate service within a meta cluster" suggestion, because this fits well with deploying Kubernetes applications: Deploy by applying yaml to a clusters. 

Deploying to a GCP bucket leads to all kinds of question that better be avoided: rollback? cleanup? deploy gitpod-self-hosted? If a GCP bucket really is needed, it may be the cleanest solution to deploy a pod to k8s that ensures the bucket contains the desired file and also takes care of cleaning the bucket.

> Does hot reload without server restart work for you? 

This morning it did not and I filed https://github.com/gitpod-io/gitpod/issues/5584. @geropl fixed this in https://github.com/gitpod-io/gitpod/pull/5604.

**Comment by akosyakov** [comment]
I extracted remaining tasks in https://github.com/gitpod-io/gitpod/issues/5681 and https://github.com/gitpod-io/gitpod/issues/5680
