### ISSUE TITLE
Checkout Page not reachable

### ISSUE THREAD

**Issue by phimae** [gitpod-io/gitpod#5737]
A user [reported](https://gitpod.slack.com/archives/C01KLC52R0D/p1631720743000300) the following:

"_tried to renew my subscription with gitpod but the system blocks me, and
doesnot lead me to the checkout page._"

We should check if that is a bug to be sure not more users will be affected

**Comment by JanKoehnlein** [comment]
/schedule

Check the basic flow. In parallel it would be great to get more information form the user: What exactly they did and what UI response from Gitpod they get

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5737#issuecomment-922711395):

>/schedule
>
>Check the basic flow. In parallel it would be great to get more information form the user: What exactly they did and what UI response from Gitpod they get
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
@geropl and I started investigating the issue yesterday. We checked the activities of this user on Chargebee and in the logs: the user tried to pay on 21 July but the credit card failed due to insufficient funds. Since this was never paid, when the user tried to upgrade their account again, Chargebee rejected it and responded with an error, thus blocking the user from continuing with checkout. In our [logs](https://console.cloud.google.com/logs/query;query=resource.labels.container_name%3D%22server%22%0AjsonPayload.context.userId%3D%2286b69fed-d68b-4606-a77e-e1c542c940b9%22%0A%0AjsonPayload.message%3D%22Checkout%20page%20error%22;timeRange=2021-09-15T07:27:46.146Z%2F2021-09-17T08:27:46.146Z;cursorTimestamp=2021-09-15T15:45:56.928Z?project=gitpod-191109&folder=true&organizationId=327752801919&query=%0A), the message is "Checkout page error".  
We also further checked in the logs how often this error happens. In the past 14 days it only happened to this user.

Proposed solutions:
- [ ] Write off the outstanding invoice for the user, to unblock them from upgrading.  
- [ ] Show an alert in the frontend if this happens.
- [ ] Contact Chargebee to avoid this happening again in the future. Ideally these checkout errors should be handled by them, and not thrown to us without our knowledge.

@geropl Please correct or add to this comment where needed 🙏🏼

**Comment by phimae** [comment]
Thanks for the fix, Laurie! I think this would be @ChristinFrohne. I will respond to the respective slack thread

**Comment by laushinka** [comment]
After discussing with @geropl, once @ChristinFrohne informs the user, we can close this ticket. The decision is due to the following considerations: 1) This is a rare case, 2) The task of sending a response to the frontend is currently not testable due to [not being able to run a Chargebee test environment](https://gitpod.slack.com/archives/C01KGM9EBD4/p1632229699201500). 
New issues will be created to follow up.
