### ISSUE TITLE
In-workspace onboarding v2

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#5964]
In https://github.com/gitpod-io/openvscode-server/pull/110, we released v1 of the in-workspace onboarding.

As a follow-up, here are some ideas.

## Change the look & feel to match what VS Code does

<details>
  <summary>Screenshot</summary>
    <img src="https://user-images.githubusercontent.com/788827/135488091-75218bcf-c07e-49b3-bea6-4de90a41b324.png" />
</details>

In particular, use each step's `description` to provide the content. Note, this is very limited in terms of content length compared to the Markdown files we currently use.
As the content on the right, we'd use an image to explain each step.

## Provide more dynamic onboarding

We could use a step's `when` clause to provide onboarding steps that are tailored to a given project. For example, if we detect that a project does not have prebuilds configured, we could provide a button to automatically enable prebuilds whereas someone who already uses prebuilds doesn't need to see that.

**Comment by JohannesLandgraf** [comment]
Excellent work with v1 @mikenikles! I really like the tone of it. Some small suggestions for improvement: 

- [ ] At the end of each section add a 'Next button' to move e.g. from 'What is Gitpod?' to 'Prebuilds do the heavy lifting'
- [ ] For the CTAs (click here for e.g. the docker command, open ports) kumquat coloured buttons will work better
- [ ] Describe in 'Full access to a terminal' the shortcut how to open one (or let the button ^ do all the work)
- [ ] Include a button at the VS Code Desktop Support that does the same as Gitpod: Open in VS Code

**Comment by JohannesLandgraf** [comment]
And another thing: I think the Get Started with Gitpod onboarding flow should replace the Welcome Tab (or open as the primary one next to the Welcome one)

**Comment by filiptronicek** [comment]
> * [ ]  Include a button at the VS Code Desktop Support that does the same as Gitpod: Open in VS Code

Would be great to fit a <kbd>Open in VS Code: Insiders</kbd> there, too!

**Comment by mikenikles** [comment]
_At the end of each section add a 'Next button' to move e.g. from 'What is Gitpod?' to 'Prebuilds do the heavy lifting'_
There isn't an API at the moment to do that, I wanted to add that in v1.

_For the CTAs (click here for e.g. the docker command, open ports) kumquat coloured buttons will work better_
👍 Will see what I can do here in terms of styling. Possibly inline CSS may do the trick.

_Describe in 'Full access to a terminal' the shortcut how to open one (or let the button ^ do all the work)_
👍. We have to consider operating-system dependent shortcuts. Will see what we can do.

_Include a button at the VS Code Desktop Support that does the same as Gitpod: Open in VS Code_
That's already there if you click either of the links, unless I misunderstand what you're looking for.

_Get Started with Gitpod onboarding flow should replace the Welcome Tab_
Wouldn't that be lovely 😄. I haven't seen a way to do that without modifying core VS Code source.

**Comment by JohannesLandgraf** [comment]
> That's already there if you click either of the links, unless I misunderstand what you're looking for.
What I meant is having a real button :)

**Comment by filiptronicek** [comment]
I believe this should still be open, it's still a good idea to update the onboarding exp

**Comment by mikenikles** [comment]
Thanks Filip. Yes Anton, that sounds like a sensible approach.
