### ISSUE TITLE
Replace hard-coded gitpod.io links with envvar-driven links

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6400]
I have found a couple of links in the dashboard which have a hard-coded reference to "gitpod.io". These should be replaced to use the `GITPOD_DOMAIN` envvar supplied at runtime - this will give self-hosted users a fully native experience.

- [ ] [Dashboard workspaces](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/workspaces/Workspaces.tsx#L208)
- [ ] [Dashboard start workspace](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/workspaces/StartWorkspaceModal.tsx#L62)
- [ ] there may be others, which I can help track down when this ticket is picked

![image](https://user-images.githubusercontent.com/275848/138862517-d12d38a0-265c-41d0-8f05-0e2ab09cd3d0.png)

Links to documentation should not be changed.

**Comment by MrSimonEmms** [comment]
I've found one more URL with a hard-coded gitpod.io

https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/start/CreateWorkspace.tsx#L116

**Comment by iQQBot** [comment]
Aha, lost it

**Comment by MrSimonEmms** [comment]
@iQQBot don't fret, it happens
