### ISSUE TITLE
Test Plan #6433

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6502]
PR: https://github.com/gitpod-io/gitpod/pull/6433

# Areas to cover
 - [x] typeorm/DB
   - [x] check `db-sync` logs
   - [x] check `server` logs
   - [x] check `ws-manager-bridge` logs
   - [x] ~check DB slow logs~ slow logs are not enabled in staging. CPU usage patterns after/before deployment look good, though
   - [x] check common queries with `EXPLAIN` to see if indexes are being hit
 - [x] licensor
   - [x] create/install/validate (maybe re-use old testsuite?)
 - [x] server/express
   - [x] signup/login/logout
   - [x] cookie handling
 - [ ] GitHub app & prebuild
   - [x] start prebuild (@jldec already tested in the weekend)
   - [ ] check if failing prebuilds end up as `error`
   - [x] `/new`: see that GH lists repositories as expected

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6502#issuecomment-957266597):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6502#issuecomment-957267150):

>/schedule
>
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
Turns out our the [commit](https://github.com/gitpod-io/gitpod/compare/592ba9808b7d7bd916670d20b97805ed8f02cfa5...7abe78c91792c18b0c22103c890b25ea3a4cdf05) broke migrations: https://werft.gitpod-io-dev.com/job/ops-build-main.465

Which we did not notice because we have a broken window for quite some time: https://werft.gitpod-io-dev.com/job/ops-build-main.464 :see_no_evil:

**Comment by corneliusludmann** [comment]
When I try to change preferences (e.g. I try to tick the “Use Desktop IDE” checkbox), nothing happens besides this error message in the console:

```
Uncaught (in promise) Error: Request updateLoggedInUser failed with message: Cannot query across one-to-many for property identities
    at main.js:449
```

([internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1635936210198600))

**Comment by geropl** [comment]
Now that the change is deployed to staging `db-sync` is crashlooping. Will prepare a fix.

**Comment by geropl** [comment]
Currently blocked by failing staging deployments: https://gitpod.slack.com/archives/C01KGM9EBD4/p1635954840148800

**Comment by laushinka** [comment]
Re cookies:
Unlogged-in visitors to `https://www.gitpod.io/` get `ajs_anonymous_id` and `gitpod-marketing-website-visited` cookies.
Logged-in users get `gitpod-user`, `_gitpod_io_`, and `GCLB`.
