### ISSUE TITLE
Cleanup teams and projects when an account is deleted

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6655]
Users are [reporting](https://app.frontapp.com/open/cnv_igbm1ze) not being able to create projects after deleting (and recreating) their Gitpod account.

The New Project repo list will show "already taken" for projects left behind in deleted accounts 

This happens because projects under deleted accounts were not cleaned up, preventing re-use of the repositories in those orphan projects.

### To Reproduce

- Delete an account which has an existing/working Project.
- Try to create a new Project (under a different account) using the same repo.
- Observe "already taken" for that repo.

### Expected Behavior when deleting an account

- [x] Projects under the User account should be deleted
- [x] Teams, and the projects under them, exclusively held by the account should be deleted
- [x] Teams which also have a another owner, should not be deleted

**Comment by laushinka** [comment]
@jldec I can reproduce. Did we give them a quick fix yet? (The Front link didn't redirect to the specific issue). If not we can mark the projects they need as deleted in the DB as a quick fix.

**Comment by roboquat** [comment]
@laushinka: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6655#issuecomment-966196795):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
> * Deleting an account should delete any projects exclusively held by the account
> * Projects in teams which also have a another owner, should not be deleted

@jldec Should the teams that they are a sole owner in, also be deleted?

**Comment by laushinka** [comment]
@jldec The issue talks about what happens to projects when an account is deleted, but teams are also affected, and when a team is deleted, so are the projects. How about we update this issue to be about what happens to teams and projects when an account is deleted?

**Comment by jldec** [comment]
@laushinka - good suggestion - thank you!
I have updated the issue title and description.
