### ISSUE TITLE
Revisit use of GitHub Marketplace and GitHub Student Developer Pack

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6673]
https://github.com/marketplace/gitpod-io
https://education.github.com/pack/

- [ ] Correct copy for Personal plan (remove references to private repos)
- [ ] Correct copy and icon for Student pack 
- [x] #5702
- [x] #6531
- [ ] Handle paid plans through Gitpod dashboard

*screenshots Nov 11, 2021*

![Screenshot 2021-11-11 at 19 33 15](https://user-images.githubusercontent.com/849592/141357985-161fef44-ab33-4472-b38d-de0249cb84a2.png)

![Screenshot 2021-11-11 at 19 26 51](https://user-images.githubusercontent.com/849592/141358034-f20b8ba5-7dc2-4fd4-a507-21a3c70bb96b.png)

**Comment by jldec** [comment]
Closing in favor of #14025
