### ISSUE TITLE
Epic: Allow user to configure preferred IDE configurations as part of onboarding

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6707]
**Goal/Intended Outcome** 

Users are aware of JetBrains IDE’s when they first use Gitpod so that if they are a regular JetBrains user they can configure all future workspaces to use JetBrains. 

**Proposal**
- Introduce a prompt for onboarding users (e.g. first workspace start)
- Present users with the current alternative IDE (JetBrains, etc) options, but also allow to dismiss
- If possible, we can directly update the preferences (or alternatively routing to the preferences page)
- On subsequent workspace starts we revert to the existing flow / respect existing preferences

**Consideration(s)**
- Embedding of logo's might help user perception (but not mandatory as part of the design)
- We should see this work as iterative, implement an experiment, and we can adapt/alter based on the results

**Measurement ([Experiment Dashboard](https://eu.mixpanel.com/project/2482401/view/3024765/app/dashboards#id=3173296))**

- Increased conversion rate through the onboarding funnel
- Increase in retention for users who are more likely to use JetBrains as a daily driver
- Increased general adoption of the JetBrains feature

**Note:** Some dropoff to be expected by adding additional friction/step into the onboarding flow. 

**Out of scope**
- VS Code Desktop (unless v.easy)
- Vim / SSH flows
- Implementing as A/B test

**Issues**
- [x] https://github.com/gitpod-io/gitpod/issues/9433
- [x] https://github.com/gitpod-io/gitpod/issues/9534
- [x] https://github.com/gitpod-io/gitpod/issues/9791
- [x] https://github.com/gitpod-io/gitpod/issues/9790
- [x] https://github.com/gitpod-io/gitpod/issues/9792

~~https://github.com/gitpod-io/gitpod/issues/9520~~

See Figma [[1](https://www.figma.com/file/1ofpgCa3XI0F4zZKhcgiGg/%236707?node-id=0%3A1)]

**Comment by svenefftinge** [comment]
I think generally it could make sense to ask the user when we detect certain IDE metafiles (e.g. `.idea`) in a project.
Including the "Don't ask me again for this project" or even "Don't ask me again for similar projects".
We can surface these settings in the user preferences so users could manage them there.

**Comment by loujaybee** [comment]
Moving this under JetBrains, removing epic label for now.

**Comment by andreafalzetti** [comment]
Shall we consider this Epic as complete? cc @loujaybee

**Comment by loujaybee** [comment]
Thanks @andreafalzetti, yeah we were just monitoring some data. Gitpod now asks for preferred IDE for users who have not selected a default, after this point users can then change the selection freely from user preferences. 

<img width="698" alt="image" src="https://user-images.githubusercontent.com/5528307/180431008-5f603c3a-e727-40f2-921f-3c045127afdf.png">
