### ISSUE TITLE
[deployment] First steps towards automatic deployment of the meta cluster

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#6785]
The steps we currently take to deploy meta are rather dull, and could as well be automated. I think the main reasons why we don't do that yet are
- We are afraid we are breaking something without being aware.
- We are unsure when and how to roll back.

Eventually, we'd like to reach automatic gradual deployments with automatic rollback ([internal doc](https://www.notion.so/gitpod/Gradual-Meta-Deployments-81af0d28c6ec4047b4f2f07dddb408ec)). But that is not necessarily a pre-requisite for automatic deployments.  There are a few steps that we can already take towards that goal

I propose to do this
- [ ] Gather the really most useful information in the meta dashboard
- [ ] Implement alerts on the most prominent failures, e.g. workspaces not starting
- [ ] Investigate and document the fastest way to roll a buggy deployment back in Argo

**Comment by jankeromnes** [comment]
Great idea! 💯 I'd love to see frequent & automated meta deployments (and one key benefit to me is that this will guarantee truly seamless, reliable and small deployments).

> with automatic rollback

> Investigate and document the fastest way to roll a buggy deployment back in Argo

A few nuances I felt like adding here:

- I don't know if it's possible to have 100% automatic rollback in case of trouble: When things go wrong, perhaps we'll always need at least _some_ manual assessment / intervention

- Also, if we deploy 10 commits, and we know for sure that 1 of them is causing problems, it's a much shorter and safer path to "roll back" 1 commit (i.e. revert the bad commit and redeploy) than to "roll back" 10 commits (i.e. redeploy the older build, which is not always easy or possible, then worry about a fix, then deploy an even bigger set of commits). I'm a big believe in "revert and redeploy", because it's generally faster, safer, simpler, and doable by almost anyone (because you don't need to fully understand and resolve the bug in order to fix it)

**Comment by geropl** [comment]
Make sense to gather this information

> Gather the really most useful information in the meta dashboard

Yes. To achieve that it might make sense to move some things out of the current one. Currently we're mixing top-level service indicators (e.g. API request success rate) with per-pod metrics. IMO it make sense to move those into a separate dashboard.

List of outcomes:
 - clean Meta Overview dashboard
 - clean Meta Service Pods dashboard
 - alerts, esp. for supporting deployments
 - notion template incl. links to docs for "how to roll back", "how to smoke test" etc.

> I don't know if it's possible to have 100% automatic rollback in case of trouble

This is not in scope for this issue. Regarding the technical details please read (and comment!) on the RFC: https://www.notion.so/gitpod/Gradual-Meta-Deployments-81af0d28c6ec4047b4f2f07dddb408ec :pray:

**Comment by laushinka** [comment]
After discussion with @geropl, the tasks for this issue:

- [ ] Create an issue to create an alert for workspace failure rates, assigned to the Workspace team.

- Changes to the overview: 
- [ ] Create sections in our Grafana overview e.g. general and external (workspace)
- [ ] Create a Grafana panel under the external dashboard for the workspace failure rate.  
- [] Edit websocket by clientType
- [] Add API Request error rate 
- [] Remove container image, cpu, memory, network (go into dashboard for pod health or services health),
- [] Add messagebus pod status, cpu, memory, network under a sub-section

- Pod-specific dashboard:
- [ ] Create a separate dashboard for pod-specific views

**Comment by geropl** [comment]
Here a quick summary of outcomes that we deem separate from this issue but still come up during our work:

Meta Overview:
 - [ ] add DB CPU graphs (source: gcloud) (platform issue: https://github.com/gitpod-io/observability/issues/31)
 - [ ] API response times (+ on server dashboard!) (source: add prometheus metric)

Meta Services:
 - [ ] add graphs for log rates (error/warn/info) (source: either gcloud, or we instrument our logging to emit prometheus data)

Alerts relevant for automatic deployments (for most of those we already have alerts somewhere):
 - workspace startup error rates
 - log error rate per service
 - API error rate
 - API response times
 - DB CPU usage
 - websocket connection rate (open/close)

**Comment by geropl** [comment]
Last pieces:
 - [Rollback notes](https://www.notion.so/gitpod/How-to-Rollback-Meta-Deployments-5321dfb659a24259b950e106b8ead821) (to be verified/proof read)
 - extended [deployment template](https://www.notion.so/gitpod/Meta-Deployment-Log-7ec4a522d6bb4e72ba30477d3904ff67) with:
    - hint to how-to-rollback
    - post deployment checks for metrics
