### ISSUE TITLE
[db] Maintenance: missing indexes

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6807]
Recent DB CPU spikes turned up more missing indexes:

- [x] https://console.cloud.google.com/logs/query;cursorTimestamp=2021-11-19T13:55:35.697582Z;query=logName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcloudsql.googleapis.com%252Fmysql-slow.log%22%0Atimestamp%3D%222021-11-19T13:47:29.620270Z%22%0AinsertId%3D%222%23583386024174%23979887871142546947%23slow%231637329649620270000%230000000000102e5a-0-0@a1%22?project=gitpod-191109
```
EXPLAIN SELECT ws.id AS id,
ws.ownerId AS ownerId,
ws.softDeleted as softDeleted
FROM d_b_workspace AS ws
WHERE ws.deleted = 0
AND ws.contentDeletedTime = ''
AND ws.softDeleted IS NOT NULL
AND (
ws.softDeletedTime < NOW() - INTERVAL 21 DAY
OR ws.softDeletedTime = ''
)
AND ws.ownerId <> 'builtin-user-workspace-probe-0000000'
LIMIT 1000;
```
   - [x] https://console.cloud.google.com/logs/query;cursorTimestamp=2021-11-19T13:47:29.620270Z;query=logName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcloudsql.googleapis.com%252Fmysql-slow.log%22%0Atimestamp%3D%222021-11-19T13:47:16.228882Z%22%0AinsertId%3D%222%23583386024174%23979887871142546947%23slow%231637329636228882000%230000000000102ac1-0-0@a1%22?project=gitpod-191109
```
EXPLAIN SELECT ws.id AS id,
ws.ownerId AS ownerId
FROM d_b_workspace AS ws,
d_b_prebuilt_workspace AS pb
LEFT OUTER JOIN d_b_workspace AS usages ON usages.basedOnPrebuildId = pb.id
WHERE pb.buildworkspaceId = ws.id
AND ws.contentDeletedTime = ''
AND ws.pinned = 0
AND ws.creationTime < NOW() - INTERVAL 7 DAY
GROUP BY ws.id, ws.ownerId
HAVING
max(usages.creationTime) IS NULL or max(usages.creationTime) < NOW() - INTERVAL 7 DAY
LIMIT 1000;
```
 - [x] token entry: https://console.cloud.google.com/logs/query;cursorTimestamp=2021-11-19T13:43:38.061478Z;query=logName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcloudsql.googleapis.com%252Fmysql-slow.log%22%0Atimestamp%3D%222021-11-19T13:42:13.492218Z%22%0AinsertId%3D%222%23583386024174%23979887871142546947%23slow%231637329333492218000%2300000000000ff8e8-0-0@a1%22?project=gitpod-191109
```
EXPLAIN UPDATE d_b_token_entry AS te
SET te.deleted = TRUE
WHERE te.expiryDate != ''
AND te.refreshable != 1
AND te.expiryDate <= '...';
```
 - [x] prebuild workspaces / projectId:
    - Slow log: https://console.cloud.google.com/logs/query;cursorTimestamp=2021-11-19T13:33:32.157296Z;query=logName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcloudsql.googleapis.com%252Fmysql-slow.log%22%0Atimestamp%3D%222021-11-19T13:33:32.157296Z%22%0AinsertId%3D%222%23583386024174%23979887871142546947%23slow%231637328812157296000%2300000000000fdb74-0-0@a1%22?project=gitpod-191109

      Query:
```
EXPLAIN SELECT pws.*, ws.*
   FROM `d_b_prebuilt_workspace` `pws`
      INNER JOIN `d_b_workspace` `ws`
         ON `pws`.`buildWorkspaceId` = `ws`.`id`
   WHERE `pws`.`projectId` = '...'
   ORDER BY `pws`.`creationTime` DESC LIMIT 1;
```
 - [x] subscription: teamSubscriptionSlotId:
```
EXPLAIN SELECT subscription.*
    FROM `d_b_subscription` `subscription`
    WHERE `subscription`.`teamSubscriptionSlotId` = '...' AND `subscription`.`deleted` != true AND `subscription`.`planId` != "free"
    ORDER BY `subscription`.`startDate` DESC;
```
