### ISSUE TITLE
[cleanup] Look into deprecating GraphQL

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#7051]
For some time now we have had a graphql endpoint at https://gitpod.io/api/graphql

As we (Team Meta) are not aware of any clients, we'd like to remove it because:
 - maintenance burden
 - amount of (outdated) dependencies
 - potential for creating security issues because  we do not have it on our "radar" when making code changes
 - is not document or advertised anywhere
 - paves the way for a more unified, coherent API (re-)implementation

(The GraphQL implementation will stay in the repo's history, of course, and gets a git tag for easier lookup.)

**Comment by geropl** [comment]
Steps: 
 - [ ] identify clients (none?)
 - [ ] come up with strategies to migrate
 - [ ] remove/block `/graphql` route (brownout)
 - [ ] finally remove the implementation from our code.

**Comment by geropl** [comment]
- clients: a single self-hsoted client uses it for monitoring. Is still on an older version, so removal will not affect immediately. The goal is to offer an equivalent API as soon as they catch up.
 - migration: see above. We plan to offer a public API that has the same features
 - removal: here's the PR: https://github.com/gitpod-io/gitpod/pull/7504
