### ISSUE TITLE
Epic: Implement SSH gateway (JetBrains)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7183]
Currently the Gitpod JetBrains integration is using the Code With Me service as an interim solution, this epic contains all work to remove the Code With Me interim solution, and to implement an entirely Gitpod owned flow. 

**Remaining work**
- [x] Workspace team to deploy SSH gateway
- [x] Meta team to deploy new version of the Gitpod server
- [x] Anton to finish UI for connection handling and gateway plugin
- [ ] Document approach for local development/testing/review of the gateway plugin
- [x] Publish gateway plugin to the JetBrains marketplace
- [x] JetBrains to release gateway with Gitpod plugin (@akosyakov to speak with JetBrains about how this process might work)

Also see duplicate issue comments/details [[1](https://github.com/gitpod-io/gitpod/issues/5644)]

**Comment by loujaybee** [comment]
Hey @svenefftinge not sure if you intended to update the title, but we're juggling a couple of different epics for JetBrains e.g. https://github.com/gitpod-io/gitpod/issues/7332 happy to update, but this one was to signify the Gitpod->JetBrains user experience, not sure if a better title makes sense. CC: @akosyakov 🙏

**Comment by svenefftinge** [comment]
I wanted to have something clearer for the roadmap. Sorry if that changed the intent too much. 
Can you make sure there is an item on the roadmap that reflects the Epic for Jetbrains integration being GA?

**Comment by loujaybee** [comment]
@svenefftinge gotcha! Yeah, we currently have an epic for GA (however it didn't have an associated GitHub issue) on the IDE page, I'll refactor some things, as this epic will likely be closed now that Code With Me is now deployed 🙏  I'll make sure JetBrains GA is represented on the roadmap 🚀

**Comment by akosyakov** [comment]
@loujaybee Can be closed?

**Comment by loujaybee** [comment]
@akosyakov yep! Just moving other issues out to the GA epic, all good to close !

🥳 🚀 congrats, folks!!

https://github.com/gitpod-io/gitpod/issues/7956
