### ISSUE TITLE
Epic: Automated Self-Hosted Testing

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#7316]
## Summary
Set up werft jobs that automatically install and test (running the [existing integration tests](https://github.com/gitpod-io/gitpod/tree/120872bfce3bbb7a7d1b3372282166745d9f9ec2/test)) Gitpod self-hosted from `main` on 4 representative infrastructure environments every night as well as manually on demand. Also the update path should be tested

## Context
Before we can publish a new Gitpod self-hosted release, we need to test the installation on all supported platforms. Doing these by hand is annoying, error-prone, and time-consuming. That's why we need to automate this. This will build our confidence in our releases, which in turn will increase trust with users and customers. 

## Value
Regular, automated tests ensure more reliable Gitpod releases, increasing our own confidence and our customer's confidence.

## Acceptance Criteria
- We have a werft job that tests the latest self-hosted from `main` and runs the existing integration tests.
- Test runs on 4 representative environments (tbc what these are, see below for first draft)
- Tests for fresh installations as well as updates from the previous version/release.
- Notifications about failed tests.

## Measurement
- Number of tests run per week.
- Number of different environments we test on on a nightly basis.

## Growth Area
- Onboarding

## Proposed Test Environments
1. AWS
2. GKE
3. AWS - airgapped
4. AWS - self-signed certs

## Milestones
- [x] Milestone 1 - MVP with a basic werft pipeline to run tests
- [x] Milestone 2 - Support all cloud providers
- [x] Milestone 3 - Additional testing dimensions
- [ ] Milestone 4: Unittests for terraform script

Full testing surface area defined [here](https://www.notion.so/gitpod/Self-Hosted-Testing-Resources-1ad123a1fb944768a1bd8ad55f611d2a#bcec048707ab442daba5fa08ff5c5b90) (internal)

**Comment by nandajavarma** [comment]
Based on the discussion I had with @corneliusludmann, I have made a very [rough note on notion](https://www.notion.so/gitpod/Automated-Test-Installations-Integration-Tests-27e072c44a404abfba10361846976173), about things we discussed during the chat and a small plan on where to start.

**Comment by lucasvaltl** [comment]
Closing this as we fulfilled the acceptance criteria - we are running nightly tests on 4 platforms :)
