### ISSUE TITLE
Epic: Simplified Multi-Meta

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#7435]
Summary:
 This is the epic for implementing "Simplified Multi-Meta" as specified in [this RFC](https://www.notion.so/gitpod/Simplified-Multi-Meta-9942f49ccfbe47b0a7e352970df13162).

Context:
 - basically summed up in [the RFC](https://www.notion.so/gitpod/Simplified-Multi-Meta-9942f49ccfbe47b0a7e352970df13162)

Value:
 - enables more Gitpod clusters (e.g., asia) without adding yet another DB
 - enables delivering multi-cluster Gitpod to Self-Hosted customers (because it reduces setup complexity)

Measurement:
 - messagebus has not cross-cluster dependency anymore
 - we got rid of `db-sync`
 - we replaced rabbitmq with a simpler pub/sub implementation (redis pub/sub)

Tasks:
 - Remove cross-cluster messagebus dependency
   - [x] ~#7436~
   - [x] make imagebuild logs independent of cluster locality #7899
   - [x] #7523
 - get rid of the multi-DB setup
   - [ ] #8271
   - [ ] Introduce time measurements for key operations (all/selected API calls)
   - [ ] Resolve cross-DB inconsistencies (AT) https://github.com/gitpod-io/gitpod/issues/7796
   - [ ] (optional, if that improves things) Use a read-through cache to improve
   - [ ] clean up unsynced DB tables
   - [ ] clean up delete jobs (saas vs. self-hosted)
 - Replace rabbitmq with Redis pub/sub
   - [ ] Replace rabbitmq with Redis pub/sub

**Comment by geropl** [comment]
Messagebus is done :heavy_check_mark: 

Closing this issue in favor of two follow-up epics:
 - https://github.com/gitpod-io/gitpod/issues/9198
 - https://github.com/gitpod-io/gitpod/issues/9097
