### ISSUE TITLE
Epic: New Workspace Input

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7554]
**Summary**
The goal of this feature is to provide users with a great experience for starting workspaces.

**Context** 
The existing "new workspace" UI has several limitations.

- It does not support opening workspaces on arbitrary repo context URLs
- It requires navigating to a workspaces list to click on the "New Workspace" button
- The modal UI feels too small and not commensurate with the importance of the New Workspace action. 

**Description**
This epic aims to fix those limitations with the following:

- [ ] A text input which supports copy-paste of git repo context URLs
- [ ] An auto-suggest completion feature offering a list of pre-fetched repos for quick selection, when users start typing the name or other text suggestive of the repo they want
- [ ] A keyboard binding to bring up the New Workspace feature from anywhere in the dashboard
- [ ] A larger, cleaner user interface

Future goals (not in scope for this epic) include

- Smarter auto-suggest based on user behavior or other inputs
- Promotion of the New Workspace page to serve as the default landing page for the dashboard
- Support for use by unauthenticated users prior to sign-up or login

**Value**
Starting workspaces is a key feature of Gitpod, and one that deserves to be as smooth and simple as possible, for both new and returning users.

**Comment by jldec** [comment]
See https://github.com/gitpod-io/gitpod/issues/3715#issuecomment-811947169 for additional UX ideas. (from @shaal)

>  GitKraken has a nice interface to open an existing repo from Github, Gitlab, etc.
> Whatever git hosting the user gave Gitpod access to, can list repos, branches and PR, directly from Gitpod UI.

> _GitKraken screenshot for opening an existing repo_
> ![image](https://user-images.githubusercontent.com/22901/113309019-bdcd4300-92d4-11eb-83f1-4da351935416.png)
