### ISSUE TITLE
Epic: Admin dashboard enhancements to avoid SQL queries for support

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7597]
**Summary**
The goal of this epic is to enable the use of the admin dashboard, to resolve support scenarios which currently require SQL queries for inspection or direct SQL manipulation of data.

**Context**
Features such as teams, or projects and prebuilds cannot currently be inspected via the admin dashboard. This makes it difficult to support users in their use of these features.

Issues with infrastructure scheduling may result in database inconsistencies which can currently only be resolved through direct SQL manipulation of the affected records. One examples of this is #7255.

**Description**

general
- [x] #6932
- [x] #8454
- [ ] Admin date/time values should show exact date/time on hover

workspaces

- [x] https://github.com/gitpod-io/gitpod/issues/8005
- [ ] force backup
- [ ] force stop when stuck in stopping state
- [ ] list recent workspace instances with times, duration, status
- [ ] link-to and show prebuild workspaces
- [x] #8453
- [ ] Show list of instances under workspace detail
- [ ] Distinguish between prebuild and other kinds of workspaces in workspaces list 

user accounts

- [x] [fix account statement to download JSON](https://github.com/gitpod-io/gitpod/issues/7583) 
- [ ] #8451
- [ ] recover account e.g. after deleting the last authorized git provider account
- [ ] list projects under a user account

projects

- [x] #7636
  - [x] show project team or owner
  - [x] show recent project prebuilds below
- [ ] delete project
- [ ] restore project
- [ ] #8452
- [ ] show project configuration

teams

- [x] #8060
  - [x] list team members and owners below
  - [x] change roles between member and admin 
 - [ ] #8523
- [ ] list projects in a team

nice to have (not in scope for this epic)

- [ ] show team activity log (changes in memberships, projects)
- [ ] report team usage (workspace hours by project, team member)

**Value**
Visibility into Gitpod feature usage is important for customers and operators to understand how users are getting value from the platform.

**Comment by geropl** [comment]
@jldec Once you're back: can you look into splitting this up in follow ups? :pray:

**Comment by jldec** [comment]
Closing this because the Epic process requires epics to end.

- scheduled #8451 as urgent support followup.
- added #8452 to Epic #9291.
- treating other tasks including #8532 as lower priority for now.

**Comment by laushinka** [comment]
> * treating other tasks including [werft/deploy/post-process: Remove openvsx statefulsetstatus #8532](https://github.com/gitpod-io/gitpod/pull/8532) as lower priority for now.

Thanks for following up, @jldec! How is #8532 related to the epic btw, is it a typo?

**Comment by jldec** [comment]
Yeah, that was a typo - thanks for noticing @laushinka
