### ISSUE TITLE
Epic: Remove need to commit to git (Gitpod "Inner Loop")

### ISSUE THREAD

**Issue by mickmister** [gitpod-io/gitpod#7671]
Improve the speed that users can iterate on their configuration, particularly their `.gitpod.yml` in a way that doesn't require them to leave gitpod and/or start other workspaces. [Doc or research progress](https://www.notion.so/gitpod/Research-Improve-Gitpod-Configuration-Loop-ef865d584cee4fbdb25f95d50d419cba).

There are some main configuration areas to improve on: 

1. `gitpod.yml` - inclusive of the task commands
2. Image: Dockerfile updates / prebuilds
3. IDE integrations 
4. Dotfiles iterations
5. Logs for feedback

Also useful to think on different dimensions: 
1. Does it lint? 
2. Does it build?
3. Does it run? (integrate)

**In scope** 
- [ ] https://github.com/gitpod-io/gitpod/issues/12208
- [x] https://github.com/gitpod-io/website/issues/3417
- [ ] https://github.com/gitpod-io/gitpod/issues/16299
- [ ] https://github.com/gitpod-io/gitpod/issues/16298
- [ ] https://github.com/gitpod-io/gitpod/issues/16480
- [ ] https://github.com/gitpod-io/gitpod/pull/16363
- [ ] https://github.com/gitpod-io/gitpod/issues/6894
- [ ] https://github.com/gitpod-io/gitpod/issues/6898
- [ ] https://github.com/gitpod-io/gitpod/issues/16335

**Nice to have** 
- https://github.com/gitpod-io/gitpod/issues/16180
- https://github.com/gitpod-io/gitpod/issues/16178

**Out of scope - Improve outer loop**
- https://github.com/gitpod-io/gitpod/issues/16264
- https://github.com/gitpod-io/gitpod/issues/16236
- https://github.com/gitpod-io/gitpod/issues/16232

**Closes**
- https://github.com/gitpod-io/gitpod/issues/1305
- https://github.com/gitpod-io/gitpod/issues/12893
- https://github.com/gitpod-io/gitpod/issues/9025
- https://github.com/gitpod-io/gitpod/issues/4860
- https://github.com/gitpod-io/gitpod/issues/6818
- https://github.com/gitpod-io/gitpod/pull/13505
- https://github.com/gitpod-io/gitpod/issues/8691
- https://github.com/gitpod-io/gitpod/issues/10701 (partially)
- https://github.com/gitpod-io/gitpod/issues/9956

**Related issues:** 
- https://github.com/gitpod-io/gitpod/issues/16485
- https://github.com/gitpod-io/website/issues/2188
- https://github.com/gitpod-io/gitpod/issues/11149
- https://github.com/gitpod-io/gitpod/issues/10701
- https://github.com/gitpod-io/gitpod/issues/11149
- https://github.com/gitpod-io/gitpod/issues/11063
- https://github.com/gitpod-io/website/issues/2368
- https://github.com/gitpod-io/gitpod/issues/13004
- https://github.com/gitpod-io/gitpod/issues/2186
- https://github.com/gitpod-io/gitpod/issues/4861

<details>
<summary>Original issue description</summary>

## Context

When I'm building a workspace, I oftentimes want to iterate on the .gitpod.yml file and test its behavior. My workflow is:

- make a change to .gitpod.yml
- commit and push change
- open gitpod through the commit's/branch's GitHub url
- now I have a workspace created from my edited .gitpod.yml file

### Problem with this approach

Two things that are inconvenient about my current workflow:

- I'm going to github as part of the workflow. I'd rather stay in gitpod while I'm iterating
- I end up with an extra workspace that I need to delete

## Possible Solution

Add a command to the gp CLI, which takes the current .gitpod.yml (and dockerfile) and starts a fresh workspace with an explicit prebuild stage (so it runs through the automation). The CLI would output the build logs (docker build, prebuild, tasks) to standard out and at the end (ready state) print a link so one can optionally go and open the IDE. 
The workspace stops when I terminate the process.

We can then have IDE commands to run this. I think a code lens in the .gitpod.yml would be even better. Also, a notification when the config has changed could be useful for users to discover this.

</details>

**Comment by svenefftinge** [comment]
@mickmister this has been discussed more on a solution side in https://github.com/gitpod-io/gitpod/issues/4861 and https://github.com/gitpod-io/gitpod/issues/6818. I like that you framed it from the problem/user perspective, so would like to use this as the driving epi. That means we are updating the initial description as we discover this.

**Comment by mickmister** [comment]
@svenefftinge It would be interesting if the workflow could match the style of docker image development, how you can iterate on a dockerfile as it caches the execution of each step. It's more difficult in the `.gitpod.yml` case, because there are multiple scripts running at once, and probably a million other things I'm not aware of that makes it difficult to cache the steps.

I haven't tried the approach of using a dockerfile to setup the Gitpod image. In what's currently available, that may provide a faster workflow of building the workspace, as you can iterate on the Dockerfile and test with the resulting Docker image, without needing to recreate the workspace on each iteration.

**Comment by loujaybee** [comment]
Moving to Q3 as the currently proposed solution for this would be dependent upon https://github.com/gitpod-io/gitpod/issues/7185, which in turn is dependent on API changes introduced in https://github.com/gitpod-io/gitpod/issues/7900 and https://github.com/gitpod-io/gitpod/issues/8512. However, if required, some simpler (non-dependent) solutions could be found for immediate pain relief here rather than doing this via a Gitpod CLI / using the Gitpod API's.

**Comment by loujaybee** [comment]
Note: There is also the related use-case of iterating/feedback loop on updating dotfiles configuration (in addition to `.gitpod.yml`, which might be solved with the same solution, but there might be some way to improve the feedback loop for dotfiles iteration. Wanted to add that use-case here, also.

**Comment by raphaeltm** [comment]
Just adding some feedback from another perspective. 

We have a custom Docker image for our workspaces where we pre-install various CLIs that we use on a bunch of projects. If I update the Docker image, to get the latest CLIs, but don't want to get rid of the files in my current workspace (which might include docker volumes with data that I still need), don't have a good path forward. To get the latest image, I need to create a new workspace. It would be really useful (in my use case) to be able to rebuild the current workspace, preserving all the files in `/workspace`. i.e. re-run the prebuild steps, and then remount `/workspace`. 

We've only just started testing GitPod in the last few weeks, so I might be missing a few things about how it works, but I think this ties in well with this issue.

**Comment by richardfrankza** [comment]
Loving the product overall, but as a newbie to gitpod customising my workspace image - it has been painfully slow to iterate and get it right. I look forward to this feature.

**Comment by jmls** [comment]
yeah, needing this asap ;)

**Comment by csweichel** [comment]
[`run-gp`](https://github.com/gitpod-io/run-gp) almost provides that - we'd just need to disable the IDE and port forwarding, and add a good means for getting feedback from the tasks.

**Comment by loujaybee** [comment]
We have begun technical investigations here and created some draft plans around this. However, I'm going to move this from Q3 currently as it's unlikely to complete in Q3, with most of our efforts going towards the JetBrains integration.

**Comment by loujaybee** [comment]
Temporarily removing @andreafalzetti as owner, will need to figure out who picks this up again in Q4.

**Comment by loujaybee** [comment]
Documentation raised w/ announcement: https://github.com/gitpod-io/website/pull/3290

**Comment by loujaybee** [comment]
Hey folks, a beta version of the `gp validate` command is now shipped, here's the announcement: 

https://www.gitpod.io/changelog/validate-gitpod-yaml-without-commit

You can find some more information of how to use the feature...

Here, in the context of configuring a workspace: https://www.gitpod.io/docs/configure/workspaces
And also here for the CLI command: https://www.gitpod.io/docs/references/gitpod-cli#validate

Feedback is tagged up against the `gp validate` label [[1](https://github.com/gitpod-io/gitpod/labels/feature%3A%20gp%20validate)], feel free to add more issues with any other feedback.

- https://github.com/gitpod-io/gitpod/issues/16557
- https://github.com/gitpod-io/gitpod/issues/16538
- https://github.com/gitpod-io/gitpod/issues/16335
- https://github.com/gitpod-io/gitpod/issues/16325
- https://github.com/gitpod-io/gitpod/issues/16180
- https://github.com/gitpod-io/gitpod/issues/16178

We can now consider this issue closed 🙏

**Comment by GitMensch** [comment]
Sorry for posting to an existing issue, but as this is linked from within the IDE to provide feedback...

First: I definitely like that, no more "create extra branch, temporarily switch default branch to that, create/adjust .gitpod.yml, restart workspace" any more!
... but:

`gp validate` currently always yields in the workspace being force-closed with a message:

> **Oh, no! Something went wrong!**
> container workspace completed; containers of a workspace pod are not supposed to do that

after "Building the workspace image..."

(tested both with the default image and with `image: gitpod/workspace-c`)

**Comment by akosyakov** [comment]
@GitMensch It sounds  like a regression. Could you create a new issue and share with which repo you can reproduce it please? I'm trying to reproduce with https://github.com/akosyakov/parcel-demo but I cannot reproduce with VS Code Browser.
