### ISSUE TITLE
Epic: Start Fresh Projects

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#7722]
New projects are usually started in a dev environment. Therefore we want to allow starting workspaces that are not connected to a remote git repository. they might be completely empty or seeded based on an archive.

- [ ] https://github.com/gitpod-io/gitpod/issues/6903
- [x] https://github.com/gitpod-io/gitpod/issues/6904
- [x] https://github.com/gitpod-io/gitpod/issues/6906

**Comment by jwpjrdev** [comment]
I wouldn't mind working on this a little. Are there any mockups for what such a menu would look like in the dashboard?

**Comment by jwpjrdev** [comment]
can someone make this never-stale?
