### ISSUE TITLE
Epic: Simplify team plans and align with project teams

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7759]
[Updated 2022-01-28 by @JanKoehnlein]
[Updated 2022-02-01 by @JanKoehnlein]
[Updated 2022-05-13 by @jldec]

**Summary**  
The goal of this epic is to simplify the administration of [**team plans**](https://www.gitpod.io/docs/teams) by making team plans behave like the new [**teams**](https://www.gitpod.io/docs/teams-and-projects#create-a-team) introduced with teams and projects. There's a detailed discussion in this [RFC](https://www.notion.so/gitpod/Aligning-Team-Plans-and-Teams-9073db94359549918ab5c85cc364de46?d=cfbea403a6734db8a3049add816c6295#e24d0882bd174016a1499a424c73e662) (internal)

**Challenges**  
- There are now 2 kinds of teams in Gitpod, one for team plan subscriptions, one for projects. This is confusing for users.
- Managing the subscription slots (members) in a Team Plan can be annoying.
- Team plans are owned by a single user. Administration of team plans cannot be delegated.
- Team plan owners do not need to be a member of the team plan themselves. ~~This capability needs to be preserved.~~
- Team plan members cannot remove themselves from a team.
- There is no API for managing team plan members.

**Task breakdown**  
- [x] #9652
- [x] #8041
  - Allow subscribing via Chargebee directly from your team Settings
  - Create a "synthetic" user subscription when you're a member of a paid Team Plan
  - Transparently update the Team Plan quantity in Chargebee when users join or leave a team
  - Pro-rate charge for new members joining in the middle of a billing cycle
  - Allow managing your Billing in team Settings via a "Team Chargebee Portal"
  - Align the new UI with #8352
  - Ship without new 'Billing' menu in team settings
- [ ] ~Only allow team owners to invite new users to a team with a paid plan~
- [ ] ~Add a membership flag for non-billed members~
- [x] Add new 'Billing' menu into team settings
- [ ] ~https://github.com/gitpod-io/ops/issues/2543~
- [x] https://github.com/gitpod-io/website/issues/2216
- [x] #10741

**Related work**
[Usage-based Billing](https://github.com/gitpod-io/gitpod/issues/9036) will provide an alternative billing mechanism which is independent of user-count or plan-selection.

**Comment by jankeromnes** [comment]
> - Team plan owners do not need to be a member of the team plan themselves. This capability needs to be preserved.

Does it really? The fact that you can be part or not part of a team plan has always created ambiguity and confusion -- as a team lead, should I purchase an individual plan for me and a team plan for my team mates, or invite myself to my team plan? What happens if I accidentally do both of these?

(See the numerous support emails we received saying "I accidentally created a plan for myself and a plan for my team, please re-unify.)

I think it's a common pattern in SaaS team plans that you're automatically part of a team that you manage. I'd vote for just dropping the capability to "manage a team without really being part of it" in the new implementation.

**Comment by JanKoehnlein** [comment]
Completely agree. That was a remnant from prior versions. We are not going to support unbilled members until we feel some commercial pressure.

**Comment by gtsiolis** [comment]
> Team plan owners do not need to be a member of the team plan themselves. This capability needs to be preserved.

Agree with @jankeromnes in https://github.com/gitpod-io/gitpod/issues/7759#issuecomment-1028718440. I see no negative reason attached to changing this. In contrast, not including the team owner can create confusion when browsing team members and sounds logical to include them in the members list but also count their membership as part of the plan. 🗳️ 

> Team plan members cannot remove themselves from a team.

Sounds ok to allow this to happen as this is supported in teams. Team members can always come back and join the team if they have the invitation URL.

> Completely migrate to new team subscriptions and remove old implementation

❓ **question**: Not sure how this would affect UX of the dashboard. If we're not migrating the old team plans to new teams, does this mean users will still see both when they have an active team plan subscription?

❓ **question**: One question that was brought up earlier this morning while meeting with @jankeromnes: In the old team plans users could start using the product for every repository they wanted and usage was counted against the old team plan. Now that teams include projects it could make sense to count only usage (workspaces, etc) for projects within that team. Food for thought. 🍔

**Comment by jankeromnes** [comment]
Thank you for sharing your thoughts @gtsiolis!

> ❓ **question**: Not sure how this would affect UX of the dashboard. If we're not migrating the old team plans to new teams, does this mean users will still see both when they have an active team plan subscription?

I think it's best to do this in two steps, in order to avoid "surprizing" users too much:

1. Implement the new "Paid Plans" feature under Team Settings (and observe initial adoption / handle initial feedback)
2. Later (once we've built confidence in the new UI), migrate older Team Plans over to new UI, and remove the old UI

At no time will you see the same paid plan in two locations:
- Current (legacy) Team Plans have no associated `teamId`, thus they show up under your personal Settings (under Teams)
- New Team paid plans _have_ an associated `teamId`, thus they show up under that Team's Settings (under Paid Plans)
- In between the two steps, we could potentially build a "voluntary migration flow" where owners of (legacy) Team Plans can select which Team the plan should move under, or if a new Team should be created for that plan

> ❓ **question**: One question that was brought up earlier this morning while meeting with @jankeromnes: In the old team plans users could start using the product for every repository they wanted and usage was counted against the old team plan. Now that teams include projects it could make sense to count only usage (workspaces, etc) for projects within that team. Food for thought. 🍔 

I think this will remain unchanged for now: In essence, we are just moving the current Team Plans to a different part of the UI (by "linking" them to a Team), but the plans' features stay the same -- i.e., if you're part of such a paid team plan (whether legacy or new), you get unlimited Gitpod hours regardless of which repository you use (just like today).

At a later point in time, we might think about implement usage-based pricing, and this will potentially change how the team plans work. But this is out of scope for now.

**Comment by gtsiolis** [comment]
Thanks, @jankeromnes!

The plan breadkdown makes sense as long as we don't push the next steps including migration too much below.

🍊 🍊 🍊 🍊 

Re-posting from a [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1628594059164300?thread_ts=1628592974.163000&cid=C021Q4BL8E8) (internal) for visibility and future reference:

> For the first iteration of Teams & Projects we’re keeping both Teams and we’re adding a deprecation notice in https://github.com/gitpod-io/gitpod/pull/5121. 

💭 **thought**: This could be re-used as an information notice rather than a deprecation notice.  

> In the future we could migrate teams by creating a new team to replace the old ones and automatically associating all users with it. 

> We could be able to create new teams for old teams with the name of the tier like Team Professional and use a url like team-professional-gzf7wf33, so that every user allocated a (old) team seat sees a new team also available in the new top navigation.

💭 **thought**: I'd be interested in your thoughts on this. I guess it would be best to first allow users to rename teams, see https://github.com/gitpod-io/gitpod/issues/5067.

🍋 🍋 🍋 🍋 

> At a later point in time, we might think about implement usage-based pricing, and this will potentially change how the team plans work. But this is out of scope for now.

Although out of the scope of this issue, moving usage-based pricing to capture usage for workspaces that have an associated project could push for adding more project and making projects more useful here, no?

🥝 🥝 🥝 🥝 

❓ **question**: Should this be part of the [roadmap](https://github.com/orgs/gitpod-io/projects/27/)? Cc @jldec

**Comment by jldec** [comment]
not quite done - see remaining tasks in description.

**Comment by jankeromnes** [comment]
@jldec I've removed my assignment to the Epic, but please feel free to directly assign remaining/sub-issues to me that you'd like to schedule next.

**Comment by jldec** [comment]
Linked to docs issue https://github.com/gitpod-io/website/issues/2216
