### ISSUE TITLE
Epic: Minimum Viable Single Sign-On (SSO)

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7761]
Closed in favour of https://github.com/gitpod-io/gitpod/issues/16862

<details><summary>Old description</summary>
**Summary**  
The goal of this epic is to allow users to sign up and log in with alternate identity providers (OIDC) which are not also git integrations. This applies to both SaaS and self-hosted Gitpod installations.

[Product Doc](https://www.notion.so/gitpod/Minimum-Viable-Single-Sign-On-SSO-4f7c5a0355ee4b22afc22c48df214114) (internal)

### Iteration 1 – Theme: Groundwork to support OIDC with Google
- [x] https://github.com/gitpod-io/gitpod/issues/14951
- [x] https://github.com/gitpod-io/gitpod/issues/14953
- [x] https://github.com/gitpod-io/gitpod/issues/15150
- [x] https://github.com/gitpod-io/gitpod/issues/14955
    - [x] https://github.com/gitpod-io/gitpod/pull/15267

### Iteration 2 – Theme: Integrate OIDC auth flow (❌ )
- [x] https://github.com/gitpod-io/gitpod/issues/15152
- [x] https://github.com/gitpod-io/gitpod/issues/14954
    - [x] https://github.com/gitpod-io/gitpod/pull/15472
    - [x] https://github.com/gitpod-io/gitpod/pull/15512
    - [x] https://github.com/gitpod-io/gitpod/pull/15631 (fixes # 14954)
- [x] https://github.com/gitpod-io/gitpod/issues/14278

### Sub-epics
* Epic: SSO/OIDC Setup Flow (for Dedicated): https://github.com/gitpod-io/gitpod/issues/15649
* https://github.com/gitpod-io/gitpod/issues/15955
* https://github.com/gitpod-io/gitpod/issues/16862

### Out of Scope
- [ ] Additional identity providers - TBD
- [ ] Identity provider APIs e.g. SAML SSO or SCIM
- [ ] Identity provider integrations with Gitpod payment plans e.g. for teams
- [ ] Group membership APIs e.g. to sync with GitHub teams
- [ ] Gitpod-native authentication (or at least account recovery via one time password sent via e-mail)

Signal: https://github.com/gitpod-io/customers/issues/46
</details>

**Comment by lucasvaltl** [comment]
This reminded me of a [blog post](https://www.enterpriseready.io/features/single-sign-on/) I read about this exact topic. It contains some very specific ideas about how to implement SAML support along with some best practices - not sure if it helps, but wanted to send it over anyways!

**Comment by shaal** [comment]
This is essential for repositories hosted elsewhere than Github, Gitlab, or Bitbucket.
ie. Drupalpod is hosted in a self-hosted Gitlab repository at https://git.drupalcode.org/project/drupalpod

A new user gets to choose between Github, Gitlab or Bitbucket when opening the Gitpod link for this repo. Since this repo is not hosted in any of those places, this can be confusing.

**Comment by shaal** [comment]
Related discussion in drupal.org - https://www.drupal.org/project/drupalorg/issues/3238242#comment-14434396

**Comment by ubshreenath** [comment]
Upvoting this.

**Comment by charleswhchan** [comment]
Hello, is the SSO OIDC feature completed?

I would like to add OidcAuthProviders config to installer (similar to [config.go::AuthProviders](https://github.com/gitpod-io/gitpod/blob/e01ca57b69b8b7d20a9660eb5fc6c03b004e15f1/install/installer/pkg/config/v1/config.go#L146)), what's the correct behavior? 
a. retrieve the config on deploy
b. write config to database on component/server start up

Note: I am happy to create a PR with guidance.

**Comment by meysholdt** [comment]
Hey @AlexTugarev, do you want to take the above questions?
