### ISSUE TITLE
Epic: Improve reliability of prebuilds and prebuild logs

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7812]
**Summary**  
Users have reported sporadic issues with prebuilds not happening, or prebuild logs not showing up. The goal of this epic is to identify specific root causes in separate issues, and mitigate those one by one.

- [ ] https://github.com/gitpod-io/gitpod/issues/8596
- [x] https://github.com/gitpod-io/gitpod/issues/8197
- [x] https://github.com/gitpod-io/gitpod/issues/8595
- [ ] https://github.com/gitpod-io/gitpod/issues/7010
- [x] Prebuilds are reported as "FAILED" in the projects page, but cannot be retriggered because they are "still running"
- [x] https://github.com/gitpod-io/gitpod/issues/7819
- [x] https://github.com/gitpod-io/gitpod/issues/7874
- [x] https://github.com/gitpod-io/gitpod/issues/7475
- [x] https://github.com/gitpod-io/gitpod/issues/7468

**Comment by purkhusid** [comment]
I would like to add an issue that I've seen happen for my repo:

1. Be in the Web UI and click `Open Workspace` on a branch that has an active prebuild
2. Wait until the prebuild finishes and the workspace is automatically opened
3. Notice that the it seems like the prebuild was not presisted and the prebuild steps have been triggered inside the workspace on workspace open

**Comment by shaal** [comment]
@purkhusid I've seen that as well.
When I disable all automatic prebuild in Github - I no longer see that.
After a commit, if I didn't manually trigger a prebuild, I'll see the `init` tasks running when I open worksapce.
If I trigger a prebuild - I'll see the `init` tasks in prebuild, and after that every new workspace will not run again the `init` tasks.

**Comment by geropl** [comment]
In the context of [this issue](https://github.com/gitpod-io/gitpod/issues/8096#issuecomment-1058175304) we found that failing prebuild instances would sometimes:
 1.) fail on first start
 2.) be re-started (why?)
 3.) eventually stop, but without(!) an error: overriding the bad state with a"positive" signal in the DB :warning: 
This could be a root cause for the perceived unreliability, of course.

Note that this seems to occur most with private repos, so not sure if this is a general issue or not.
/cc @jldec @JanKoehnlein

**Comment by jldec** [comment]
I would like to include #8446 as part of this epic once we can identify / extract actionable sub-tasks.
#8637 may be a good candidate for an incremental prebuild UI improvement.

**Comment by geropl** [comment]
@easyCZ If you have a spare minute or two, and as you're the one with the most context loaded in your prefrontal cortex :wink:  : Could you go through the issues listed here and see if they are still relevant? If not clear, please ask the original author for clarification.

Especially these maybe can be closed, because they are too broadly scoped, and/or the core issues have already been resolved with one of your PRs:
 - https://github.com/gitpod-io/gitpod/issues/8197
 - "Prebuilds are reported as "FAILED" in the projects page, but cannot be retriggered because they are "still running""

**Comment by geropl** [comment]
@easyCZ Please ping me if I can help create a (or two!) follow-up epics for this. :pray:

**Comment by easyCZ** [comment]
I've reviewed and triaged this epic. We're splitting the remaining pieces of work in prebuild reliability into two new epics:
* https://github.com/gitpod-io/gitpod/issues/9291
* https://github.com/gitpod-io/gitpod/issues/9292

Relevant issues have been linked to the new epics.

As a result of this, I'm also closing the current epic.
