### ISSUE TITLE
Epic: move image-builder-mk3 to workspace side

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7845]
## Summary

Once we move image-builder-mk3 out of WebApp, the Workspace components no longer need to run in WebApp.

## Context

To decouple WebApp and Workspace cluster deployments.

## Value

We'll be able to ship more often, with confidence and ease.

## Acceptance criteria

Image builder runs on the workspace side, at no loss of functionality. For example, users should be able to still wait for their build to finish (seeing logs while waiting) or opt to use the default image.

## Complexities

This should not impact self-hosted, because they run all of their workloads on one cluster (currently).

## Tasks

Stack 1 - Prepare for moving image-builder-mk3 to workspace cluster
- [x] gitpod-io/gitpod#9138
- [x] gitpod-io/gitpod#9508

Stack 2 - Webapp cluster builds images using workspace cluster image builder
- [x] ~chart: remove image-builder-mk3 from Helm (perhaps not needed @geropl ?)~
- [x] gitpod-io/gitpod#9248
- [x] gitpod-io/gitpod#9137

Stack 3 - Prepare for and run image builds in workspace cluster
- [x] gitpod-io/ops#5905
- [x] gitpod-io/gitpod#9729
- [x] gitpod-io/gitpod#13881
- [x] Incrementally rollout the feature via the `movedImageBuilder` feature flag using configcat (gitpodders, then free users, then paying users)

Stack 4 - cleanup
**Wait to begin this stack until we're running 100% with image-builder-mk3 in production on SaaS.**
- [x] gitpod-io/gitpod#9143
- [x] gitpod-io/ops#6700
- [ ] Remove infrastructure and configuration in ops for webapp for image-builder-mk3

<strike>Stack 4 - Finish existing `image-builder-mk3` issues (can be tested in gitpod-staging.com if done as Stack 0, as an alternative, could do against workspace-clusters if done as the final stack)
- [ ] https://github.com/gitpod-io/gitpod/issues/7264
   * Issue 7264 is unrelated to this epic, but, is related to the component, and should be included as part of shipping image-builder-mk3, as there is a related draft PR: gitpod-io/gitpod#10192
- [ ] https://github.com/gitpod-io/gitpod/issues/10089
   * Issue 10089 is unrelated to this epic, but, is related to the component, and should be included as part of shipping image-builder-mk3, as there is a related draft PR: gitpod-io/gitpod#10235</strike>

## Questions: 	
We socialized introducing a new status for image builds. I'm unsure if we want to do that now, or wait until later. @kylos101 would prefer later.

**Comment by geropl** [comment]
> We socialized introducing a new status for image builds. I'm unsure if we want to do that now, or wait until later. @kylos101 would prefer later.

@kylos101 As this epic is for the first step, which about simply maintaining the old API, state model and behavior, "just" moved to the workspace cluster, we should exclude it here.

**Comment by kylos101** [comment]
@atduarte I 'struck out' Stack 4 of this, to limit the scope for the epic, just to moving image builder mk3 to the workspace cluster.

**Comment by easyCZ** [comment]
At the moment, there continue to be [requests made](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28grpc_server_handled_total%7Bjob%3D%5C%22ws-manager%5C%22,%20cluster%3D~%5C%22prod-meta.%2A%5C%22%7D%5B1m%5D%29%29%20by%20%28cluster,%20grpc_method%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D) against `ws-manager` in WebApp clusters:
<img width="3280" alt="Screenshot 2022-09-27 at 11 48 35" src="https://user-images.githubusercontent.com/1419286/192494159-681426f1-757f-4d81-8945-cda6ad690e29.png">

**Comment by easyCZ** [comment]
Currently it looks like `image-builder-mk3` is not correctly reporting any server metrics. That's a necessary pre-requisite for us to be able to move it - we need to be able to observe it.
To that end, I've [moved image builder to use baseserver in this PR](https://github.com/gitpod-io/gitpod/pull/13363) which also fixes the metrics reporting - we know metrics from base server do work correctly.

**Comment by aledbf** [comment]
@WVerlaek after 15276 image builder still uses `gitpod.io/workload_meta` instead of `gitpod.io/workload_services`.

**Comment by WVerlaek** [comment]
@aledbf that's the node label right? It seems that wasn't caught in testing because in workspace clusters the services nodes also have the `gitpod.io/workload_meta` label. Is that not the case for dedicated? 

I can change it so that image-builder gets the `gitpod.io/workload_services` affinity when deployed to workspace clusters

**Comment by kylos101** [comment]
Application cluster clean-up is being handled in https://github.com/gitpod-io/gitpod/issues/16095 by WebApp team.

**Comment by kylos101** [comment]
@geropl closing this for now, I figure you can track cleanup for application clusters as groundwork

**Comment by loujaybee** [comment]
@kylos101 this epic is currently on the public roadmap, but the current title is not very friendly to externals, or customers. Is it possible to either rename the title, or remove from the roadmap project?
