### ISSUE TITLE
Epic: Public Gitpod API

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#7900]
# Summary

In this epic we lay the foundation for a new public Gitpod API that can be consumed by Gitpod components as well as external clients. See this [design doc](https://www.notion.so/gitpod/Design-Doc-Public-Gitpod-API-15cdeb5d3496448ca3b61187a8aac53f) for details.

# Context

Extensively summed up in the [design doc](https://www.notion.so/gitpod/Design-Doc-Public-Gitpod-API-15cdeb5d3496448ca3b61187a8aac53f).

# Value
- provide a uniform, reliable, stable and versioned API
- consolidate our tech stack (e.g. replace JSON-RPC and REST interfaces)
- centralise common aspects such as authentication, rate-limiting, circuit-breaking etc.
- more in the [design doc](https://www.notion.so/gitpod/Design-Doc-Public-Gitpod-API-15cdeb5d3496448ca3b61187a8aac53f)

# Measurement
This epic has been successfully finished when
- the JetBrains Gateway and the dashboard successfully use the new API
- we have hardened and proven our API Guidelines
- we feel confident about our choice of technologies (gRPC, Envoy, ...)
- we are convinced the API is ready for public adoption

# Steps

## v0.1: offer basic functionality for the IDE team
- [ ] Define gRPC interface files for a workspace API
  - define `proto` files covering services to list workspaces, create and start workspace, and listen to status updates (including pre-builds and image builds)
  - gather experiences with/revise API design guidelines from the [design doc](https://www.notion.so/gitpod/Design-Doc-Public-Gitpod-API-15cdeb5d3496448ca3b61187a8aac53f)
  - define and separate re-usable concepts, e.g. for paging, structured errors
  - generate implementations in TypeScript, Go and Java
- [ ] implement the gRPC services in server 
- [ ] provide workspace API via proxy
- [ ] Introduce Envoy and plumb through proxy
   Configure
    - authorization
    - rate limiting
    - circuit breaking
    - metrics for HTTP and gRPC
    - distributed tracing

## v0.2: transition to Envoy
- [ ] Completely replace Caddy with Envoy proxy
  Migrate all the custom logic (Tiny Go/WebAssembly)

## v0.3: transition workspace startup in the dashboard
- [ ] Replace JSON-RPC with new public API in dashboard 
  Only for the workspace services implemented in v0.1

# Out of scope
- Complete migration of the current JSON-RPC API
- Define separation between public and private API

**Comment by andymac4182** [comment]
Can you please make the design doc public.

**Comment by loujaybee** [comment]
Hey @andymac4182 👋 
> A Terraform provider for managing Gitpod teams

This request is very worthy of its own feature request / issue. This epic will likely not be the fully-fledged API, but a subsection of some of the API's as well as a foundation for future API's. I doubt all of the CRUD API's required for a fully working Terraform provider will be possible within this issue/epic alone. 

> Can you please make the design doc public.
I'll look into this to see if there's anything sensitive or whether it's indeed possible to make public 🙏

**Comment by ajhalili2006** [comment]
What about authorization and authentication stuff? Will you go to the OpenID Connect route like others or the usual OAuth way like GitHub did? Will managing own OAuth clients be included in the epic roadmap?

**Comment by geropl** [comment]
The original epic from team IDE with the narrowly-scoped feature requests for the very first iteration: https://github.com/gitpod-io/gitpod/issues/8512

**Comment by jmls** [comment]
any updates on this ?

**Comment by geropl** [comment]
Hi @jmls, you can follow the current progress on the linked issue: https://github.com/gitpod-io/gitpod/issues/9229

As written in the description, we're currently focusing on our first internal client and their specific needs, and use the experience for that to lay out the foundations. How we're going to move forward beyond that specifically - e.g. how we prioritize adding more functionality is - up to future discussions.
