### ISSUE TITLE
Epic: improve workspace load test automation

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7934]
## Summary

As part of our current [loadgen](https://github.com/gitpod-io/gitpod/tree/main/dev/loadgen) program and deploy practices, we measure how quickly we auto scale nodes to meet demand for new workspaces. We don't currently put runtime stress on the nodes or assert that our limiters are working as we expect.

## Context

We had a series of incidents recently that were related to performance regressions.

## Value 
The ability to add workspace runtime load to clusters when using loadgen. This should apply to CPU, disk, network (ingress and egress), and memory. 

The ability to measure performance that workspaces are able to achieve, and assert that limiters are working correctly on our nodes. This should likely be done manually as part of this epic, documenting how-to, with the understanding that it may be automated in the future.

**Cluster and Node assertions**
- [x] https://github.com/gitpod-io/gitpod/issues/9722
   * Verify all started workspaces enter a running state
- [x] https://github.com/gitpod-io/gitpod/issues/9724
   * The started workspaces run a variety of workloads, and the workspaces are able to achieve minimum disk IO speeds and core usage. We'll need to define (1) the workspace density (2) the load we run in each workspace and (3) what success looks like over the time of the test, for the workspaces on each node.
- [x] #9901
- [x] #9948

<strike>
**Limiting tests** 
These may have to simply be measured in Grafana, or some other manual means. Inspecting the file system to see how the cgroups are configured is somewhat of a trap, and not a real measure of the limiters behaving correctly. 

For each of the limiter tests (below), they must pass for processes in the workspace, including Docker containers.

- [ ] CPU limiter governs as we expect
- [ ] Disk IO limiter governs as we expect
- [ ] Network ingress/egress limits behave as we expect
</strike>

**Documentation changes**
1. Update [runtime tests](https://www.notion.so/gitpod/Common-runtime-tests-4e3b05c3b81e4ff6810572aee66ffad3) to be more explicit to include test steps, expected results (including what sample log entries).
2. Add a document describing the baseline cluster and node performance we must always achieve with each generation

## Acceptance criteria
1. We've gained the ability to have workspaces that start as part of loadgen create runtime load for a node's CPU, memory, and disk.
2. We've defined what acceptable workspace performance looks like on a node and cluster under stress.
3. Our deploy documentation is updated, so that all teammates can conduct a performance test, decide whether a new cluster passes or fails using common/shared criteria. 

## Measurement
We should be able to use this new process, and record results (performance achieved) in our cluster changelog, with every release of a new generation.

**Comment by princerachit** [comment]
@kylos101 you recommended using the alternative option first rather than the actual proposal. Would it make sense to split this into 2 issues?

**Comment by kylos101** [comment]
The options I listed are under alternatives section are:
1. using custom images
2. adding new cmd to loadgen

For now, I think we need to see the value from a simple solution, and then determine next steps. No sense in planning a second issue if we lack the results and learnings from the first.

**Comment by kylos101** [comment]
@Furisto in hindsight, I think we should convert this into an epic, so that we can pick away at the bulleted items in the description. wdyt? 

Let's catch up Tuesday to socialize? I wonder if there are other tasks that you think might be valuable to add to this, too.

CC: @atduarte

**Comment by kylos101** [comment]
@Furisto we should also see if we can make it so that when loadgen is used, that it can actually backup to object storage. Right now it cannot, I believe because the userid doesn't relate to an actual bucket. I will add as an issue to this epic meow.

**Comment by kylos101** [comment]
@atduarte we're basically done with this epic, except, for running a load test next week, and setting a baseline for node and cluster peformance.

@Furisto Re: when do you plan to run the loadgen test for next week's deployment? I ask because we should use that as an opportunity to inspect results in Grafana and socialize a baseline with @aledbf, to agree and land on a baseline to use for future tests. In other words, if we cannot achieve the baseline in future tests, that would mean we've regressed performance wise.

**Comment by kylos101** [comment]
@Furisto I've updated this epic, to remove the limiter test automation from scope, and added a section for Documentation Changes. I think once the Documentation Changes are finished, then we can consider this epic finished. For example, I recommend compiling a draft baseline for the cluster and nodes to achieve, share it to get feedback from the team, and then update it accordingly.

**Comment by Siddhant-K-code** [comment]
I was going through the [loadgen/prod-benchmark.yaml
](https://github.com/gitpod-io/gitpod/blob/main/dev/loadgen/prod-benchmark.yaml). Saw that, we didn't added for `Java` & `Go` in the workflow.

**Comment by Furisto** [comment]
@kylos101 Documentation has been updated. Let me know if you want to see something else.

**Comment by kylos101** [comment]
@Furisto can you address the comments I left [here](https://www.notion.so/gitpod/Expected-workspace-cluster-performance-fcef20e0b4b243e2ab4b4d1e678cdda0)?

@utam0k may we ask for your help in reviewing our [deploy checklist](https://www.notion.so/gitpod/Deploy-checklist-for-workspace-clusters-a8a06edfc1474c7b83377f0a84e67c87)? If you have any questions, @Furisto went through it recently, and will be able to address.

After these two things are done, I think that should do it. :pray:

**Comment by utam0k** [comment]
I go through the checklist and left some comments. It is great documentation!

**Comment by kylos101** [comment]
@atduarte we're all set with this one, documentation updated accordingly. As this isn't a new feature, and there's no validation period, I am going to close.
