### ISSUE TITLE
Epic: Foundation of IDE integration testing

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#8017]
#### Context 
Currently, IDE team does not have any means to run end-to-end testing which makes it hard to ensure quality.

#### Value
- QA for major VS Code extensions deployed by https://github.com/open-vsx/publish-extensions
- QA for changes done by other teams but affecting IDEs like SSH gateway
- Automated rollout of new IDEs versions.
- Automated rollout of new IDEs components.

#### Acceptance Criteria

- [x] Integration test suite runs nightly on main branch and reported to [ide-jobs slack channel](https://gitpod.slack.com/archives/C02F9LQU4DR).
- [x] At least one test is running for VS Code integration
- [x] At least one test is running for JB integration

**Comment by iQQBot** [comment]
updated progress

**Comment by akosyakov** [comment]
@iQQBot Is it done now?

**Comment by iQQBot** [comment]
I think it's done, when PR merge

**Comment by akosyakov** [comment]
I'm going to close this epic since it was done in Feb. And we have indeed tests running for JB and VS Code Browser. We need another epic for VS Code Desktop and SSH against self-hosted.
