### ISSUE TITLE
Epic: Support cgroup v2

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#8350]
## Summary
cgroup v2 support enables new workloads in Gitpod clusters, e.g. is a prerequisite for k3s support.

## Value
Today we only support cgroup v1. Cgroup v2 is namespaced and offers more functionality in combination with user-namespaces. It's the precursor to supporting things like k3s within workspaces.

## Acceptance criteria
- we can still run workspace clusters which use cgroup v1 where ws-daemon fulfils its control tasks
  - enabling `/dev/fuse`
  - dynamic CPU limiting
- we can run workspace clusters which use cgroup v2 where ws-daemon fulfils its control tasks

## Tasks
- [ ] [ws-daemon] Migrate current cgroup interaction to a package, ideally re-using an existing one (e.g. [containerd's cgroup](https://github.com/containerd/cgroups))
  - [x] #8417
  - [x] #8497
  - [x] #8498
- [x] #8567
- [x] [workspacekit] Introduce cgroup namespace for ring2 #8567
- [x] #8627
- [x] Update the image to enable cgroup v2

**Comment by kylos101** [comment]
@csweichel I am slightly worried about the test effort associated with v1 (like for older self hosted clouds) and v2 (everything else). 

Perhaps we could add a task to this epic, to also do integration testing with cgroup v1? Maybe it could even leverage some of the work that we do over the next few weeks for deploy automation. For example, when we build the packer image, do so with one image supporting v2 and another supporting v1 (great idea, @Furisto , thank you!).

CC: @aledbf @sagor999

**Comment by aledbf** [comment]
> For example, when we build the packer image, do so with one image supporting v2 and another supporting v1

We disable v2 in the nodes because that breaks `ws-manager`

https://github.com/gitpod-io/gitpod-packer-gcp-image/blob/main/setup.sh#L81

**Comment by utam0k** [comment]
I created the issues to support cgroup v2
- https://github.com/gitpod-io/gitpod/issues/8497
- https://github.com/gitpod-io/gitpod/issues/8498

**Comment by utam0k** [comment]
@csweichel I think it has been done?
> [workspacekit] Introduce cgroup namespace for ring2

**Comment by csweichel** [comment]
Indeed it has. Thanks @utam0k for pointing that out.

**Comment by kylos101** [comment]
@Furisto we've closed this epic for now, as cgroup v2 is shipped. If there's anything lingering that you can think of, may I ask you to inbox a related issue and share it here?
