### ISSUE TITLE
Epic: Improve dashboard navigation

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#8385]
### Epic tasks

- [x] Move `Workspaces` into top right nav, move `Docs` and `Help` under profile
- [x] Soft-highlight all top nav elements to show context
- [x] Split team context button with 2 active hover areas
- [ ] https://github.com/gitpod-io/gitpod/issues/10976
- [ ] https://github.com/gitpod-io/gitpod/issues/7879

### Problem to solve

The dashboard navigation has grown over the last few months with the addition of new features like _Teams & Projects_ as well as new features in the admin dashboard like Telemetry settings, etc.

This introduced new components like _tabs_ and _dropdowns_ that help scale the user interface options but also improve overall UX of the dashboard, etc. However, on the way the the additional navigation elements affected usability and more specifically user control[[1](https://www.nngroup.com/articles/user-control-and-freedom/)] and consistency[[2](https://www.nngroup.com/articles/consistency-and-standards/)] across the product, see screenshots below as well as relevant issues: https://github.com/gitpod-io/gitpod/issues/7668, https://github.com/gitpod-io/gitpod/issues/7879, and https://github.com/gitpod-io/gitpod/issues/7716.

| Projects (Personal Account) | Projects (Team) |
|-|-|
| <img width="1440" alt="Screenshot 2022-02-22 at 3 14 35 PM" src="https://user-images.githubusercontent.com/120486/155140536-1a21dc7f-ea97-4bf3-bef4-8cf7034382fd.png"> | <img width="1440" alt="Screenshot 2022-02-22 at 2 41 45 PM" src="https://user-images.githubusercontent.com/120486/155140595-f8cb18ef-1a7f-41fb-a833-614ae8c909fc.png"> |

| Settings (Project) | Settings (Admin) | Users (Admin) | 
|-|-|-|
| <img width="1440" alt="Screenshot 2022-02-22 at 2 42 00 PM" src="https://user-images.githubusercontent.com/120486/155140991-6d2ac3e6-1532-4fac-b68b-32054e21fab8.png"> | <img width="1440" alt="Screenshot 2022-02-22 at 3 22 42 PM" src="https://user-images.githubusercontent.com/120486/155141023-585d51d1-1afd-4a03-9511-6a51dfb5dc17.png"> | <img width="1440" alt="Screenshot 2022-02-22 at 2 42 21 PM" src="https://user-images.githubusercontent.com/120486/155141158-e823f0bf-5768-4555-b43f-066cca2d0d7d.png"> |

| Workspaces (Personal Account) |  Branches (Project) | Prebuild (Project) |
|-|-|-|
| <img width="1440" alt="Screenshot 2022-02-22 at 2 41 33 PM" src="https://user-images.githubusercontent.com/120486/155141051-c2547dd9-480a-4fc7-8f07-5816f7db384f.png"> | <img width="1440" alt="Screenshot 2022-02-22 at 2 41 53 PM" src="https://user-images.githubusercontent.com/120486/155141357-c51d1bcf-3f31-4c91-829b-ba8241c408a6.png"> | <img width="1440" alt="Screenshot 2022-02-22 at 3 26 52 PM" src="https://user-images.githubusercontent.com/120486/155141707-5c823f5c-c0a7-4df0-91ed-41771abf3281.png"> |

### Proposal

~~Opening this as a placeholder issue based on the relevant discussion[[1](https://www.notion.so/gitpod/WebApp-design-sync-Feb-17-2022-2d50cfbdf3c44426941d5e8e4bb73fb0#f75d5ebd47d74c25880fa7f9802e8794)][[2](https://www.notion.so/gitpod/WebApp-design-sync-Feb-17-2022-2d50cfbdf3c44426941d5e8e4bb73fb0#c613e40005b74f5f83bb0c9dbd88c7b9)] (internal). Cc @jldec~~

In the spirit of MVC (minimum viable change) here's the proposed changes within the scope of this issue.

**Changelist**:
1. Move workspaces as a global navigation menu item
2. Introduce a dropdown split button with two active areas.
3. Use the team scope dropdown left area to link to the default page of the scope, that is Projects.
4. Use the team scope dropdown right area to trigger the dropdown.
5. Use a darker active color to visually separate information hierarchy of the page contents below.
6. Move the tabs (Projects, Settings, etc) below the header section.
7. Re-structure admin menu to use tabs.
8. Move Help and Docs user menu inside the user dropdown as described in https://github.com/gitpod-io/gitpod/issues/7925#issuecomment-1044791267.

**Changes to consider**:
1. Keep the active top-level menu item per page. ✔️ 
2. Use a narrower container width (optional).
3. Use more radius for the top-level navigation menu items. ✔️ 
4. Remove the separator border between the top-level navigation and the header title. (would help to show top-nav everywhere) 
5. Consider moving the feedback menu inside the user dropdown.

### Designs

| Workspaces |
|-|
| <img width="1440" alt="Workspace-Active (AFTER)" src="https://user-images.githubusercontent.com/120486/160603389-73c18c31-2784-4f95-b1c0-f5266f2fb716.png"> |

| Broad width | Narrow width |
|-|-|
| <img width="1440" alt="Workspaces-1" src="https://user-images.githubusercontent.com/120486/160603416-b5bb9f65-a0e6-494a-831e-67fa90197665.png"> | <img width="1440" alt="Workspaces" src="https://user-images.githubusercontent.com/120486/160603421-27c13019-54dd-472d-ab3a-b80fa0e3cf1e.png"> |

| Team Hover (Left) | Team Hover (Right) | Team Active |
|-|-|-|
| <img width="1440" alt="Team-Hover" src="https://user-images.githubusercontent.com/120486/160603817-5081de78-e34d-4405-8ad5-c49dba3deb3e.png"> | <img width="1440" alt="Team-Hover-1" src="https://user-images.githubusercontent.com/120486/160603825-e4528e10-69e0-4b13-8de6-c74298f6c65d.png"> | <img width="1440" alt="Team-Active" src="https://user-images.githubusercontent.com/120486/160603865-6ae2e842-dd5b-42b1-8944-a64c4a64e144.png"> |

| Project | Prebuild | Admin |
|-|-|-|
| <img width="1440" alt="Project" src="https://user-images.githubusercontent.com/120486/160603562-cde83773-8ffd-4f10-b7b3-4b694a8dd6bf.png"> | <img width="1440" alt="Prebuild" src="https://user-images.githubusercontent.com/120486/160603569-0cc8b271-7d54-4f2d-b96f-6c8baaff4f4c.png"> | <img width="1440" alt="Admin" src="https://user-images.githubusercontent.com/120486/160603576-b4a152d6-ea70-4f8c-b57f-4c011171cdd0.png"> |

See [design specs](https://www.figma.com/file/jtlGGLfdNIBNujQWEWPUvp/Dashboard-navigation-updates-%238385?node-id=0%3A1).

**Comment by gtsiolis** [comment]
In the spirit of questioning the proposed designs above, here're some screenshots side-by-side of the new navigation with no, soft, and hard highlight of the active menu on a real page like the _Workspaces_ list which also contains a primary action button. Cc @jldec @svenefftinge 

| No highlight | Soft highlight | Hard highlight |
|-|-|-|
| <img width="1440" alt="Dropdown" src="https://user-images.githubusercontent.com/120486/157275036-c405517f-dcc6-40f0-8477-c6c4c7056c58.png"> | <img width="1440" alt="Dropdown" src="https://user-images.githubusercontent.com/120486/157274680-71608257-328b-4d72-94a3-fb721fd0b335.png"> | <img width="1440" alt="Dropdown" src="https://user-images.githubusercontent.com/120486/157275138-ab36beea-e54d-40dc-b28c-2910e5a9c8a9.png"> |

**Comment by gtsiolis** [comment]
I've updated the designs in the description to move forward with the soft highlight for this iteration.

**Comment by gtsiolis** [comment]
I've opened the follow-up https://github.com/gitpod-io/gitpod/issues/10976 and reopened the https://github.com/gitpod-io/gitpod/issues/7879 for keeping track of the outstanding two tasks of this epic.

@jldec Sounds good to close this issue (epic) based on https://github.com/gitpod-io/gitpod/issues/8385#issuecomment-1160381395?

**Comment by jldec** [comment]
@gtsiolis, I'd prefer to keep this Epic open since we still have 2 incomplete tasks - they're just not scheduled for immediate implementation.

**Comment by gtsiolis** [comment]
Sounds good, @jldec! Your call. 🏀 

Just wanted to make to bring some visibility to these new follow-up issues.
