### ISSUE TITLE
Epic: Support GitHub Enterprise

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#8501]
Gitpod users would like to use their own GitHub Enterprise instance to work with Gitpod.

The experience of registering and connecting users to GHE should be at least on parity with private GitLab instances.

Support for registering a GHE instance and performing authentication is already in place. 

**Gaps** (_additional validation required_)

- [x] Registration of the GitHub App for Gitpod, for GHE instances. 
- [x] Context URL parsing
- [x] Webhooks integration for prebuilds and projects
- [x] #8429

**Comment by gtsiolis** [comment]
See also https://github.com/gitpod-io/gitpod/issues/5297.

**Comment by jankeromnes** [comment]
_Logging my progress. Please let me know if I should do this somewhere else. 🙏_

### Current state

- We have a GitHub Enterprise installation for testing (thanks @metcalfc!)
- There are already [docs for connecting GitHub Enterprise](https://www.gitpod.io/docs/github-integration#github-enterprise-server):
  - Seems to be written for Self-Hosted (e.g. "starting your Gitpod installation, you’ll get redirected to /first-steps")
  - However, it seems to work with gitpod.io
- I was able to connect our GitHub Enterprise instance with gitpod.io :

<img width="600" alt="Screenshot 2022-03-03 at 09 47 33" src="https://user-images.githubusercontent.com/599268/156558753-a2ca0c1e-c301-4eba-98e2-ad1539962512.png">

### Problems

- However, the final step of adding the GitHub Enterprise integration is to Connect with it, and this currently fails:

<img width="600" alt="Screenshot 2022-03-03 at 09 47 02" src="https://user-images.githubusercontent.com/599268/156559070-281c2fe3-9e48-47d1-b488-f8236a391edf.png">

Maybe it's because I've configured it badly, or there is a bug somewhere. Currently investigating this.

**Comment by jankeromnes** [comment]
This logged error seems relevant:

```
TokenError: The client_id and/or client_secret passed are incorrect.
    at GenericOAuth2Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at GenericOAuth2Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /app/node_modules/passport-oauth2/lib/strategy.js:177:45
    at patchedCallback (/app/node_modules/@gitpod/server/dist/src/auth/generic-auth-provider.js:674:28)
    at /app/node_modules/oauth/lib/oauth2.js:209:7
    at passBackControl (/app/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Some other relevant snippets from around the error:

```ts
{
    "message": "(Auth-With-ghe.gitpod-self-hosted.com) Initialized.",
    "payload": {
        "defaultStrategyOptions": {
            "authorizationURL": "https://ghe.gitpod-self-hosted.com/login/oauth/authorize",
            "tokenURL": "https://ghe.gitpod-self-hosted.com/login/oaut/access_token",
            "clientID": "[REDACTED]",
            "clientSecret": " [REDACTED]",
            "callbackURL": "https://gitpod.io/auth/ghe.gitpod-self-hosted.com/callback",
            "scope": "user:email,read:user,public_repo,repo,read:org,workflow",
            "scopeSeparator": ",",
            "userAgent": "gitpod.io",
            "passReqToCallback": true
        }
    }
}

authFlow: {
    host: 'ghe.gitpod-self-hosted.com',
    returnTo: 'https://gitpod.io/complete-auth?message=success',
    overrideScopes: false
}

{
    path: '/auth/ghe.gitpod-self-hosted.com/callback?code=[REDACTED]'
}

{
    code: 'incorrect_client_credentials',
    uri: 'https://docs.github.com/enterprise/3.3/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#incorrect-client-credentials',
    status: 500
}
```

From what I can tell, the `client_id` and `client_secret` values look correct (except for a space in front of the secret? 🤔)

I guess this calls for a dev environment with more debug logs.

**Comment by jankeromnes** [comment]
Okay, connecting the app worked, let's try opening a repository.

Opening a private repository fails with:

<img width="600" alt="Screenshot 2022-03-03 at 14 58 50" src="https://user-images.githubusercontent.com/599268/156579399-a1733e0c-b06b-49d2-a29b-bb5b3f8ccb95.png">

Clicking on `Grant` just goes back to the same error again. New thing to debug! 🙌

**Comment by AlexTugarev** [comment]
@jankeromnes and @jldec, what is the plan of registering of GitHub Apps? 

It is a prerequisite for Projects support for GHE. Is it planned to extend the form on the /integrations page and use the DB to persist the private key?

**Comment by jankeromnes** [comment]
While GitHub Enterprise is now generally supported in both SaaS and Self-Hosted (https://github.com/gitpod-io/gitpod/pull/8574), I'll just briefly re-open this Epic for one more test:

It would be cool to experiment with a Gitpod Self-Hosted installation that points its GitHub App (singleton) to a GitHub Enterprise installation instead of `github.com` (for the particular case where you self-host Gitpod and only use your GitHub Enterprise installation without caring about `github.com` -- there it could potentially be helpful to set up the GitHub App in your GitHub Enterprise server in addition to the OAuth Integration).

**Comment by geropl** [comment]
@jankeromnes This is an error from prod: https://console.cloud.google.com/errors/detail/CLja7KCK6azk-QE;service=server;time=PT1H?project=gitpod-191109
Could it be related to this changes?

**Comment by jankeromnes** [comment]
@geropl Interesting, thanks for reporting. That entire code is new since this epic, so yes it's related.

Looking at the code, it looks like something is sending webhook payloads without setting an expected header:
- A request is sent to our GitHub Enterprise webhook URL 👍
- The HTTP header `X-GitHub-Event` is properly set to `push` 👍
- However, the HTTP header `X-Github-Enterprise-Host` is not set ❌

https://github.com/gitpod-io/gitpod/blob/54618bfc2a0ed1a9019a6b257343dc30674adc32/components/server/ee/src/prebuilds/github-enterprise-app.ts#L70-L74

This causes these particular webhook calls to be rejected. I suspect this is from an older version of GitHub Enterprise, and the likely symptom is that someone enabled Prebuilds for a project on that older GHE, but the Prebuilds are not being triggered due to this error.

Would be good to investigate these failing calls, and see if there is another way to identify which GitHub Enterprise server they're from.

**Comment by jldec** [comment]
moved ☝️ into #9196 so that we can close this epic.
