### ISSUE TITLE
Send commit statuses to GitLab, Bitbucket, and GitHub Enterprise

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8796]
## Is your feature request related to a problem? Please describe

We currently have this support matrix:

| Integration | Can create Project | Push triggers Prebuild | Prebuild sets Commit Status |
| :---: | :---: | :---: | :---: |
| github.com | ✅ | ✅ | ✅ |
| GitHub Enterprise | ✅ | ✅ | ❌ |
| gitlab.com | ✅ | ✅ | ❌ |
| Self-Managed GitLab | ✅ | ✅ | ❌ |
| bitbucket.org | ✅ | ✅ | ❌ |
| Bitbucket Server |  ✅ |  ✅ | ❌<sup> |

## Describe the behaviour you'd like

This issue is about making the rightmost column green:

- [ ] Send prebuild commit statuses to both gitlab.com and Self-Managed GitLab (via [the API](https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit))
- [ ] Send prebuild commit statuses to bitbucket.org (via [the API](https://developer.atlassian.com/server/bitbucket/how-tos/updating-build-status-for-commits/))
- [ ] Send prebuild commit statuses to GitHub Enterprise (via [the API](https://docs.github.com/en/rest/reference/commits#create-a-commit-status))
