### ISSUE TITLE
Epic: Blazingly Fast Workspace Starts 🚀 

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#8973]
### Summary 

We want to make a big step in regards to workspace start-up times. 

 - [ ] https://github.com/gitpod-io/gitpod/issues/8971 
 - [x] https://github.com/gitpod-io/gitpod/issues/8186
 - [ ] https://github.com/gitpod-io/gitpod/issues/8972
 - [ ] https://github.com/gitpod-io/gitpod/issues/8992
 - [x] https://github.com/gitpod-io/gitpod/issues/9006
 - [ ] https://github.com/gitpod-io/gitpod/issues/9018

### Context 

We have a series of existing hypothesis and experiments that we believe will impact user-facing Gitpod performance for workspace starts. This epic is to implement these experiments, with the expectation of an increase in performance

### Value

Improving the user experience, eliminating one of the most significant frictions that are currently associated with ephemeral workspaces.

### Acceptance Criteria

 - [ ] Implement a user-centric metric that represents the full workspace startup time
 - [ ] Run 4 experiments with the objective to improve the workspace startup time metric.

### Measurement

1. Decrease in P50 and P95 time to start a workspace, from a user perspective—which includes server and IDE times.
2. Increase in user sentiment about workspace performance time https://github.com/gitpod-io/gitpod/issues/7925
3. Optional measurements: 
    1. Workspace / page refresh and restarts (user thrashing)
    2. Abandoned workspaces (workspaces started but not “used”)
 
### Growth Area 

N/A

### Persona 

All Gitpod users.

### In Scope

Improving performance of workspace starts

### Out of scope

Improving performance of other aspects of Gitpod (general performance) e.g. prebuilds

### Complexities

- We do not have a metric defined for performance (from a user-facing standpoint)
- Potential “milestones” along workspace start
    - Workspace requested
    - Workspace provisioned
    - IDE loaded
    - IDE content interactive
    - IDE tasks loaded and shown

### Press Release

N/A

**Comment by atduarte** [comment]
Closed in favour of smaller and more specific 🛹 epics.
