### ISSUE TITLE
Epic: Improved Workspace Startup Times

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#9018]
### Summary

We want to leverage IPFS (caching) and eStargz (lazy image pulling) to make workspace startup times incredibly fast.

### Context

Currently, the median workspace startup time is below 10 seconds, but the P95 is around or above 1 minute.  

### Value

Having to wait for the development environment to start adds friction to the experience. When developing locally a persistent development environment is used which means a lot of time is wasted setting it up and upgrading it, and problems arise frequently but regular usage is instant. We want to provide the same fast experience with ephemeral development environments.

### Acceptance Criteria

- [ ] Workspace container images are lazily pulled.
- [ ] Workspace container images are cached in the regional cluster.

### Measurement

- [ ] 95th percentile of workspace startup times is under 40 seconds.

### Growth Area

Expansion.

### Hypothesis

We are able to reach sub 10 seconds for the 95th percentile of workspace startup times.

**Comment by atduarte** [comment]
Closing since this was partially done and the rest is represented by https://github.com/gitpod-io/gitpod/issues/8992
