### ISSUE TITLE
Epic: User Configurable Workspace Timeouts (CLI command + user preference)

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#9038]
## Press Release

Gitpod users can now set any timeout up to 24 hours using the command line, or with a native integration in their favourite editors! To try out this feature, simply type: `gp timeout set 1h` in any running workspace to extend the workspace inactivity timeout of that workspace. To set your global user preference timeout, got to your use preferences and set the value that you want to apply for all future timeouts. Additionally, we've also made the editor timeout configuration optional, meaning that if you don't want a Gitpod workspace to timeout when you close your editor, you can now set 

### External Questions

<details>
  <summary><strong>Does this work for free users?</strong></summary> No, currently only users on a paid plan can extend timeouts. 
</details>

<details>
  <summary><strong>Is the timeout respected / guarenteed?</strong></summary> No. A workspace has a maximum continuous session time of 36 hours. 
</details>

<details>
  <summary><strong>Do timeout settings apply to running workspaces?</strong></summary> TBC
</details>

<details>
  <summary><strong>Can you set an admin preference for timeouts?</strong></summary> Not currently. This is something we plan to introduce as an organisation policy in the future. 
</details>

### Internal Questions

<details>
  <summary><strong>Why have a 24hr timeout limit?</strong></summary>
  24 hours is somewhat arbitrary, and we want to learn what users do with this. But, also the 24hr is based around a few infrastructure constraints. We have an <a href="https://github.com/gitpod-io/website/pull/3341">undocumented 36 hour workspace session limit</a>, that we need for doing workspace deployments, to allow us to upgrade workspaces. There are also some tokens within the workspace scoped to 24 hours that might break if a workspace runs longer than 24 hours (@akosyakov mentioned this - the supervisor token, which is revoked on workspace stop, renews on restart but doesn't refresh). 

</details>

---

## Context

Gitpod timeouts have historically been optimised mostly for cost reduction, to relieve users from any anxiety about leaving workspaces running forever and therefore creating unnecessary cost. Since Gitpod is ephemeral we want to encourage users to start new workspaces and manage the scaling of these workspaces to not incur unnecessary cost. As Gitpod moves towards a usage-based pricing model #[9036](https://github.com/gitpod-io/gitpod/issues/9036) there is opportunity to review how Gitpod handles timeouts, giving more power to the user to decide what timeout configuration works best for them. 

Currently, timeouts are fixed to 30min resp. 60min (+ 3h boost) for unlimited users. In some cases, however, there is a trade-off being made between the usability of Gitpod workspaces and cost management (through timeouts) as some users have use-cases where they want to have Gitpod workspaces open for longer, whereas other users would like to keep workspaces running, and are less cost conscious. 

## Use Cases

1. User is using an unsupported client without heart-beating (e.g. JetBrains Fleet)
2. User is running long-running tasks in workspaces and needs to leave workspace running (e.g data tasks)
3. When there is friction in re-setting up a closed workspace (e.g. re-setting up SSH commands, etc)
4. General convenience when going away from your computer for some time and returning

## Acceptance Criteria (Implementation)

- [x] User can set any timeout up to 24 hours from any client (VS Code, JetBrains + SSH access)
- [x] User cannot set the inactivity timeout more than 24h
- [x] User can set a global user preference for timeout
- [x] https://github.com/gitpod-io/website/pull/3517

## Acceptance Criteria (Measurement)

- [ ] What values do users set timeouts to? Do they need 24 hours? (e.g. understand use cases for timeouts)
- [ ] Are timeouts respected? e.g. users setting X timeout on a long running workspace that is then closed. 

## In scope

- https://github.com/gitpod-io/gitpod/issues/16085
- https://github.com/gitpod-io/gitpod/issues/16107
- https://github.com/gitpod-io/gitpod/issues/15945
- https://github.com/gitpod-io/gitpod/issues/16157
- https://github.com/gitpod-io/gitpod/issues/16200

## Out of scope

- https://github.com/gitpod-io/website/pull/3341
- https://github.com/gitpod-io/gitpod/issues/16089
- User can disable the editor inactivity timeout on a per-user basis
- https://github.com/gitpod-io/gitpod/issues/16083
- https://github.com/gitpod-io/gitpod/issues/16609
- https://github.com/gitpod-io/gitpod/issues/15304
- Review + see the current timeout for a workspace
- Admin / Global default or organisational policy (e.g. not per user)
- Scheduling timeouts
- API's for timeout 

## Related issues

- https://github.com/gitpod-io/gitpod/issues/16565
- https://github.com/gitpod-io/gitpod/issues/16090
- https://github.com/gitpod-io/gitpod/issues/16146
- https://github.com/gitpod-io/gitpod/issues/7719 + https://github.com/gitpod-io/gitpod/issues/9019
- https://github.com/gitpod-io/gitpod/issues/11355
- https://github.com/gitpod-io/gitpod/issues/11700
- https://github.com/gitpod-io/gitpod/issues/11263
- https://github.com/gitpod-io/gitpod/issues/10373
- https://github.com/gitpod-io/gitpod/issues/7685
- https://github.com/gitpod-io/gitpod/issues/6300
- https://github.com/gitpod-io/gitpod/issues/9221
- https://github.com/gitpod-io/website/issues/2144
- https://github.com/gitpod-io/gitpod/issues/13498

**Depends on:** 
- https://github.com/gitpod-io/gitpod/issues/9036

<details>
  <summary>Potential fixes</summary>

**Solutions for flexible timeout options:**

- **Setting a default per-user** - e.g. allowing users to change the default workspace timeout 
- **Setting a schedule** - e.g. allowing users to configure a schedule where workspaces do not timeout. [[1](https://gitpod.slack.com/archives/C02P236JZPC/p1675869034359899)]
- **Extending timeouts arbitrarily** - e.g. a command in workspace (similar to 3h boost)
- **Global default** - e.g. Self-Hosted installs able to change the global default (current default is 30min).
- **API for timeout** - For custom integrations, such as educational products that use Gitpod + want workspaces to timeout for cost reasons, but want to sleep / wake them programatically. 

</details>

<details>
  <summary>Original description</summary>
  
### Summary

Allow users to change the default workspace timeout and extend timeouts arbitrarily. Self-Hosted installs should be able to change the global default (usually 30min).

### Context

The automatic timeouts are a convenience feature, that should relieve users from any anxiety about leaving workspaces running forever and therefore creating unnecessary cost. 
Currently, it is fixed to 30min resp. 60min (+ 3h boost) for unlimited users. 
Once usage-based pricing exists we can allow users to freely choose their timeouts. 
We should do this on two levels:
 - setting a default per user
 - manual command in workspace (similar to 3h boost)

### Value

Depending on behaviour patterns and use cases, a different timeout might make sense.

### Acceptance Criteria

The new feature (user setting and workspace action) needs to be shipped to SaaS and Self-Hosted release.
The change has been communiticated.

### Measurement

The new feature is used by active users. Send events on use.

### Growth Area

expansion

### Persona(s)

Active users

</details>

**Comment by corneliusludmann** [comment]
See also:
- https://github.com/gitpod-io/gitpod/pull/8576.

**Comment by corneliusludmann** [comment]
Since https://github.com/gitpod-io/gitpod/pull/8576 is merged, we can set the regular workspace timeout and the extended workspace timeout (when the user clicked the “boost” button) per installation (via installer).

What's still missing is that users are able to set their custom workspace timeouts.

**Comment by loujaybee** [comment]
https://github.com/gitpod-io/customers/issues/57

**Comment by atduarte** [comment]
"Tab close timeout" is also an issue at times: https://github.com/gitpod-io/gitpod/issues/9036#issuecomment-1192679511

**Comment by loujaybee** [comment]
I'm going to take ownership of this for the time being, and assign to `team: IDE`. 

I'm also going to update from Q3 as this feature is dependent upon: 

- https://github.com/gitpod-io/gitpod/issues/9036

Due to the sensitivity / importance of the dependent pricing changes (i.e it's important we get it right) that it doesn't make sense to push for this change to be delivered in Q3.

**Comment by SecludedL** [comment]
Thank you for the great job on launching the Pay-as-you-go plan in such a short time! 

We switched to the new plan on Friday and still had the same timeout issues as before, meaning that when the browser is closed, the timeout is set to 3 minutes (which is a problem, since we're opting for the PaaG plan specifically to pay in order avoid these short timeouts).  Ideally, the workspace would continue running either until you stop it or until it hits the extended timeout (3h or more) and it would completely disregard heartbeat signals (such as having an active browser window).

Can you please confirm that you're still looking to remove the browser close timeout at least for PaaG customers? 

Thank you!

**Comment by andreafalzetti** [comment]
> Thank you for the great job on launching the Pay-as-you-go plan in such a short time!
> 
> We switched to the new plan on Friday and still had the same timeout issues as before, meaning that when the browser is closed, the timeout is set to 3 minutes (which is a problem, since we're opting for the PaaG plan specifically to pay in order avoid these short timeouts). Ideally, the workspace would continue running either until you stop it or until it hits the extended timeout (3h or more) and it would completely disregard heartbeat signals (such as having an active browser window).
> 
> Can you please confirm that you're still looking to remove the browser close timeout at least for PaaG customers?
> 
> Thank you!

This is something we believe it should be addressed in Q1, please bear with us until we have more details 🙏

**Comment by mbrevoort** [comment]
Now with PAYG, what's stopping us from offering significantly longer timeouts? 8 hours? 24 hours? 48 hours?

**Comment by mbrevoort** [comment]
A very simple "skateboard" could be to expand `gp timeout extend` to accept a time period. For example:
* `gp timeout extend 24h`
* `gp timeout extend 180m`

Up to some reasonable limit within the range of 24h - 72h.

**Comment by gtsiolis** [comment]
We could also make this a preference in user settings with 2-3 fixed options to select from later. Cc @mbrevoort

**Comment by rgoldfinger-quizlet** [comment]
It would be nice to have the option to extend both the inactivity timeout and the IDE disconnected timeout.

**Comment by svenefftinge** [comment]
https://github.com/gitpod-io/gitpod/pull/15815 adds a `gp timeout set <duration>`command

**Comment by svenefftinge** [comment]
@SecludedL Yes, that is definitely something we should be able to disable using that command as well.

**Comment by SecludedL** [comment]
@svenefftinge - thanks for the swift response! Please do let me know if there's something we can do on our own or if there's a specific issue I can follow to test the feature when it's implemented in Gitpod. Have a great weekend!

**Comment by svenefftinge** [comment]
For now, I fear the only way to avoid the onclose signal is to either not close the editor or disconnect your network before closing.

**Comment by mbrevoort** [comment]
I agree, the timeout should extend independent of whether an IDE or browser window is connected or not. If I want to extend the timeout for 24 hours then we should let it run for 24 hours regardless. With pay-as-you-go we should be giving more agency to users.

**Comment by loujaybee** [comment]
Thanks for the feedback @SecludedL, your request is now encapsulated in this issue: 

- https://github.com/gitpod-io/gitpod/issues/16089

I've also raised a couple of related issues, so will link those here, also. 

- https://github.com/gitpod-io/gitpod/issues/16085
- https://github.com/gitpod-io/gitpod/issues/16084
- https://github.com/gitpod-io/gitpod/issues/16083

**Comment by loujaybee** [comment]
Some other areas we can look to apply timeout control:

- **Admin/orgs/team:** Give timeout limit and controls to admins to restrict how much control users in an org have over their timeouts. Mostly to manage spend: e.g. https://github.com/gitpod-io/gitpod/issues/16090
- **User:** The ability for a user to set a timeout value as a default for all future workspaces. So the user doesn't have to run the command on each workspace start, or add to their `.gitpod.yml` 
- **Project:** Ability to set a specific timeout for a project, where there may be a perpetual need to use an extended timeout for that project, such as when doing long-running data tasks, tests, or sharing the environment for preview purposes.

**Comment by loujaybee** [comment]
As part of this work, we might want to consider aligning the free tier and paid timeout of 30/60 minutes given that a user can now set the inactivity timeout themselves.

**Comment by loujaybee** [comment]
Regarding the acceptance criteria: 

> User can set any timeout up to 24 hours from any client (VS Code, JetBrains + SSH access)

I believe this is completed, can we tick off?
