### ISSUE TITLE
Epic: Migrate to Installer

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#9097]
### Summary

WebApp is the last team that relies on the helm chart for deployments, we should get rid of it.

#### General approach

Go through components one by one and decide for each config to either:
   - work with a default
   - find a way to place variance in the installer

#### Tasks 
 - [x] Setup a diff tool between chart and installer to identify config diff https://github.com/gitpod-io/ops/pull/1558
   - [x] `open-vsx`
     - https://github.com/gitpod-io/gitpod/pull/9215
   - [x] `server`
     - [x] #9227
     - [x] #9297
     - [x] #9305
     - [x] remove `logLevel` from config, and take it from `LOG_LEVEL` env var
     - [x] make `defaultBaseImageRegistryWhitelist` configurable (or is this an imageBuilder concern?)
     - [x] make `definitelyGpDisabled` configurable
     - [x] make `disableDynamicAuthProviderLogin` configurable
     - [x] make `enableLocalApp` configurable
     - [x] `runDbDeleter`: = !dbSync.enabled
     - [x] `builtinAuthProvidersConfigured`: https://github.com/gitpod-io/gitpod/pull/9612
     - [x] payment
       - [x] ~add chargebee config to outer wrapper chart (cmp. [old](https://github.com/gitpod-io/ops/blob/gpl/webapp-installer/charts/gitpod_io/charts/gitpod/templates/chargebee-config-secret.yaml#L7-L18) [chart](https://github.com/gitpod-io/ops/blob/0ef3b446536cafa90598ae808fffe2b0aadc80c0/charts/gitpod_io/values.staging.yaml#L225-L233))~ already done by terraform
       - [x] add option to specify a secret to config.experimental.server.chargebeeConfig, and configure server to [find it](https://github.com/gitpod-io/gitpod/blob/948ae5192be0dd3d35431e6b0f5b443b1c61cfc1/install/installer/pkg/components/server/configmap.go#L142)
       - [x] set [server.config.EnablePayment](https://github.com/gitpod-io/gitpod/blob/948ae5192be0dd3d35431e6b0f5b443b1c61cfc1/install/installer/pkg/components/server/configmap.go#L140) when that secret is configured
     - [x] analytics: configure `GITPOD_ANALYTICS_WRITER` and `GITPOD_ANALYTICS_SEGMENT_KEY`
     - [x] license secret: set `GITPOD_LICENSE_TYPE` in wrapper chart as expected
     - [x] mount github-app-cert (just like payment-endpoint)
     - [x] [blockedRepositories](https://github.com/gitpod-io/gitpod/blob/main/components/server/src/config.ts#L164)
     - [x] workspaceGarbageCollection: defaults to true
   - [x] `ws-manager-bridge`
     - [x] ~add option `skipSelf` and use it [here](https://github.com/gitpod-io/gitpod
/blob/21263bd4e7acdffd1fb81c0056cc9f935159679c/install/installer/pkg/components/ws-manager-bridge/objects.go#L21)~ done based on "installation method"
     - [x] add option `experimental.webapp.wsManagerBridge.skipSelf` (default: false, set to `true` for SaaS)
   - [x] proxy
     - [x] proxy-ingress svc (wrapper chart)
     - [x] static IP
     - [x] serviceAnnotations (proxy, openVsxProxy & ideProxy)
   - [x] `db-sync` (wrapper chart)
   - [x] db
     - [x] `disableMigration` (default: false): disable jobs `dbinit-session` and `migrations` & `db-init` configMap
     - [x] validate gcloud-sql-token shape
   - [x] `messagebus` (well-tested in preview envs)
     - [x] validate config shape (incl. user/password)
   - [x] `payment-endpoint` (wrapper chart)
   - [x] setup wrapper-chart:
     - [x] https://github.com/gitpod-io/ops/pull/1977
     - [x] auth-providers
   - [x] cross-cutting:
     - [x] installationShortname: https://github.com/gitpod-io/gitpod/pull/9218
     - After meeting with self-hosted team:
       - [x] Move `PodConfig` section under a new `Common` field, to make it clearer that these values are cross-cutting and applicable to all teams.
       - [x] Rename `Affinity` method in `common` package to `NodeAffinity` (https://github.com/gitpod-io/gitpod/pull/9400)
       - [x] Make replicas default to 1 and use the configuration method in `common` everywhere.
       - [x] Configure tracing sampling parameters
 - [x] rollout to staging
 - [x] rollout to devstaging: remove the special bash post-processing [here from preview envs](https://github.com/gitpod-io/gitpod/blob/6bc0571a52f6c51d4ba782defbf8c027399b27fc/.werft/jobs/build/installer/post-process.sh#L89-L145) https://github.com/gitpod-io/gitpod/issues/9855
 - [x] rollout to prod
 - [x] cleanup
   - [x] #9487
   - [x] Remove the `dev/installer-diff` program (only needed for figuring out the diff of the installer vs helm chart).
 - [x] aftermath
   - [x] ~find a way to configure `repositoryPasslist`~ not required, deprecated anyway

### Collaboration

For collaboration and questions on the remaining tasks: [Notion sync doc](https://www.notion.so/gitpod/installer-work-sync-9b662039bc224c939b923e6db4d126d3).

### Context

Historically we all deployed with the helm chart but decided to go with the installer instead.

### Value

The value lies in alignment and getting rid of technical debt.

### Acceptance Criteria

We can deploy using the installer in all deployment modes, and delete to helm chart.

### Measurement

Does not apply

**Comment by geropl** [comment]
Finally closing this after all boxes are ticked. :checkered_flag:
