### ISSUE TITLE
Epic: Get rid of db-sync

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#9198]
### Summary

This is the epic for getting rid of `db-sync`, which was already discussed at length in the context of "Simplified Multi-Meta" in [this RFC](https://www.notion.so/gitpod/Simplified-Multi-Meta-9942f49ccfbe47b0a7e352970df13162).

### Context

 - basically summed up in [the RFC](https://www.notion.so/gitpod/Simplified-Multi-Meta-9942f49ccfbe47b0a7e352970df13162)
 - previous epic: #7435

### Value

 - enables more Gitpod clusters (e.g., asia) without adding yet another DB
 - enables delivering multi-cluster Gitpod to Self-Hosted customers (because it reduces setup complexity)

### Acceptance Criteria

 - we got rid of `db-sync`

### Measurement

 - when there is no `db-sync` deployment anymore, and we're still able to deploy to prod :upside_down_face: 

### Notion

Discussion related to this epic is [in Notion](https://www.notion.so/gitpod/WebApp-Epic-Get-rid-of-db-sync-a790d1d453fa482aa5041a8e0be39c28).

### Tasks

- [x] https://github.com/gitpod-io/gitpod/issues/14560
- [x] Create a sidecar container to configure Toxiproxy with a `latency` toxic.
- [x] Run the above sidecar in the Toxiproxy pod.
- [x] Deploy a second `slow-server` deployment which connects to `mysql` through Toxiproxy.
- [x] Allow `proxy` to route websocket connections with the `slow-database` protocol header to the `slow-server` deployment.
- [x] Allow setting of the `slow-database` websocket connection header from websocket connections from dashboard based on the value of a feature flag.
- [x] #14958
- [x] #14960
- [x] #15027
- [x] #14962
- [x] #14963
- [x] #14964
- [x] #14965
- [x] #14995
- [ ] #14996
- [ ] #14997
- [ ] #14998
- [x] #15297
- [x] #15298
- [x] #15328
- [ ] [db-sync] Look at slowest queries on Grafana and configure caching for them. (typeorm allows caching on a per-query basis).
- [x] #15655

**Comment by geropl** [comment]
Old workspace cluster table PR: https://github.com/gitpod-io/gitpod/pull/8539

**Comment by svenefftinge** [comment]
continues [here](https://github.com/gitpod-io/gitpod/issues/16265)
