### ISSUE TITLE
Epic: Prebuild logs reliability

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#9291]
### Summary

Prebuilds are core feature of Gitpod. However, currently access to logs from prebuilds is not consistent and reliable. Users can sometimes wait for a long to time to see any logs at all and in some instances the same logs do not show when the browser is refreshed. For example, Image Build logs are not persisted and currently only viewable while the image is building, but not after it has completed building.	

### Context

We have tackled elements of prebuild reliability in a previous epic - https://github.com/gitpod-io/gitpod/issues/7812. However, logs warrant a closer and more focused look.

The existing architecture will (likely) require changes to be able to persist logs consistently as well as bring log access closer to the workspace, and away from the current server.

### Value

Primarily, this epic aims to increase trust in prebuilds and enables users to understand what a prebuild is doing, why it is not working and how to fix it.

### Acceptance Criteria

* Log content (on both UI and API level) remains consistent during a prebuild, and after.
* Log content is visible to the user as soon as reasonable, and logs can be accessed for completed prebuilds.

### Measurement

* Reduced rate of prebuild bugs & issues raised
* Reduced support burden for Prebuilds

### Growth Area

* Acquisition
* Onboarding
* Exploration

### Issues
- [x] https://github.com/gitpod-io/gitpod/issues/8324
- [x] https://github.com/gitpod-io/gitpod/issues/4879
- [x] https://github.com/gitpod-io/gitpod/issues/8684
- [ ] https://github.com/gitpod-io/gitpod/issues/8452
- [ ] https://github.com/gitpod-io/gitpod/issues/9513

**Comment by jldec** [comment]
Added #8452 to this Epic so that we can close #7597

**Comment by jldec** [comment]
Added to Q2 roadmap per discussion with @geropl.

**Comment by jldec** [comment]
Closing in favor of #10361 and #9292.
