### ISSUE TITLE
Epic: Prebuild transparency

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#9292]
### Summary

Improve how we surface prebuild information, including status, duration and actionable errors to users
The main focus of this epic is on surfacing information about the "trigger" of a prebuild, and what consequence that trigger had.

### Context

In the past we focussed on increasing prebuild reliability technically:
 - https://github.com/gitpod-io/gitpod/issues/7812
 - https://github.com/gitpod-io/gitpod/issues/10361

But the _perceived_ instability - and source of a big chunk of inbound user requests - is caused by uncertainty about _if_, _how_ and _why not_ a prebuild was triggered by some user action. This also **affects Self-Hosted** as the question "is my SCM correctly setup" is a frequently brought up during/after installation and can trivially answered from such a "prebuild trigger" view.

Also, this uncertainty will only increase when it comes to introducing more options for configuring prebuilds in the context of [Usage Based Pricing](https://github.com/gitpod-io/gitpod/issues/9036).

### Value

Clear and understandable prebuild statuses will increase trust in Prebuilds and as result in Gitpod as a product. It will enable users to optimize their prebuilds to be able to get the most out of Gitpod.

### Acceptance Criteria

* Prebuild UI (and APIs) communicate prebuild information consistently
* Prebuild "triggers" are discoverable in the UI

### Growth Area

* Acquisition
* Onboarding
* Exploration
* Expansion

### Issues

- triggers UI:
  - [ ] ~~https://github.com/gitpod-io/gitpod/issues/7010~~
  - [x] https://github.com/gitpod-io/gitpod/issues/10764
  - [ ] ~~https://github.com/gitpod-io/gitpod/issues/10765~~
  - [x] https://github.com/gitpod-io/gitpod/issues/7938
 
- observability:
  - [ ] ~~https://github.com/gitpod-io/gitpod/issues/9170~~
  - [x] #10587

**Comment by jldec** [comment]
Added to [roadmap](https://github.com/orgs/gitpod-io/projects/27/views/1?filterQuery=label%3A%22team%3A+webapp%22).

**Comment by jldec** [comment]
Updated description with partially completed sub-issues and marking as done for Q3.
