### ISSUE TITLE
Epic: [kots] Revise KOTS Installation Configuration UI 

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#9661]
### Summary:
A review, and subsequent fixes and improvements to the KOTS installation UI 

### Context: 
The current experience using the KOTS installation UI is not as good as we want it to be. There are several issues we want to work on - using the limited tools we have at our disposal (KOTS UI only has limited functionality). Issues: 
- We don't link to the docs as much as we should to give more context
- We have not reviewed the ordering and grouping holistically since first creation - it has grown organically
- You currently have to use the config-patch for a few settings, mainly workspace resources. We want to minimize the usage of the config patch and instead use the UI as it is less error prone.

--> There is a limit to what we can do, and that is the availiable UI building blocks of the KOTS UI
--> Note: We will need to be very careful about rolling this out - this has the potential to break users configurations, and thus we need to test this before it goes out and provide a detailed explanation on how to upgrade! 

### Value
Improve the onboarding and installation experience for our Self-Hosted customers in order to increase the self-servicability of Gitpod Self-Hosted and hopefully reduce the likelyhood of misconfugration (&incidents).

### Measurement
Ask customers for feedback of the "improved" installation UI once released - iterate on this. 

### Issues: 
- [ ] Design pass to come up with a proposal of how to make improvements. Focus on consistency, readibility, UX, and linking to docs. Constrained by what is possible with KOTS UI
- [ ] https://github.com/gitpod-io/gitpod/issues/13452
- [ ] #13606
- [x] [this internal feedback about the certificate issuer name](https://gitpod.slack.com/archives/C01KLC56NP7/p1651248380457109)
- [x] This [internal feedback](https://gitpod.slack.com/archives/C01KLC56NP7/p1655795973498729) on naming of the SSH option
- [ ] [Feedback](https://github.com/gitpod-io/gitpod/issues/9661#issuecomment-1119491252) on container registry wording
