### ISSUE TITLE
Optimize the GUI for a smartphone/tablet

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#970]
Currently gitpod/theia is very uncomfortable to be used from a smartphone
- [ ] GUI is not optimized for small display
![image](https://user-images.githubusercontent.com/11302521/70226574-5e4b3b80-1751-11ea-9658-c8fcd3b8fe8d.png)

it's basically just desktop site view

- [ ] Editing the text doesn't work
![image](https://user-images.githubusercontent.com/11302521/70226442-247a3500-1751-11ea-90e6-ad5932b21589.png)

i can add a new text, but then i can't remove it.

- [ ] Smartphone/Tablet should have custom keyboard instead of the one used on the system
Using android keyboard for anything relevant to programming is uncomfortable to use since it doesn't have all the characters and getting them is usually pita unless FOSS alternative with custom layout is used. 

Another issue with this is that the keyboard usually obstructs the whole screen making it difficult to see the code and autofill.

Some apps like termux (https://termux.com/) handles this scenario using additional GUI which works sufficiently most of the time

![image](https://user-images.githubusercontent.com/11302521/70227097-4922dc80-1752-11ea-90a5-84271fca080c.png)

### References
- Request for tablet support - https://github.com/gitpod-io/gitpod/issues/28

**Comment by RDIL** [comment]
It works pretty well on my iPad...

**Comment by Kreyren** [comment]
> It works pretty well on my iPad...

Using useragent set on iOS with chrome 54 it seems to have the same GUI:
<img width="997" alt="image" src="https://user-images.githubusercontent.com/11302521/70396380-c8d9d100-1a08-11ea-98c6-4d3ce317191a.png">

i don't have the ability to test this on the iPad atm, but it seems that the GUI is same on all platforms which i believe could be adapted to be more functional and user-friendly.

(The issue with being unable to remove text on my phone still presists)

Example of proposed GUI for android:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/11302521/70396418-240bc380-1a09-11ea-92d1-4b5cb7cacd41.png">
^ Is much better to work instead of using zoom to work with version made for desktop PC and then using the same zoom to navigate on buttons.

![image](https://user-images.githubusercontent.com/11302521/70396448-66cd9b80-1a09-11ea-8e2f-4d939b72a536.png)
^ Utilizing the phone for touch-based GUI.

**Comment by jankeromnes** [comment]
Many thanks for these super helpful resources!

Currently, we're working on gradually improving the tablet experience (mainly for iPad, which is the biggest target). Until now, we've been closely following VS Code's UX (because we're a small team, and they seem to have great UX talent). But supporting touch-based devices is already venturing beyond this (as to my knowledge, you can't install VS Code on tablets or Chromebooks, so we're now in more "uncharted" territory for a modern IDE).

Smartphones are also a very important target, and will likely be the next form factor we tackle after tablet support is great. I personally feel the need to be productive with Gitpod on my phone (I've used Cloud9 like this before, and it's a must-have e.g. to do sysadmin or deploy quick fixes when on the go). I'm looking forward to better mobile support in Gitpod.

**Comment by Kreyren** [comment]
>  (because we're a small team, and they seem to have great UX talent).

WFIW i was working as a frontender for few months (i hated it so i focused on backend and this was around 7 years ago) and i'm former graphic designer so if you are going to making this UX decision open for contribution i would be willing to submit some ideas/mock-up and do testing.

**Comment by MarkusTiede** [comment]
Using an iPad Pro (11-inch) on iOS 13.2.3 with a physical keyboard: it’d be useful if the commandline prompt would not be hidden by the OS C&P toolbar. This applies after a couple of commands have been entered and the prompt is in the lower bottom area of the console.

**Comment by jankeromnes** [comment]
Another relevant issue: We should fix Apple Pencil support for Gitpod/Theia on iPad: https://github.com/eclipse-theia/theia/issues/6389

**Comment by jankeromnes** [comment]
Also, relevant update: You can now "install" Gitpod on iOS, and get a fullscreen experience, thanks to https://github.com/eclipse-theia/theia/issues/7607 being fixed.
