### ISSUE TITLE
Epic: fully support cgroup v2

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#9775]
### Summary

Our initial attempt at supporting cgroup v2 is located [here](https://github.com/gitpod-io/gitpod/issues/8350). 

We ran it in production for a short while (April 11-April 20th, roughly). During this time, we had trouble with CPU and IO limiting, which forced a downgrade to cgroup v1.

The intent of this epic is to fully support cgroup v2 again, and remain on it, at least for the saas. Gitpod must continue being compatible for cgroup v1 for self-hosted use cases.

### Context

We want to give users the ability to set [resource constraints](https://docs.docker.com/config/containers/resource_constraints/) when using docker in Gitpod. This is only possible with cgroup v2.

Additionally, we want to be able to [run Kubernetes workloads within Gitpod](https://github.com/gitpod-io/gitpod/issues/4889). Reliably supporting cgroup v2 is a foundational effort to supporting K3s, we will create a separate epic for supporting K3s. 

### Value

Precursors that must work, this provides a good core Gitpod experience, but doesn't add value beyond what we have now with cgroup v1 by itself:
- [x] CPU and IO limiting
- [x] Enabling fuse
- [x] https://github.com/gitpod-io/ops/issues/2028
<strike>Cache reclaim</strike> removed because we're going to use swap for now, to avoid a kernel upgrade

This is where the real value come in with cgroup v2:
- [x] #9776

Groundwork we should consider scheduling once this epic is done:
- [ ] https://github.com/gitpod-io/gitpod/issues/9688 (also needed for cgroup v1)

@atduarte @csweichel 

### Acceptance Criteria

cgroup v2 limiters must have feature parity with cgroup v1.

Customers must be able to specify their own resource constraints when using `docker run`.

### Measurement

We are able to run cgroup v2 in production, and customers are able to specify their own resource constraints.

How do we support resource constraints now? The containers that customers start are only subject to the resource constraints of their pod and workspace container. Therefore, even if they  do `docker run --cpus=".5" -it --rm busybox`, and then run `cpuburn`, it will try to use as many cores the workspace can access, regardless of the `.5` limit.

### Other

Related internal slack threads [[1](https://gitpod.slack.com/archives/C03372UP877/p1651690179566069?thread_ts=1651085324.490779&cid=C03372UP877)][[2](https://gitpod.slack.com/archives/C02F19UUW6S/p1651689904262559?thread_ts=1651588208.042839&cid=C02F19UUW6S)]

**Comment by atduarte** [comment]
> Gitpod must continue being compatible for cgroup v1 for self-hosted use cases.

I didn't know we needed this. Could you please elaborate on the reason? 🙏

**Comment by kylos101** [comment]
> > Gitpod must continue being compatible for cgroup v1 for self-hosted use cases.
> 
> I didn't know we needed this. Could you please elaborate on the reason? pray

@atduarte certainly, just updated the epic description with an Other section with references to internal Slack threads

**Comment by kylos101** [comment]
@Furisto we have this placeholder epic out there to fully support cgroup v2. Is there anything you'd recommend we add or change? 

I was talking with @utam0k today, and we added two issues for consideration:
1. https://github.com/gitpod-io/ops/issues/2028
2. https://github.com/gitpod-io/gitpod/issues/9688

**Comment by atduarte** [comment]
> updated the epic description with an Other section with references to internal Slack threads

@kylos101 aren't those references related with the benefits of cgroup v2? Was trying to understand why cgroup v1 will need to be maintained.

**Comment by aledbf** [comment]
For self-hosted, having only v2 could be an issue for managed solutions

**Comment by utam0k** [comment]
> Was trying to understand why cgroup v1 will need to be maintained.
Realistically cgroup v1 is still a major player. k8s only recently supported cgroup v2. it would not be surprising if there is software that only supports cgroup v1.

**Comment by atduarte** [comment]
@kylos101 all issues seem to have been resolved. Just tested the resource constraints in a Gitpod workspace (gen59). Should we close this Epic?

**Comment by kylos101** [comment]
:+1: yep! Thanks for the validation, @atduarte. :muscle:
