### ISSUE TITLE
Epic: WorkspaceService public API and validate usage from IDE

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#9866]
# Summary

This epic we implement the first service to be consumed by an internal client (IDE) and validate it.

# Context

Prior epic: #7900.

Extensively summed up in the [design doc](https://www.notion.so/gitpod/Design-Doc-Public-Gitpod-API-15cdeb5d3496448ca3b61187a8aac53f).

# Value
- provide a uniform, reliable, stable and versioned API
- potential to consolidate our tech stack (e.g. replace JSON-RPC and REST interfaces)
- centralise common aspects such as authentication, rate-limiting, circuit-breaking etc.
- more in the [design doc](https://www.notion.so/gitpod/Design-Doc-Public-Gitpod-API-15cdeb5d3496448ca3b61187a8aac53f)

# Measurement
This epic has been successfully finished when:
 - IDE has successfully converted to the WorkspaceService
 - we are confident in being able to operate the public API in production

# Steps
The Public API scaffolding and infrastructure is deployed as part of https://github.com/gitpod-io/gitpod/issues/9229, to validate the approach to the API, we need to increase usage and identify part forward with respect to API Clients.

In this task, we will focus on the following:
* Offer a subset of the Workspace Service to be consumed by the IDE
* Define health metrics and harden monitoring to enable further adoption.
* Validate the API with respect to ergonomics and content

# Tasks
- [x] https://github.com/gitpod-io/gitpod/pull/9704
- [x] https://github.com/gitpod-io/gitpod/issues/9787
- [x] #9923
- [x] https://github.com/gitpod-io/gitpod/pull/10052
- [ ] Setup Public API Health Dashboard
- [ ] Setup Public API Alerts & Runbooks

**Comment by david-bakin** [comment]
@easyCZ - Are epics supposed to just go stale?  Especially one where progress has been made? Also I don't get why the bot marked it completed when two tasks above are still unchecked? And shouldn't it take a _person_ not a bot to close an epic?  Just curious.  Especially as I'm waiting for various (other0 API things to actually happen (e.g., to be able to trigger a prebuild via a GitHub/GitLab CI step).

**Comment by easyCZ** [comment]
@david-bakin Sorry about this. Looks like we had a mis-configuration with the bot and it ended up closing this accidently. It definitely should not have been closed. Re-opening.
