### ISSUE TITLE
Epic: Require a Gitpod project for prebuilds 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#9898]
Now that projects are usable across git providers, Gitpod should limit prebuilds to repos with a project.

- [ ] Check for project before running prebuild
- [ ] Change documentation to explain that prebuilds require a project
- [ ] Post announcement about new prebuild requirement in changelog

**Comment by gtsiolis** [comment]
+1000 for this.
