### ISSUE TITLE
Epic: Self-Hosted via KOTS/Replicated M2 "bicycle"

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#9929]
### Summary

This is a follow up epic on #to make the replicated installation experience even more smooth and feature complete. 

### Context

The is a follow up milestone on our journey to fully implement Replicated/kots as the way to main way to install Self-Hosted Gitpod. The goal is to increase maturity and incorporate user feedback. 

### Value

- Further solidify installation experience
- Full support of snapshots & rollback
- Improved error handling
- Better visibility on licensing issues

### Acceptance Criteria 
We'll work from top to bottom:

- [x] https://github.com/gitpod-io/gitpod/issues/9933 (largely done as of 1st of June))
- [x] https://github.com/gitpod-io/gitpod/issues/10399 ( a week worth of work))
- [x] #9926 (could be week worth of work)
- [x] https://github.com/gitpod-io/gitpod/issues/10298 (blocked by https://github.com/gitpod-io/gitpod/issues/10397 - workspace team are stacked, unlikely to be done this month (June))
- [ ] https://github.com/gitpod-io/gitpod/issues/10359 (1 h to fully analyse this and ensure the proposed solution has the expected impact, one week to implement) 
- [x] https://github.com/gitpod-io/gitpod/issues/10725
- [x] https://github.com/gitpod-io/gitpod/issues/10337 (1 day or so)
- [x] https://github.com/gitpod-io/gitpod/issues/10244 (1 day worth of work - consider bundling as part of registry preflight check)
- [ ] https://github.com/gitpod-io/gitpod/issues/9661 (1 day worth of work - likely best one by someone else than Simon because he is the closest to it)
- [x] #11069
- [x] https://github.com/gitpod-io/gitpod/issues/10183 (couple of hours for license ID, couple of IDs for UI change)
- [ ] https://github.com/gitpod-io/gitpod/issues/9972 (requires https://github.com/gitpod-io/gitpod/issues/8933)
- [ ] https://github.com/gitpod-io/gitpod/issues/9971 (requires https://github.com/gitpod-io/gitpod/issues/8933))
- [ ] https://github.com/gitpod-io/gitpod/issues/10272 (1/2 a day)
- [x] https://github.com/gitpod-io/gitpod/issues/9981 (maybe solved y a more generic post process your yaml step)
- [x] #10247 (should be done by webapp)
- [x] https://github.com/gitpod-io/gitpod/issues/9982 (replicated issue - needs to be raised with them)
- [x] https://github.com/gitpod-io/gitpod/issues/8983 (should be done by webapp)
- [x] #9820 (raised with replicated)
- [x] https://github.com/gitpod-io/gitpod/issues/10257 (easy to fix)
- [x] https://github.com/gitpod-io/gitpod/issues/10306 (need replicated's help here)
- [x]  #8789 (currently blocked by [external issue](https://github.com/replicated-collab/replicated-gitpod/issues/4)) (we don't care about ubuntu anymore - which would make this obsolete)
- [x] #8861
- [x] #8865
- [ ] Video walkthrough of an air gapped installation for [internal](https://gitpod.slack.com/archives/C01KLC56NP7/p1654293542220629) purposes
- [x] https://github.com/gitpod-io/gitpod/issues/9931
- [x] https://github.com/gitpod-io/gitpod/issues/9937

### Measurement

- Feedback from users on newly released features here

**Comment by lucasvaltl** [comment]
@MrSimonEmms is there any open issue in here that we should be working on? I'd like to close this epic and instead work on the open issues separately as individual issues.

**Comment by MrSimonEmms** [comment]
Yeah, I think this can be closed
